### ISSUE TITLE
可否增加一个用户备注或者用户分类功能？

### ISSUE THREAD

**Issue by Topcckin** [v2board/v2board#100]
大佬好，能否增加一个用户备注或者用户分类功能？

**Comment by tokumeikoi** [comment]
用于什么场景下显示备注？

**Comment by Topcckin** [comment]
> 用于什么场景下显示备注？

首先，感谢大佬回答。A、B、C三个用户(群)都在订阅P下面，某些时候会去编辑P订阅下面中某个用户(群)，例如调整P订阅下面A用户(群)，B、C不动。这时候可以直接去看用户备注或者去看用户分类，就会方便很多。

**Comment by tokumeikoi** [comment]
要更新用户组下边的什么内容？

**Comment by 911211606** [comment]
1、订阅的和没订阅的可能需要分（群）类（发）备（邮）注（件）2、还有就是无法快速找到某个用户（进行编辑甚至更多功能），需要一页一页翻找
