### ISSUE TITLE
工单系统需求

### ISSUE THREAD

**Issue by movecat** [v2board/v2board#101]
1，工单不管 管理员或者用户回没回复，显示的状态都是待回复。
建议：如果任何一端回复后对方那边显示下已回复，比较直观点。

3，在就是附件上传，前后台增加附件上传功能，建议图片＋视频都能上传。

4，建议后台增加一个 可以添加预设回复的功能。

5，建议工单可以接入邮件系统，用户与管理员提交工单或者回复工单后能邮件通知对方。能及时得到信息反馈。

**Comment by xb0or** [comment]
第3个文件上传要限制大小和种类
