### ISSUE TITLE
面板中的「服務端口」這一項到底是什麼意思？

### ISSUE THREAD

**Issue by PoorerImmune** [v2board/v2board#102]
① 這個值和 v2ray-poseidon 的 config.json 中的 localPort 有何分別？
② 我採用 Nginx 配合 V2Ray 的方式來架設服務，V2Board 本身佔用了 443 連接埠，那我設定 WebSocket+TLS 連線方式時還能在「連接端口」和「服務端口」內填 443 嗎？

**Comment by Topcckin** [comment]
只要不是NAT，就填一样的。你这种要求建议父子节点配合使用。

**Comment by thank243** [comment]
给nat用下发配置的。比如nat主机随机端口你本地是12345，随机给你54321的外网端口。下发配置文件是让后端监听12345端口。你用不能让用户直接连接你12345 端口呗。
