### ISSUE TITLE
你好！支付之后不回调问题

### ISSUE THREAD

**Issue by bin008** [v2board/v2board#115]
我确定当面付配置是正确的。同样配置到网站上也是无误的。
下面是日志记录
/core/proxy/vmess/encoding: failed to read request header > websocket: close 1006 (abnormal closure): unexpected EOF
另外一个日志
/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))

**Comment by thank243** [comment]
你提交的日志和你支付宝回调没有任何关系。建议查看此issue
#116

**Comment by bin008** [comment]
也是同#116 配置一样的没有问题

**Comment by bin008** [comment]
我没有开cf 开了证书 重新安装之后还是不能回调。我确定当面付和网站对接没有问题。
之前我开了证书可以回调，现在突然不行。

日志如下：
public/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))

vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))

/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))

vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))

vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))

vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))

定时任务中显示
Running scheduled command: '/www/server/php/73/bin/php' 'artisan' check:order > '/dev/null' 2>&1
Running scheduled command: '/www/server/php/73/bin/php' 'artisan' check:commission > '/dev/null' 2>&1
★[2020-03-16 11:28:02] Successful

queue中显示
Exception trace:

1 pcntl_signal(Object(Closure))
/www/wwwroot/***/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:562

2 Illuminate\Queue\Worker::listenForSignals()
/www/wwwroot/***/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:104

Please use the argument -v to see more details.

ErrorException : pcntl_signal() has been disabled for security reasons

at /www/wwwroot/***/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:562
558| pcntl_async_signals(true);
559|
560| pcntl_signal(SIGTERM, function () {
561| $this->shouldQuit = true;

562| });
563|
564| pcntl_signal(SIGUSR2, function () {
565| $this->paused = true;
566| });

Exception trace:

1 pcntl_signal(Object(Closure))
/www/wwwroot/***/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:562

2 Illuminate\Queue\Worker::listenForSignals()
/www/wwwroot/***/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:104

Please use the argument -v to see more details.
