### ISSUE TITLE
当面付支付成功后 The signature is not match 问题

### ISSUE THREAD

**Issue by thank243** [v2board/v2board#116]
使用支付宝1.4RSA签名验签工具 
![无标题](https://user-images.githubusercontent.com/11692994/76704389-aa742780-6713-11ea-8968-5c99edf49996.png)
按上图所示配置，并将appid改成和支付宝当面付appid一致。
反复确认。应用公钥，支付宝公钥，私钥均正确。
提交订单后，支付成功，有回调。查看支付宝自助诊断工具，均成功，但是laravel日志提示如下图
![image](https://user-images.githubusercontent.com/11692994/76704438-02ab2980-6714-11ea-9b1c-8d4ab77e248a.png)

同样配置方式，在部分机器上可以实现回调，部分机器上始终无法回调。

**Comment by thank243** [comment]
现在猜测和cf以及lets证书有关。

**Comment by tokumeikoi** [comment]
1.2.3 fix it

**Comment by bin008** [comment]
我没有开cf  开了证书  重新安装之后还是不能回调。我确定当面付和网站对接没有问题。
之前我开了证书可以回调，现在突然不行。

日志如下：
public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))

vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))

/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))

vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))

vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))

vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))

定时任务中显示
Running scheduled command: '/www/server/php/73/bin/php' 'artisan' check:order > '/dev/null' 2>&1
Running scheduled command: '/www/server/php/73/bin/php' 'artisan' check:commission > '/dev/null' 2>&1
----------------------------------------------------------------------------
★[2020-03-16 11:28:02] Successful

queue中显示
 Exception trace:

  1   pcntl_signal(Object(Closure))
      /www/wwwroot/***/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:562

  2   Illuminate\Queue\Worker::listenForSignals()
      /www/wwwroot/***/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:104

  Please use the argument -v to see more details.

   ErrorException  : pcntl_signal() has been disabled for security reasons

  at /www/wwwroot/***/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:562
    558|         pcntl_async_signals(true);
    559| 
    560|         pcntl_signal(SIGTERM, function () {
    561|             $this->shouldQuit = true;
  > 562|         });
    563| 
    564|         pcntl_signal(SIGUSR2, function () {
    565|             $this->paused = true;
    566|         });

  Exception trace:

  1   pcntl_signal(Object(Closure))
      /www/wwwroot/***/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:562

  2   Illuminate\Queue\Worker::listenForSignals()
      /www/wwwroot/***/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:104

  Please use the argument -v to see more details.

**Comment by thank243** [comment]
@bin008 我再重复一遍。你贴的日志和你回调问题一点关系都没有。你可以试试把omnipay降级到3.0.6看下。我恢复正常了。

**Comment by jw-star** [comment]
> omnipay降级到3.0.6

请问怎么降级
