### ISSUE TITLE
功能增强：优惠劵可以批量生成

### ISSUE THREAD

**Issue by zzyemail** [v2board/v2board#118]
有时候需要大量的优惠券，希望能有批量生成功能和导出excel功能

**Comment by lokisama** [comment]
你说的是属于一张仅使用一次的绑定优惠券，任务系统用
现在的是属于推广优惠券，大家都可以用，推广站点用
设计不一样，可能要另外开系统

**Comment by limaojun** [comment]
> 有时候需要大量的优惠券，希望能有批量生成功能和导出excel功能

可以在数据库批量insert一下
