### ISSUE TITLE
订阅升降级

### ISSUE THREAD

**Issue by xb0or** [v2board/v2board#121]
A订阅10元100G流量
B订阅20元200G流量

我先买A订阅15天用完100G流量，然后再升B订阅，因为系统只计算剩余天数，所以只付费14.95就能升级到B订阅，同时又得到200G流量
14.95+10=24.95
反过来，先买B订阅用完流量买再买B订阅不仅不用付钱还出现了退款
应该把剩余流量也加入计算

**Comment by tokumeikoi** [comment]
你可以关闭续费或更换订阅重置流量
