### ISSUE TITLE
功能增加：希望能增加删除客户账号的功能

### ISSUE THREAD

**Issue by zhzhyu** [v2board/v2board#134]
虽然可以在数据库删除，但在后台设置一个按钮还是不错的

**Comment by tokumeikoi** [comment]
数据关联性较强，无法做删除，即使在数据库删除也会导致一些问题，而且删除用户本身没有任何意义，你可以进行封禁

**Comment by zhzhyu** [comment]
> 数据关联性较强，无法做删除，即使在数据库删除也会导致一些问题，而且删除用户本身没有任何意义，你可以进行封禁

我已经从数据库删了。。。有什么影响吗，有什么不就措施吗

**Comment by zhzhyu** [comment]
补救措施
