### ISSUE TITLE
【实测】更换订阅的发现

### ISSUE THREAD

**Issue by lokisama** [v2board/v2board#145]
版本 : 1.2.3
BUG : 升级订阅抵扣价格多算了，多送钱了。
重现：

1.套餐A：月付58，套餐B：年付790，折扣券：8折
2.用户先买套餐A，使用折扣券，抵扣11.6，实际支付46.4，时间：2020/03/29 00:18
3.用户升级套餐B，使用抵扣券，抵扣158，再抵59.9，实际需支付572.07，时间：2020/03/29 00:20
4.取消上一单，再次验证
用户升级套餐B，使用抵扣券，抵扣158，再抵59.82，实际需支付572.18，时间：2020/03/29 01:44

预测结果：步骤3，再抵应该是小于46.4（至少是58），而不是直接大于58？
猜测逻辑：没计算实际支付，约等于原价 58/30 *31（3月有31天，4月30天）
可能分子分母差了1天，也可能是某个hardcode，没看代码乱猜测莫责怪 T-T
现在去阅读大佬代码，不是挑刺，只希望大佬项目越来越好，加油！
（这块逻辑在工作中也碰到过，和钱有关，所以测试比较详细）

--------------------------  Edit by 03/29 2:24 ----------------------------
v2board/app/Http/Controllers/User/OrderController.php 
<pre><code>private function getSurplusValueByCycle(User $user, Plan $plan)
    {
        $dayPrice = 0;
        if ($plan->month_price) {
            $dayPrice = $plan->month_price / 2592000;  
//30天，找到了
        } else if ($plan->quarter_price) {
            $dayPrice = $plan->quarter_price / 7862400;  
//91天  感觉会有bug
        } else if ($plan->half_year_price) {
            $dayPrice = $plan->half_year_price / 15811200;  
//183天 感觉也会有bug
        } else if ($plan->year_price) {
            $dayPrice = $plan->year_price / 31536000;   
 //365天  碰到闰年可能有bug，虽然4年碰1次忽略不计，但今年刚好2020年
        }
        // exclude discount
        if ($user->discount && $dayPrice) {
            $dayPrice = $dayPrice - ($dayPrice * $user->discount / 100);
        }
        $remainingDay = $user->expired_at - time();  
// 由于3月是31天
        $result = $remainingDay * $dayPrice;  
//所以这里*31了
        return $result > 0 ? $result : 0;
    }
</code></pre>

大佬辛苦日理万机，小弟不才对这小bug提这个建议，没具体跑过
<pre><code>
// 生效中套餐抵扣金额  伪代码
...
$create_at = strtotime( date('Y-m-d H:i:s',$user->expired_at) . ' - 1 month');
$dayPrice = $plan->month_price / ( $user->expired_at - $create_at ); 
...
$create_at = strtotime( date('Y-m-d H:i:s',$user->expired_at) . ' - 3 months');
$dayPrice = $plan->quarter_price / ( $user->expired_at - $create_at );
...
$create_at = strtotime( date('Y-m-d H:i:s',$user->expired_at) . ' - 1 year');
$dayPrice = $plan->year_price / ( $user->expired_at - $create_at );
...
$remainingDay = $user->expired_at - time();  
$result = $remainingDay * $dayPrice;  

</code></pre>

**Comment by tokumeikoi** [comment]
有tg吗？

**Comment by lokisama** [comment]
> 有tg吗？

https://t.me/LyncaTech 大佬有群吗
