### ISSUE TITLE
群发邮件遇到线程数超出，请问在哪里更改发送时间间隔。

### ISSUE THREAD

**Issue by raychien326** [v2board/v2board#148]
谢大佬！
log提示部分如下：
Expected response code 250 but got code "432", with message "432 4.3.2 STOREDRV.ClientSubmit; sender thread limit exceeded [Hostname=SG2PR01MB3659.apcprd01.prod.exchangelabs.com]

发送邮箱为outlook
使用的是宝塔PM2

非常感谢

**Comment by tokumeikoi** [comment]
1.2.5

**Comment by raychien326** [comment]
Thank you！
