### ISSUE TITLE
增加修改默认管理地址的功能

### ISSUE THREAD

**Issue by zhzhyu** [v2board/v2board#152]
刚刚莫名有人开通了服务，没有付款，感觉是直接入侵后台开通的，希望能增加修改默认管理地址功能，增强安全性

**Comment by gcphym** [comment]
请问现在有办法更改吗 /admin感觉还是不太安全

**Comment by van7ish** [comment]
> 请问现在有办法更改吗 /admin感觉还是不太安全

早就有了
