### ISSUE TITLE
[建议]使用教程建议

### ISSUE THREAD

**Issue by replicatejtyo** [v2board/v2board#155]
建议取消教程分类：部分电脑不支持V2rayN，需要安装CLASH，但是分类后，分类菜单实在过小，无法看到。包括别的。
如果无法取消，建议增加一项：常见问题FAQ的分类，将常见问题写入此分类。

**Comment by nicholastz** [comment]
你后台不能自己添加吗？

**Comment by tokumeikoi** [comment]
1.2.4有提示选择客户端
