### ISSUE TITLE
stripe选择usd 但还是强制hkd

### ISSUE THREAD

**Issue by Nadenesmith1221** [v2board/v2board#156]
大佬，我的是美国的stripe账户，已开通支付宝和微信，我在v2b后台选择了usd货币，但是支付的时候有Server Error报错。我在stripe后台查询了日志，如下：
`{
  "error": {
    "code": "invalid_currency",
    "message": "Invalid currency: hkd. The payment method `alipay` does not support this currency in your region.",
    "type": "invalid_request_error"
  }
}`

**Comment by tokumeikoi** [comment]
这个问题是说你的账号不支持这个区域吧？
