### ISSUE TITLE
用户订阅流量到达80%后 流量邮件提醒的小问题

### ISSUE THREAD

**Issue by movecat** [v2board/v2board#160]
1，有个小问题，用户订阅流量到达80%以后会邮件通知用户。
如果在管理后台修改用户流量低于80%后，系统还是会每天发送提醒邮件给用户。
2，这个通知开关在用户中心，其实可以把流量提醒与到期邮件通知 这个功能放到管理后台。统一开启或者关闭。
建议是给个连续通知多少天后停止通知的选项。

**Comment by tokumeikoi** [comment]
1.2.4已经修复啦
