### ISSUE TITLE
关于配置DNS出错

### ISSUE THREAD

**Issue by nicholastz** [v2board/v2board#180]
### **出错图:**
![2020-04-07 21 00 45](https://user-images.githubusercontent.com/32432943/78672204-ea918900-7912-11ea-8bf3-77778a700e6c.jpg)
### **添加格式如下(加domain也同样):**
![WechatIMG165](https://user-images.githubusercontent.com/32432943/78672535-5b38a580-7913-11ea-9583-a890e22c5c02.jpeg)

**Comment by tokumeikoi** [comment]
与面板无关
