### ISSUE TITLE
诸多账号里多了很多莫名的退款及抵扣

### ISSUE THREAD

**Issue by timesons** [v2board/v2board#181]
![image](https://user-images.githubusercontent.com/9979023/78733104-0cbcf280-7977-11ea-9439-f580df490902.png)

![image](https://user-images.githubusercontent.com/9979023/78733061-e6975280-7976-11ea-8bca-98811f64122a.png)
前端面板为v1.2.5，后端poseidon 1.4.7 如图个人中心里只有11.9推广佣金，在下订单的时候莫名出现退款与抵扣金额，下订单完毕后进行第二次购买，又莫名出现余额支付，此时个人中心钱包里还是11.9，疑惑账号退款及抵扣金额是从哪里来的？（订单详情页面多次出现右侧‘结账区域’闪退问题, 刷新页面可以显示出来）
![image](https://user-images.githubusercontent.com/9979023/78733325-b4d2bb80-7977-11ea-80cf-320abf6efe42.png)
![image](https://user-images.githubusercontent.com/9979023/78733368-d5027a80-7977-11ea-94b3-26322f960488.png)

**Comment by timesons** [comment]
刷新个人中心后发现钱包金额有变动，又多出账户余额53.47
![image](https://user-images.githubusercontent.com/9979023/78733733-d8e2cc80-7978-11ea-9efe-7ff8b5de4132.png)

**Comment by timesons** [comment]
测试了一票已注册用户账号，个人中心金额为0，下订单时都出现不同金额的抵扣金 。。。
![image](https://user-images.githubusercontent.com/9979023/78735014-4f34fe00-797c-11ea-9cdb-8c683213bdf7.png)
![image](https://user-images.githubusercontent.com/9979023/78734979-2f9dd580-797c-11ea-9d55-236d2861b01a.png)

**Comment by cyril-cheng** [comment]
订阅只能买一个，你购买新订阅，以前的订阅就会被退款。用优惠券抵扣的，退款的时候也会直接变成无折扣退款返回钱包。

**Comment by timesons** [comment]
> 订阅只能买一个，你购买新订阅，以前的订阅就会被退款。用优惠券抵扣的，退款的时候也会直接变成无折扣退款返回钱包。

退款的规则是什么？系统是自动按使用时长及价格来进行升级或降级吗？

**Comment by cyril-cheng** [comment]
按全价这算退款，以前抵扣买的也会折算进去，所以我不设置优惠券，用优惠券会出现两种情况，一个是更换订阅出现白嫖，如果要杜绝白嫖那么就只能在后台关闭订阅更换。
