### ISSUE TITLE
佣金首次发放问题

### ISSUE THREAD

**Issue by timesons** [v2board/v2board#182]
![image](https://user-images.githubusercontent.com/9979023/78744753-f9208480-7994-11ea-818e-0ccb86cdee79.png)
“开启后佣金只会在用户没有付费订单的情况下进行发放”，用户没有付费订单，那按什么比例给邀请人发放呢？

**Comment by tokumeikoi** [comment]
这个文本提示有问题，仅被邀请人首次支付时才会产生佣金

**Comment by tokumeikoi** [comment]
1.3 fix 文本问题
