### ISSUE TITLE
clash更新0.9.5以后，订阅链接失效了

### ISSUE THREAD

**Issue by cyril-cheng** [v2board/v2board#194]
clash更新0.9.5以后，订阅链接失效了，不能获取节点信息。

**Comment by tokumeikoi** [comment]
clash哪里来的0.9.5版本？

**Comment by cyril-cheng** [comment]
这个啊
https://github.com/Fndroid/clash_for_windows_pkg
还有这个
https://github.com/BoyceLig/ClashR.For.Windows
普通用户谁会去直接使用二进制文件啊

**Comment by tangchuqi** [comment]
删除user里面的.config文件夹

**Comment by tokumeikoi** [comment]
0.9.5的clash win有问题，你可以用0.94

Sent from ProtonMail Mobile

開啟 週一, 4月 20, 2020 在 11:08, 唐楚淇 <notifications@github.com> 寫道：
