### ISSUE TITLE
用户管理>给用户发邮件问题

### ISSUE THREAD

**Issue by timesons** [v2board/v2board#195]
1.用户管理>选择给用户发邮件时，选择全部用户，经查询没有全部发送(已排除邮件发送数量限制问题)
2.用户管理>选择给‘订阅用户’发邮件时，包不包括'注册试用'所选择的套餐？

**Comment by 911211606** [comment]
你既然排除了数量限制，那就只有配置，队列，redis 这几个看看了，最好是提供下log

**Comment by tokumeikoi** [comment]
1.数据库mail_log表有发送日志
2.订阅用户就是有效用户
