### ISSUE TITLE
建议新增节点列表功能

### ISSUE THREAD

**Issue by QAQkk** [v2board/v2board#198]
目前未付费用户是无法查看套餐中包含哪些节点，已付费的用户也无法查看其他套餐中包含哪些节点。
建议添加一个节点列表功能，用户可以选择对应套餐卡片(可参考教程样式)查看该套餐中包含的节点、在线状态、标签等。

**Comment by tokumeikoi** [comment]
没有付费就能看到节点，这个意义不大吧？也没有先例啊

**Comment by Kaulssl** [comment]
仅可以查看节点名称即可。
因为可能会出现不同套餐包含节点不同节点的情况。
如SSPANEL中不购买同样也可以看到节点名称。
