### ISSUE TITLE
请求增加订阅套餐排序 并优化移动端显示

### ISSUE THREAD

**Issue by TerrorbladeART** [v2board/v2board#204]
1.请求增加订阅套餐排序 
2.并优化移动端的订阅列表显示，比如三个订阅套餐   移动端 在 [购买订阅]页面 需要向下滑动才能看到其它套餐，部分客户会认为只有一个套餐。请增加向下滑动提示 或者优化移动端的订阅套餐列表显示

**Comment by tokumeikoi** [comment]
1.排序1.3有了
2.这种用户你告诉他可以下拉他也不会
