### ISSUE TITLE
[功能增强]自定义用戶面板菜單

### ISSUE THREAD

**Issue by 911211606** [v2board/v2board#205]
v2board從我使用以來是一個功能非常強大的面板，有著其它面板沒有的簡潔，同時又有許多領先其它面板的功能。進來使用中，我購買了一款主題皮膚，希望在用戶的菜單那一欄中可以加入自定義菜單，讓我的用戶可以輕松返回首頁。這個功能應該不只是侷限我的情況，如果你有其他的網站同樣的可以添加去用戶的菜單欄

**Comment by tokumeikoi** [comment]
你购买了一款皮肤？

**Comment by 911211606** [comment]
之前購買的改改用
