### ISSUE TITLE
【功能增强】提供更多支付接口

### ISSUE THREAD

**Issue by snail-ju** [v2board/v2board#209]
目前支付接口有四：
1.支付宝 -> 方便但不安全(容易被查表)
2.BitpayX -> 方便但是对用户不友好
3.Stripe -> 申请门槛过高
4.PayTaro -> 停止注册
希望增加新的支付方式~~

**Comment by 911211606** [comment]
+1

**Comment by limaojun** [comment]
PayTaro 昨天开放注册了

**Comment by tokumeikoi** [comment]
所以有什么新的支付方式？

**Comment by raymao9** [comment]
@tokumeikoi 可以增加 Stripe 银行卡和 Paypal（可以使用银联借记卡）吗

**Comment by 911211606** [comment]
https://v2net.best敏感时期，暂时屏蔽大陆访问，如需访问暂时请使用临时订阅链接：https://bit.ly/2y8jRIs
