### ISSUE TITLE
关于订阅方案的问题

### ISSUE THREAD

**Issue by opoet** [v2board/v2board#21]
当一个用户在购买一个月的订阅以后，在用户使用完流量，而天数未到期时，再次购买一个月的订阅后，只是增加了订阅天数，而流量并没有增加，已使用的流量数目也未清零。

**Comment by Excalibur-osu** [comment]
同样的疑问...
流量是每月清零还是怎么?
续费无论按月还是季度还是什么都不会累加流量 只会累加时间

**Comment by opoet** [comment]
> 同样的疑问...
> 流量是每月清零还是怎么?
> 续费无论按月还是季度还是什么都不会累加流量 只会累加时间

下一个版本会解决
