### ISSUE TITLE
建议增加没有订阅的用户不显示订阅地址

### ISSUE THREAD

**Issue by kakakakarr** [v2board/v2board#216]
即便现在没有订阅的时候会提示订阅失败，但是也会导致部分用户以为订阅有问题或者泄露订阅地址风险，建议改成像IOS账号一样，没有订阅就提示没有有效订阅，不进行显示。

**Comment by tokumeikoi** [comment]
这个代码开源的人人都知道订阅地址

**Comment by kakakakarr** [comment]
有些人是没有开通订阅，先进行配置的，然后提示错误，就会认为你系统有问题。。。
