### ISSUE TITLE
【建议】域名被污染后支付宝Notify异步通知失败，加入可更改 URL 参数

### ISSUE THREAD

**Issue by jitdor** [v2board/v2board#222]
现时`1.2.5`版本的v2board里的`app/Http/Controllers/User/OrderController.php`对支付宝的异步通知定义为
```
$gateway->setNotifyUrl(url('/api/v1/guest/order/alipayNotify'));
```
假设v2board域名是`domain.com`, 如果该域名被DNS污染的情况下，国内支付宝异步通知将会失败（因为国内机器不能访问被污染的`https://domain.com/api/v1/guest/order/alipayNotify`，而支付宝的机器就在国内），导致v2board队列在付款后不会自动更新用户订阅。

此时如果我有备用域名`domain2.com`，我把系统配置里的站点URL配置从`domain.com`更改为`domain2.com`的话，我也需要更新全部节点的配置，而且后端的授权也会失效。

建议把`setNotifyUrl`里域名部分转为可于面板更改的参数，当域名被污染时可以随时改动异步通知的域名部分而不影响v2board其他设定。

**Comment by nishuo** [comment]
👍
