### ISSUE TITLE
[功能增强]工单增强

### ISSUE THREAD

**Issue by 911211606** [v2board/v2board#225]
用户发了工单能不能邮件提醒下，不然老是没有及时回复。还有就是问下工单如果添加关键词自动回复这个实现起来麻烦吗，不麻烦就考虑下，如果改动太多太麻烦就算了吧，怕不稳定-_-

**Comment by 911211606** [comment]
或者把工单下了，直接上个第三方的在线聊天，这样工单就不会太慢了

**Comment by tokumeikoi** [comment]
工单会做tg提醒，邮件提醒
