### ISSUE TITLE
用户仪表盘总览里的"待办工单"点击后不跳转

### ISSUE THREAD

**Issue by chengziorange** [v2board/v2board#226]
F12看了一下，点击“待办工单”的数字之后并没有请求发出。作为对比，点击“我的邀请”是可以看到有两个请求的，分别是"fetch"和“details”，请求的url分别是"https://my.domain/api/v1/user/invite/fetch"和“https://my.domain/api/v1/user/invite/details”

**Comment by betaxab** [comment]
最新的提交修复了。
