### ISSUE TITLE
请教下邮件配置方面的问题

### ISSUE THREAD

**Issue by hyjsos** [v2board/v2board#23]
按照教程，使用PM2启动了邮件队列，启动后的界面如下图。不知道有问题没。
![pm2](https://user-images.githubusercontent.com/34772779/73242147-0aa02000-41df-11ea-8f2a-6089dab5185e.png)

env里的邮件配置，不知道有没有配置错。
![env配置](https://user-images.githubusercontent.com/34772779/73242168-21467700-41df-11ea-9a16-7790100f312a.png)

重置密码界面点发送后，提示服务器错误。
![重置密码错误提示](https://user-images.githubusercontent.com/34772779/73242194-3a4f2800-41df-11ea-9415-02d7ce273fda.png)

希望大佬帮忙看看哪里有配置错的没。

**Comment by tokumeikoi** [comment]
pm2正确，报错的话storage/logs下有日志，如果没有的话就说明没有权限

**Comment by hyjsos** [comment]
> pm2正确，报错的话storage / logs下有日志，如果没有的话就说明没有权限

我更新了下最新的代码，现在倒是不报错了。但还是发不出邮件。
ssh下手动执行了下pm2里面的代码：显示如图
![image](https://user-images.githubusercontent.com/34772779/73279671-70fd6080-4228-11ea-934d-b1a0856288da.png)

**Comment by tokumeikoi** [comment]
laravel的日志文件就是报错，请仔细检阅

**Comment by hyjsos** [comment]
最后再请教下：laravel的日志文件里有这样一条报错重复出现，是redis的问题吗？
[2020-01-28 07:24:21] local.ERROR: Connection refused {"exception":"[object] (RedisException(code: 0): Connection refused at /www/wwwroot/cloud.v2-1900.site/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php:126)
[stacktrace]
#0 /www/wwwroot/cloud.v2-1900.site/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(126): Redis->connect('172.16.119.119', '6379', 0, NULL, 0, 0)
#1 /www/wwwroot/cloud.v2-1900.site/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(83): Illuminate\\Redis\\Connectors\\PhpRedisConnector->establishConnection(Object(Redis), Array)
#2 /www/wwwroot/cloud.v2-1900.site/vendor/laravel/framework/src/Illuminate/Support/helpers.php(422): Illuminate\\Redis\\Connectors\\PhpRedisConnector->Illuminate\\Redis\\Connectors\\{closure}(Object(Redis))
#3 /www/wwwroot/cloud.v2-1900.site/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(100): tap(Object(Redis), Object(Closure))
#4 /www/wwwroot/cloud.v2-1900.site/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(27): Illuminate\\Redis\\Connectors\\PhpRedisConnector->createClient(Array)
#5 /www/wwwroot/cloud.v2-1900.site/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(31): Illuminate\\Redis\\Connectors\\PhpRedisConnector->Illuminate\\Redis\\Connectors\\{closure}()
#6 /www/wwwroot/cloud.v2-1900.site/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php(110): Illuminate\\Redis\\Connectors\\PhpRedisConnector->connect(Array, Array)
#7 /www/wwwroot/cloud.v2-1900.site/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php(90): Illuminate\\Redis\\RedisManager->resolve('default')
#8 /www/wwwroot/cloud.v2-1900.site/vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php(298): Illuminate\\Redis\\RedisManager->connection('default')
#9 /www/wwwroot/cloud.v2-1900.site/vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php(207): Illuminate\\Queue\\RedisQueue->getConnection()
#10 /www/wwwroot/cloud.v2-1900.site/vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php(191): Illuminate\\Queue\\RedisQueue->migrateExpiredJobs('queues:verify_m...', 'queues:verify_m...')
#11 /www/wwwroot/cloud.v2-1900.site/vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php(167): Illuminate\\Queue\\RedisQueue->migrate('queues:verify_m...')
#12 /www/wwwroot/cloud.v2-1900.site/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\\Queue\\RedisQueue->pop('verify_mail')
#13 /www/wwwroot/cloud.v2-1900.site/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(123): Illuminate\\Queue\\Worker->getNextJob(Object(Illuminate\\Queue\\RedisQueue), 'verify_mail')
#14 /www/wwwroot/cloud.v2-1900.site/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\\Queue\\Worker->daemon('redis', 'verify_mail,oth...', Object(Illuminate\\Queue\\WorkerOptions))
#15 /www/wwwroot/cloud.v2-1900.site/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\\Queue\\Console\\WorkCommand->runWorker('redis', 'verify_mail,oth...')
#16 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#17 /www/wwwroot/cloud.v2-1900.site/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#18 /www/wwwroot/cloud.v2-1900.site/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#19 /www/wwwroot/cloud.v2-1900.site/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#20 /www/wwwroot/cloud.v2-1900.site/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#21 /www/wwwroot/cloud.v2-1900.site/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#22 /www/wwwroot/cloud.v2-1900.site/vendor/laravel/framework/src/Illuminate/Console/Command.php(201): Illuminate\\Container\\Container->call(Array)
#23 /www/wwwroot/cloud.v2-1900.site/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#24 /www/wwwroot/cloud.v2-1900.site/vendor/laravel/framework/src/Illuminate/Console/Command.php(188): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#25 /www/wwwroot/cloud.v2-1900.site/vendor/symfony/console/Application.php(1011): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#26 /www/wwwroot/cloud.v2-1900.site/vendor/symfony/console/Application.php(272): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#27 /www/wwwroot/cloud.v2-1900.site/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#28 /www/wwwroot/cloud.v2-1900.site/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#29 /www/wwwroot/cloud.v2-1900.site/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#30 /www/wwwroot/cloud.v2-1900.site/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#31 {main}
"}

**Comment by nishuo** [comment]
阿里云的SSL SMTP端口是465
你的是456

**Comment by xiaobinbins** [comment]
和您一样的问题 发不出去邮件，请问您解决了没有

**Comment by DocWho22** [comment]
和您一样的问题 发不出去邮件，请问您解决了没有？
cat queue-3.log

RedisException  : Connection refused

**Comment by xiaobinbins** [comment]
嗯嗯 可以发送了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "v2board/v2board"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月5日(星期三) 晚上6:09
收件人:&nbsp;"v2board/v2board"<v2board@noreply.github.com&gt;;
抄送:&nbsp;"xiaobinbins"<chenjinbinss@gmail.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [v2board/v2board] 请教下邮件配置方面的问题 (#23)





 
和您一样的问题 发不出去邮件，请问您解决了没有？
 cat queue-3.log
 
RedisException  : Connection refused

**Comment by DocWho22** [comment]
> 嗯嗯 可以发送了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "v2board/v2board" <notifications@github.com&gt;; 发送时间:&nbsp;2020年8月5日(星期三) 晚上6:09 收件人:&nbsp;"v2board/v2board"<v2board@noreply.github.com&gt;; 抄送:&nbsp;"xiaobinbins"<chenjinbinss@gmail.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [v2board/v2board] 请教下邮件配置方面的问题 (#23) 和您一样的问题 发不出去邮件，请问您解决了没有？ cat queue-3.log RedisException : Connection refused — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

能否请脚下您是如何解决的？
