### ISSUE TITLE
关于优惠卷建议

### ISSUE THREAD

**Issue by TerrorbladeART** [v2board/v2board#233]
建议增加 单个用户使用同一优惠卷次数的限制 。比如有个8折优惠卷 a用户可以疯狂使用此优惠卷重复购买套餐 。
甚至使用优惠卷买完A套餐 再去更换为其它套餐进行抵扣 再使用优惠卷

**Comment by 828768** [comment]
你们能把「券」这个字读对写对嘛。。。跟我读：quàn   ，你们都这样错读，感觉我辛苦高考都白费了，麻蛋
