### ISSUE TITLE
希望能增加path路径的设置和伪装网站的设置

### ISSUE THREAD

**Issue by zhzhyu** [v2board/v2board#237]
希望能增加path路径的设置和伪装网站的设置，虽然不确定这样能不能降低被墙，但也是一种有效的方法

**Comment by pty819** [comment]
同意

**Comment by TerrorbladeART** [comment]
WebSocket是干嘛的？！

**Comment by zhzhyu** [comment]
> WebSocket是干嘛的？！

我是说面板能设置，这样方便点

**Comment by VeryAdd** [comment]
> > WebSocket是干嘛的？！
> 
> 我是说面板能设置，这样方便点

请问 
![image](https://user-images.githubusercontent.com/22927845/84000604-8a14db80-a997-11ea-8631-823f93824c90.png)
路径分流是在这设置吗？ 比如说我想分流到/vv
请问我该怎么填写？

**Comment by pty819** [comment]
> > > WebSocket是干嘛的？！
> > 
> > 
> > 我是说面板能设置，这样方便点
> 
> 请问
> ![image](https://user-images.githubusercontent.com/22927845/84000604-8a14db80-a997-11ea-8631-823f93824c90.png)
> 路径分流是在这设置吗？ 比如说我想分流到/vv
> 请问我该怎么填写？


{
  "path": "/ray"
}
