### ISSUE TITLE
推荐使用docker一键部署,集成Nginx+PHP+MySQL+Redis

### ISSUE THREAD

**Issue by HiColinn** [v2board/v2board#248]
推荐一下封装的Docker镜像,帮助更多小白一键部署(讲真,真的是一键,比用删库塔更快),先上图:

![install_v2board](https://user-images.githubusercontent.com/65964332/83315527-1cf49e00-a253-11ea-8b25-1fdeb074260d.gif)
***
**镜像特点:**
镜像内集成Nginx-PHP-MySQL-Redis环境,Supervisor守护Cron,可一键部署v2board !

🟢一键 ❗

镜像内已经配置好Nginx-PHP-MySQL-Redis环境,以及默认配置文件,真正做到,一键部署!

🟡无交互初始化

镜像内集成了全自动无交互初始化安装v2board的脚本,避免交互输入,部署更快!
***
可以使用Supervisordctl查看每个进程没有启动成功,宿主机执行命令:

```shell
docker exec -it v2board supervisorctl status
```

正常情况下应该返回如下:

```shell
[root@Me v2board]# docker exec -it v2board supervisorctl status
mysql                            RUNNING   pid 10, uptime 0:05:40
nginx                            RUNNING   pid 8, uptime 0:05:40
php-fpm                          RUNNING   pid 9, uptime 0:05:40
redis                            RUNNING   pid 6, uptime 0:05:40
cron                          	 RUNNING   pid 5, uptime 0:05:40
```
***
由于某些不可名状的原因,此镜像虽然已经发布,但是我没有提供任何README说明,大家都懂的,逗逼站长的故事很惊悚.但是为了感谢v2board的开发者,我愿意将镜像源码提供给你们,由你们发布,我就不管了,哈哈哈哈.如果感觉不错请联系我.
另:感谢v2board的作品.

**Comment by tokumeikoi** [comment]
https://github.com/v2board/v2board-docker已经有了。

**Comment by leungzw** [comment]
> 推荐一下封装的Docker镜像,帮助更多小白一键部署(讲真,真的是一键,比用删库塔更快),先上图:
> 
> ![install_v2board](https://user-images.githubusercontent.com/65964332/83315527-1cf49e00-a253-11ea-8b25-1fdeb074260d.gif)
> 
> **镜像特点:**
> 镜像内集成Nginx-PHP-MySQL-Redis环境,Supervisor守护Cron,可一键部署v2board !
> 
> 🟢一键 ❗
> 
> 镜像内已经配置好Nginx-PHP-MySQL-Redis环境,以及默认配置文件,真正做到,一键部署!
> 
> 🟡无交互初始化
> 
> 镜像内集成了全自动无交互初始化安装v2board的脚本,避免交互输入,部署更快!
> 
> 可以使用Supervisordctl查看每个进程没有启动成功,宿主机执行命令:
> 
> ```shell
> docker exec -it v2board supervisorctl status
> ```
> 
> 正常情况下应该返回如下:
> 
> ```shell
> [root@Me v2board]# docker exec -it v2board supervisorctl status
> mysql                            RUNNING   pid 10, uptime 0:05:40
> nginx                            RUNNING   pid 8, uptime 0:05:40
> php-fpm                          RUNNING   pid 9, uptime 0:05:40
> redis                            RUNNING   pid 6, uptime 0:05:40
> cron                          	 RUNNING   pid 5, uptime 0:05:40
> ```
> 
> 由于某些不可名状的原因,此镜像虽然已经发布,但是我没有提供任何README说明,大家都懂的,逗逼站长的故事很惊悚.但是为了感谢v2board的开发者,我愿意将镜像源码提供给你们,由你们发布,我就不管了,哈哈哈哈.如果感觉不错请联系我.
> 另:感谢v2board的作品.

镜像在哪。。。来个启动脚本？
