### ISSUE TITLE
ERROR DIVISION BY ZERO

### ISSUE THREAD

**Issue by LewisXZC** [v2board/v2board#257]
1.2.5 更新到1.3之后会出现 Division by zero app/Services/OrderService.php:132)行，看了下代码。当$strToMonth[$item->cycle] 这里返回0的时候也就是$item->cycle = onetime_price的时候，($surplusMonth - time()) / 2678400 / $strToMonth[$item->cycle] 这里会除以0. 不知道是因为我这边升级设置漏掉了什么还是bug。 请看一下， 谢谢
<img width="732" alt="Screen Shot 2020-06-01 at 5 44 25 PM" src="https://user-images.githubusercontent.com/56447443/83469378-64865000-a434-11ea-9f46-a40eb3142a19.png">

**Comment by LewisXZC** [comment]
更新的时候直接跑的 sh update.sh

**Comment by tokumeikoi** [comment]
1.3.1已经处理了，历史余留问题
