### ISSUE TITLE
[bug]total_amount为0时 佣金正常计算问题

### ISSUE THREAD

**Issue by TerrorbladeART** [v2board/v2board#260]
根据 setInvite()函数代码得知
$order->total_amount > 0 时 才会计算佣金
而实际
total_amount = 0时 也会正常计算佣金
![image](https://user-images.githubusercontent.com/59191279/83633138-08a5fd80-a5d3-11ea-87a6-2b93e3f310e6.png)

**Comment by tokumeikoi** [comment]
你自己都描述了，逻辑是>0才会计算，实际如果=0也能计算你觉得可能吗？

**Comment by TerrorbladeART** [comment]
![image](https://user-images.githubusercontent.com/59191279/83942135-75afd200-a823-11ea-8051-85b8eb1964d0.png)
![image](https://user-images.githubusercontent.com/59191279/83942140-7d6f7680-a823-11ea-9b88-e1cb3a12d992.png)

可能
