### ISSUE TITLE
建议添加http2和quic配置功能

### ISSUE THREAD

**Issue by pty819** [v2board/v2board#261]
如题，目前只有tcp和ws，http2和quic的握手次数要少很多，可否在面板里添加这两个选项？

**Comment by thank243** [comment]
你的caddy都能配置。

**Comment by pty819** [comment]
> 你的caddy都能配置。

可以细说一下吗

**Comment by thank243** [comment]
> > 你的caddy都能配置。
> 
> 可以细说一下吗

https://caddyserver.com/docs/

或者群里找人给你代劳
