### ISSUE TITLE
[功能增强]希望可以在用户管理界面看到该用户的订阅地址

### ISSUE THREAD

**Issue by StriveMoring** [v2board/v2board#266]
使用场景：绝大部分用户都希望自己不用操作，一手交钱一手交货的模式

- 目前的后台权限不够，并不能完全控制（帮助）用户操作,一些必要的信息状态也看不到，比如该用户的订阅地址等等

目前想到两种解决方案：
- [1 ] 为后台用户管理新增一些用户端的功能，这个比较复杂要写很多代码
- [ 2] 增加一个切换到用户界面的按钮，直接跳转到对应的用户端，最大程度的控制（修正、帮助）用户行为

个人感觉第二种方案实现要简单一些，希望大佬考虑一下，感谢！

**Comment by Nightma7e** [comment]
同需求
