### ISSUE TITLE
更新1.3.1后优惠券添加失败

### ISSUE THREAD

**Issue by Andylee24** [v2board/v2board#274]
优惠券添加时显示请求失败，1.3.0时正常

**Comment by xiyu247** [comment]
在某些声明可以留空的值 不填的情况下创建优惠券会报server error

指定订阅这一项 在数据库里好像只能为null 如果设置了使用优惠券的时候就server error

**Comment by Andylee24** [comment]
好的谢谢！

**Comment by Pastechn** [comment]
经过多次测试 发现当前版本添加窍门：
- **填写**优惠券代码，**不选择**可用订阅，其他信息随意。此时提交，提示 `Server Error` ；
- **删除**优惠券代码，其他信息**保持不变**，再次提交即可成功添加；
- 对优惠券信息进行修改，即可选择可用订阅。
