### ISSUE TITLE
[前端优化] 功能建议

### ISSUE THREAD

**Issue by rmfeel** [v2board/v2board#280]
1，购买/续费支付成功后 没有弹出支付成功对话框，容易误解是否充值成功

**Comment by on99life** [comment]
2.用户中心首页 待办工单 点击无法跳转工单页面   待付订单和我的邀请均可以跳转 最新dev

**Comment by tokumeikoi** [comment]
> 2.用户中心首页 待办工单 点击无法跳转工单页面 待付订单和我的邀请均可以跳转 最新dev

当下发表回复的时间这个问题已经得到了解决



> 1，购买/续费支付成功后 没有弹出支付成功对话框，容易误解是否充值成功

该问题会被处理

**Comment by 828768** [comment]
购买的时候那个 `下单` 按钮不够明显，而支付方式显示过大，容易让人去点支付方式显示而忽略 `下单` 文字按钮，这个下单按钮应该加明显底色或者位置挪到支付方式下方，要不然总有傻逼找不到
