### ISSUE TITLE
用户使用流量80%告警邮件，只发送一次

### ISSUE THREAD

**Issue by yywudi** [v2board/v2board#284]
我发现的情况是， 如有用户30人，当月第一个超过80%流量的用户会收到邮件警告提醒。
之后的其他流量超80%的用户不会发送警告邮件。

另，流量已耗完不会发送任何通知邮件。

这些配置是有bug还是可以再哪里修改?

**Comment by wloot** [comment]
> 另，流量已耗完不会发送任何通知邮件。

原因是v2b目前只会选取后端提交的用户来发送流量提醒邮件

**Comment by yywudi** [comment]
这个issue 在1.4版本中已经修复。

> > 另，流量已耗完不会发送任何通知邮件。
> 
> 原因是v2b目前只会选取后端提交的用户来发送流量提醒邮件
按照这个解释就理解了，流量耗尽，用户已经在后端被删除了，不是有效用户
