### ISSUE TITLE
自动保存功能有缺陷 建议改进！

### ISSUE THREAD

**Issue by imrelax** [v2board/v2board#287]
后台的自动变更保存是一个很好的功能。确实很方便。
但是我在使用中还是发现了一些问题。
如果 你使用了 浏览器的密码保存功能。
那么在 某些功能下
比如: 教程的 APPID 这里。就会自动填充 浏览器保存的账号密码。
由于自动保存，，又不能很好的修改。 我尝试了修改配置文件。V2board.php,但是只要我再次访问这个页面。密码会自动回写
给我造成了很大的困扰。所以建议 修正下 APPID  账户密码这个位置  然后 看能否 增加手动保存吧！

**Comment by tokumeikoi** [comment]
卸载opcache或者更新到1.3.2-dev版本
