### ISSUE TITLE
Trojan 节点 SNI 配置

### ISSUE THREAD

**Issue by jitdor** [v2board/v2board#291]
V2board 1.3.1 版本里 Trojan 节点的 SNI 配置在订阅里的 `trojan://` 链接是以 `peer=` 作为字符串名称。但是目前 Qv2ray 客户端只接受以 `sni=` 为 SNI 配置的值对。是否可以考虑把 `peer=` 改为 `sni=` 或是加入对应 `sni=` 的字符串名称？谢谢。

**Comment by tokumeikoi** [comment]
这个要专门适配qv2ray，而不是修改当前的字符串，peer是兼容shadowrocket的

**Comment by U-v-U** [comment]
https://github.com/v2board/v2board/pull/295

The problem is resolved since PR596 has been merged.
