### ISSUE TITLE
[邮件配置]邮件配置建议

### ISSUE THREAD

**Issue by MsTata** [v2board/v2board#292]
希望可以增加SendGrid第三方邮件发送提供商，配置更方便些。

**Comment by MsTata** [comment]
利用api与邮件发送提供商对接进行邮件的发送功能

**Comment by syouko** [comment]
此时此刻正好在配置sendgrid中= = 头大，不知道是哪里出错了，日志正常发送，但数据库log里显示Cannot send message without a sender address

**Comment by MsTata** [comment]
sendgrid还是蛮好用的（个人感觉）小批量的来说的话

**Comment by lawrence1751** [comment]
> 此时此刻正好在配置sendgrid中= = 头大，不知道是哪里出错了，日志正常发送，但数据库log里显示Cannot send message without a sender address
> 
> //---
> 
> 更新，要重启PM2队列服务

想問大佬是大概如何配置的呢？
在設定sendgrid的域名認證成功後就卡了，希望能夠指點一下

**Comment by syouko** [comment]
> > 此时此刻正好在配置sendgrid中= = 头大，不知道是哪里出错了，日志正常发送，但数据库log里显示Cannot send message without a sender address
> > //---
> > 更新，要重启PM2队列服务
> 
> 想問大佬是大概如何配置的呢？
> 在設定sendgrid的域名認證成功後就卡了，希望能夠指點一下

不知道你进行到哪一步了。

在sendgrid创建完发件人后，继续创建一个API，

然后在v2b邮件配置的地方这样配置：

服务器地址：smtp.sendgrid.net
SMTP端口：587
SMTP加密方式：TLS
SMTP账号：apikey
SMTP密码：填入你刚刚创建的API
发件地址：你创建的发件人
模板：随你
