### ISSUE TITLE
易支付错误，显示该路由不支持GET方法。支持的方法：POST。

### ISSUE THREAD

**Issue by billylicn** [v2board/v2board#297]
我也遇到了这个错误，界面显示该路由不支持GET方法。支持的方法：POST。
这里是详细的错误信息
https://flareapp.io/share/J7ogZx78#F5

**Comment by billylicn** [comment]
#286 似乎也遇到了同样的错误

**Comment by xb0or** [comment]
修改/app/​Http/​Routes/​Gue­stRoute.php 就可以用了
<?php
namespace App\Http\Routes;

use Illuminate\Contracts\Routing\Registrar;

class GuestRoute
{
    public function map(Registrar $router)
    {
        $router->group([
            'prefix' => 'guest'
        ], function ($router) {
            // Plan
            $router->get ('/plan/fetch', 'Guest\\PlanController@fetch');
            // Order
            $router->post('/order/alipayNotify', 'Guest\\OrderController@alipayNotify');
            $router->post('/order/stripeNotify', 'Guest\\OrderController@stripeNotify');
            $router->post('/order/bitpayXNotify', 'Guest\\OrderController@bitpayXNotify');
            $router->post('/order/mgateNotify', 'Guest\\OrderController@mgateNotify');
            $router->post('/order/epayNotify', 'Guest\\OrderController@epayNotify');
            $router->get('/order/epayNotify', 'Guest\\OrderController@epayNotify');
           

            // Telegram
            $router->post('/telegram/webhook', 'Guest\\TelegramController@webhook');
        });
    }
}
