### ISSUE TITLE
[建议] 关于中转机制的完善

### ISSUE THREAD

**Issue by Pastechn** [v2board/v2board#298]
经过几天的使用，发现 v2board 对于那些仅以端口转发形式中转的流量无法很好的统计，基本还是根据未中转的节点倍率计算流量。这里提出一个改进建议：`通过设置不同的 UUID 实现单独统计流量`

一旦某个节点在配置时选择了父节点，就为用户分配一个额外的 UUID 进行连接，统计通过该 UUID 使用的流量再乘以节点倍率作为中转节点流量。若所有中转倍率相同，则不同节点的中转可以共用一个 UUID ；若存在倍率不同的中转，则将中转过的节点作为父节点进行套娃，一旦发现父节点已为中转节点，则重新分配一个 UUID 用于倍率计算。

说人话：就是增加一个判断逻辑。若存在父节点且父节点为直连节点，则生成一套额外的 UUID 用于中转倍率计算；若父节本身就是中转节点，则继续生成一套额外的 UUID ，依次套娃。倍率相同的中转节点处于同一层套娃中，使用相同的 UUID 来计算流量。

或者设置了父节点之后增加一个 UUID 选项，可以选择默认的或者之前创建的 UUID ，也可以新建一套 UUID 。

亦或是直接增加一个额外倍率的选项，每个额外倍率分配一套 UUID 。

一时头脑发热的想法，若有不妥之处望大佬海涵。这样的话改动量应该比较大，并且由于我不清楚后端的机制，不知道是不是根据 UUID 来判断用户数量，很可能也要跟着改，不知道能否实现。

**Comment by billylicn** [comment]
但是我发现一个问题，作为用户我可以手动使用倍率低的UUID来更换倍率高的UUID，这样我走的是倍率高的中转线路，但面板计费却是倍率低的中转线路。

**Comment by billylicn** [comment]
我有一个脑洞，因为中转线路的出口ip一般是固定的，即便用户UUID相同，节点端也能通过不同的出口来分辨不同的线路，这样提前设置好多个中转出口机ip，如果连接是从某个中转机ip发起的，就乘提前设置好的倍率，否则不乘。以上为个人拙见，如有错误请海涵。

**Comment by Pastechn** [comment]
UUID 替换的确是个漏洞 这个方案可能得放弃了 不过我觉得通过来源 IP 进行判断好像不太方便 因为目前 webapi 对接的话 倍率计算好像是通过前端完成的 后端好像只会上报流量之类的信息 这样的话后端可能得魔改一下了 并且 soga 和 poseidon 会不会跟进也是个问题
纯端口转发的中转的确难以单独计算倍率 如果中转能提供 API 来获取用户流量（比如某鸡家）的话 应该可以通过插件的形式解决这个问题
目前我能想到的比较完美的解决方案是在中转上使用 v2ray 进行链式转发或者任意门 但是这样又不适用于纯转发类型的中转 很矛盾 不知道有没有哪个巨佬能想出一个两全其美的方案
