### ISSUE TITLE
是否需要更换邮件样式

### ISSUE THREAD

**Issue by DesperadoJ** [v2board/v2board#30]
现在的邮件模板中，有一张经过base64编码的背景图，实测发往Gmail与QQ邮箱均无法正常显示，导致邮件不是很美观
![1581148268(1)](https://user-images.githubusercontent.com/38433236/74081666-8e35f880-4a8c-11ea-9afc-16db715ae92c.jpg)

下图是我修改的邮件模板，如有需要，我可以提供这样的模板
![1581148415(1)](https://user-images.githubusercontent.com/38433236/74081667-8ece8f00-4a8c-11ea-9024-c49449d7d3a9.jpg)

**Comment by lynnhou** [comment]
恕我直言，这也不甚美观…

**Comment by DesperadoJ** [comment]
> 恕我直言，这也不甚美观…

各有审美吧，如果还是觉得不美观也可以自己写一套

**Comment by AdolfHitler99** [comment]
y请问Gmai邮箱怎么设置
