### ISSUE TITLE
【功能增强】在 用户管理 添加  备注  一栏

### ISSUE THREAD

**Issue by pudding1111** [v2board/v2board#312]
我想和对面寝室一起租的服务器，搭建一个v2b面板，一共十几个人，因为都认识，能相互喊出来名字，但是注册的时候只能用邮箱注册，从十几个邮箱中找出特定同学太难了，所以，我恳请开发者增加  备注 一栏   字数限制在10字以内。
麻烦开发者了。

**Comment by betaxab** [comment]
同样需求这个。
