### ISSUE TITLE
[Feature]希望可以为Shadowsocks加入插件或者ws传输协议支持

### ISSUE THREAD

**Issue by kzw200015** [v2board/v2board#314]
比如v2ray-plugin什么的，方便通过ws协议过墙

虽然可以通过gost等工具实现ws协议过墙，但集成在一起会更加方便

**Comment by betaxab** [comment]
因为 v2board 使用的是 outline-ss，不支持 v2ray-plugin 功能，所以没有办法加进去。

**Comment by kzw200015** [comment]
@betaxab 那对于ws传输协议的支持可以实现吗

**Comment by betaxab** [comment]
等等吧。会魔改 outline 加一些功能。
