### ISSUE TITLE
V2Board还需要什么功能？

### ISSUE THREAD

**Issue by 911211606** [v2board/v2board#318]
说真的，从1.2.5开始，面板的功能已经趋近完善了。从增加Trojan开始我就觉得会增加好多的后端了，这个是一种方向，一种思路，与时俱进，我也觉得这样没什么错，唯一不好的地方就是太慢了。看着现在的版本更新是越来越慢，想来开发者也头疼，人是越来越多了，功能是越来越不好添加了，该添加什么功能好啊。其实我们用V2board一开始是因为简单，方便，不用配置一大堆的V2ray规则，这是最吸引我的地方吧。经过开发者的不断努力，面板也越来越人性化了，最近的版本更新连邮箱都可以可视化配置了，感觉确实也很好，但是不可避免的是面板可能会越来越臃肿，占用更多的服务器资源，我第一次安装这个面板，我的内心是有点拒绝的，我觉得这个对服务器要求还有点高，内存竟然要两个G，我只是抱着试试看的心态安装的。未来如果要添加更多的功能势必会增加更多的内存，而使用的人群其实并不是全部都用的，他们会觉得有些功能完全是多余的，从来都不使用，如果可以选择他们是不会使用的。如果可以设计成插件的样子就好了，我用这个功能我添加这个插件，甚至是自定义插件，自定义函数等等，开发个收费插件也不是不可以，毕竟面板是免费的，不要期望面板什么都有，面板有一个基础的功能就好了，更高级的功能建议付费使用。

**Comment by banxianl08** [comment]
希望开源前端或者大佬做付费主题

**Comment by mooyun** [comment]
add shadowsocks

**Comment by jinwyp** [comment]
前端开源吧， 很多页面都没有分页选择每页多少， 这也太不统一了啊， 为什么有的页面有 有的页面没有？

**Comment by maker2002** [comment]
是啊，前端开源是刚需啊...想自己添加个按钮都不行。

**Comment by 911211606** [comment]
https://v2net.best敏感时期，暂时屏蔽大陆访问，如需访问暂时请使用临时订阅链接：https://bit.ly/2y8jRIs
