### ISSUE TITLE
tls问题？

### ISSUE THREAD

**Issue by Topcckin** [v2board/v2board#32]
您好，在配合nginx分流使用v2ray的时候，证书只在nginx配置，v2ray就不要配置证书，面板节点不勾选tls，生成的订阅链接订阅之后，需要手动勾选上tls选项才能正常使用。发现的这个问题，来报告一下，再次感谢大佬。

**Comment by FishMagic** [comment]
你可以把面板生成配置文件时的tls内容注释掉，这样无论你选什么后端就不会配置tls了。
位置 app/Http/Controllers/Server/DeepbworkController.php Line135-139

**Comment by Topcckin** [comment]
> 你可以把面板生成配置文件时的tls内容注释掉，这样无论你选什么后端就不会配置tls了。
> 位置 app/Http/Controllers/Server/DeepbworkController.php Line135-139

非常感谢，操作OK。

**Comment by Topcckin** [comment]
如果以后能够新增一个关于这个证书的功能就好了。

**Comment by Topcckin** [comment]
我想到的办法是，在选择支持tls选项过后，增加一个真假tls功能的按钮，真tls按钮，即从/home/目录获取证书；假tls按钮，则不从/home/目录获取证书。这样应该能解决上述问题。
