### ISSUE TITLE
安装不了，可以解答一下解决方案嘛

### ISSUE THREAD

**Issue by eshakm** [v2board/v2board#320]
在执行php artisan v2board:install命令之后，提示了PHP Warning:  require(/www/wwwroot/qqqqq/vendor/autoload.php): failed to open stream: No such file or directory in /www/wwwroot/qqqqq/artisan on line 18

Warning: require(/www/wwwroot/qqqqq/vendor/autoload.php): failed to open stream: No such file or directory in /www/wwwroot/qqqqq/artisan on line 18
PHP Fatal error:  require(): Failed opening required '/www/wwwroot/qqqqq/vendor/autoload.php' (include_path='.:/www/server/php/73/lib/php') in /www/wwwroot/qqqqq/artisan on line 18

Fatal error: require(): Failed opening required '/www/wwwroot/qqqqq/vendor/autoload.php' (include_path='.:/www/server/php/73/lib/php') in /www/wwwroot/qqqqq/artisan on line 18

这是怎么回事，什么原因，完完全全按照教程操作的，就安装不了

**Comment by mooyun** [comment]
大家都安装的了，可以找找自己的原因，如若真安装不了早就炸锅了

**Comment by LongStudy** [comment]
同样问题，解决了吗

**Comment by toyleh** [comment]
我也是这种情况

**Comment by LongStudy** [comment]
建议内存小的机虚拟内存开大点
