### ISSUE TITLE
[功能增强]对Clash订阅进行分组

### ISSUE THREAD

**Issue by Po810C** [v2board/v2board#321]
希望能在面板中自行对选定节点设置变量，应用于 custom.clash.yaml 文件中，现有的 $app_name 不能对线路进行分组

**Comment by betaxab** [comment]
这些请自己来改。

**Comment by wsa01378** [comment]
@Po810C 自用魔改
https://paste.ubuntu.com/p/kTSSbV2Ccb/

**Comment by Po810C** [comment]
我想表达的意思是，我有一些普通节点和iplc节点，我想通过自定义分组来使clash自动选择不选到iplc节点
