### ISSUE TITLE
每天凌晨00：00分，会随机删除数据库用户数据

### ISSUE THREAD

**Issue by Best-Lew** [v2board/v2board#334]
每天一过晚上12点，就会随机删除最新注册那几个用户的流量使用数据，比如今天有100位用户，新增了10位用户，今天晚上12点就会随机清除掉110号用户到90号用户之间随机数量的流量使用数据，第二天往返重复，求解？开始以为是服务器数据库有问题，更换了服务器，备份了数据库还原过去之后还是出现这个问题。。。

**Comment by sdfsdfsdf145314364** [comment]
这么离谱？？？

搞的都有点不敢商用了，目前正计划转向v2board呢。

**Comment by 4rat** [comment]
现在1.51版本还存在吗？

**Comment by tokumeikoi** [comment]
开源项目请自行阅读代码看问题是否存在在发送issue，免得浪费时间解释。
