### ISSUE TITLE
[bug]该订阅下存在订单无法删除

### ISSUE THREAD

**Issue by sdfsdfsdf145314364** [v2board/v2board#341]
订阅购买后，用户升级成其他套餐，然后想删除这个订阅就会这样。

**Comment by van7ish** [comment]
> 订阅购买后，用户升级成其他套餐，然后想删除这个订阅就会这样。

因订阅下存在历史订单，故不可删除订阅。

**Comment by aldington-david** [comment]
__

> > 订阅购买后，用户升级成其他套餐，然后想删除这个订阅就会这样。
> 
> 因订阅下存在历史订单，故不可删除订阅。

请问如何才能删除订单
