### ISSUE TITLE
[功能增强]请求支持Shadowsocks原版客户端订阅。

### ISSUE THREAD

**Issue by sdfsdfsdf145314364** [v2board/v2board#342]
RT

**Comment by betaxab** [comment]
Android 原版 SS 客户端没法支持，因为那边的开发者非常顽固不肯实现 USER-AGENT 功能。详见 issue: https://github.com/shadowsocks/shadowsocks-android/issues/2589
Windows 原版 SS 客户端可以支持，稍等我可以提供相关代码。

**Comment by shikkoku** [comment]
奇怪，按道理SIP008订阅最先是由Android 原版 SS 客户端支持的，后来Windows版SS客户端发行版才加入支持。
