### ISSUE TITLE
【建议】签到。

### ISSUE THREAD

**Issue by sdfsdfsdf145314364** [v2board/v2board#351]
希望能增加一个签到功能，给有套餐的用户进行签到，每天设置一个随机赠送流量或者固定流量。

**Comment by jw-star** [comment]
+1

**Comment by betaxab** [comment]
签 NM，不知道现在某面板签到流量全是 JS 脚本在刷？增加服务器负担的同时给自己找不痛快。还不如多给订阅设置点流量更实用一些。

**Comment by sdfsdfsdf145314364** [comment]
> 签NM，不知道现在某面板签到流量全是JS脚本在刷？增加服务器负担的同时给自己找不痛快。还不如多给订阅设置点流量更实用一些。

注意审题:给有套餐的用户进行签到，每天设置一个随机赠送流量或固定流量
有脚本刷又如何，你不买我的套餐我凭什么让你刷呢。

**Comment by unsir** [comment]
duck不必。
对于使用js刷的用户，粘性不会提升
对于不会用js刷的用户，首先对他们来说不公平，其次，粘性提升了以后你想干嘛？本来这个服务就不是个高频服务，你还想直播带货不成？

**Comment by miniaoe** [comment]
签到功能很鸡肋，不建议加

**Comment by jinwyp** [comment]
反对，不要加
