### ISSUE TITLE
【功能添加】建议

### ISSUE THREAD

**Issue by dompling** [v2board/v2board#353]
能不能像魅影一样的订阅链接在 response 里面返回流量的使用情况呢？例如 
headers['subscription-userinfo'] = 'upload=0;download=0;total=0;'
这样的话我可以使用机场订阅流量的小组件了，可以比较方便和直观的看到。

**Comment by DinGood** [comment]
我使用机场的时候，看到过这个功能，对用户来说确实很方便。
