### ISSUE TITLE
stripe GBP支付宝订单无法识别

### ISSUE THREAD

**Issue by Nadenesmith1221** [v2board/v2board#372]
stripe GBP支付宝订单无法识别，求大佬解决一下
![photo_2020-12-23_23-37-34](https://user-images.githubusercontent.com/58839540/103024192-52176380-458a-11eb-9bba-5c264fd196e2.jpg)

**Comment by Nadenesmith1221** [comment]
实际测试一个661.91的订单，支付宝这边会经过汇率计算，需要付款671.18，75.46英镑，所以我觉得这个支付计算还是有点问题。另外扫码支付仍然会提示订单无法识别

**Comment by Nadenesmith1221** [comment]
实际测试微信支付没有问题

**Comment by liushmh** [comment]
这个问题还存在吗？我也碰到一样的问题了。

**Comment by ceceyuen** [comment]
一样的问题, any solution?

**Comment by coder-bts** [comment]
@liushmh @ceceyuen @Nadenesmith1221 你们解决了吗？同样问题

**Comment by liushmh** [comment]
没有解决，我已经放弃了 @coder-bts

**Comment by coder-bts** [comment]
@liushmh 你是一直使用 Stripe 最近才出现问题还是刚刚开始使用 Stripe 并且 Alipay 没有成功过？

**Comment by liushmh** [comment]
@coder-bts 从来没有成功过

**Comment by liushmh** [comment]
@coder-bts 我找了不同的手机，不同的地区，都试过了，我也问了下stripe的客服，最终结果就是没解决。

**Comment by coder-bts** [comment]
@liushmh 刚才在其他的 stripe 合作站点测试了一下，问题仍然复现，所以不是 v2b 的锅。我联系了 stripe 的 alipay 专员介入了。

**Comment by coder-bts** [comment]
@liushmh 我这边解决了，但怎么解决的还真不知道。

**Comment by coder-bts** [comment]
该问题已解决。且不是 V2board issue，建议 close @deepbwork

**Comment by sunyinghao5438** [comment]
@coder-bts 请问是怎么解决的呢？我目前也有这样的错误

**Comment by rustdesk** [comment]
问题还在，不是v2board问题，是stripe问题

**Comment by Tommy131** [comment]
> 实际测试微信支付没有问题

想问一下您是怎么申请到微信支付的，我提交申请了几个月了都没批下来，只有AliPay能用。

**Comment by hietsusama** [comment]
> > 实际测试微信支付没有问题
> 
> 想问一下您是怎么申请到微信支付的，我提交申请了几个月了都没批下来，只有AliPay能用（不过最近几天AliPay好像也出现问题了，无法支付）。

因为你买的是美国等滥用地区账号，有些资料同一个开几百个账号，wx是需要独立审核的，不过很正常。
可以找我买日本的Stripe 信誉度高 可开WX ZFP JCB @chain_a

**Comment by Tommy131** [comment]
> > > 实际测试微信支付没有问题
> > 
> > 想问一下您是怎么申请到微信支付的，我提交申请了几个月了都没批下来，只有AliPay能用（不过最近几天AliPay好像也出现问题了，无法支付）。
> 
> 因为你买的是美国等滥用地区账号，有些资料同一个开几百个账号，wx是需要独立审核的，不过很正常。
> 可以找我买日本的Stripe 信誉度高 可开WX ZFP JCB @chain_a

忘记说了。。我是用的自己的身份信息申请的欧洲区Stripe

**Comment by HongLouWang** [comment]
美元也不行，今天刚跟stripe客服交涉过，客服说是woocommerce的问题

**Comment by superopengl** [comment]
遇到了一模一样的error message。联系了Alipay海外客服，协同Stripe客服，得到的答复是“我们的商品没有通过Alipay的审核，所以不放权给Stripe使用Alipay”。

因为我们是海外贩售虚拟商品（不需要shipping的），我们的主观猜测是Alipay不支持海外贩售虚拟商品，以防止比如洗钱之类的不法活动（纯属个人猜测）。
