### ISSUE TITLE
请问前端如何配置tcp+http，看了默认的tcp，配置出来的只有none

### ISSUE THREAD

**Issue by 1978245715** [v2board/v2board#387]
如题，想要伪装一下http，如果需要自定义配置又要怎么修改呢

**Comment by betaxab** [comment]
由于这种配置容易被墙，所以没有添加支持 HTTP 混淆的计划。

**Comment by ChuJian2** [comment]
請問我已經在app/utils/URLSchemes.php   app/Services/ServerService 修改為tcp+http，爲什麽後端仍然是tcp+none
