### ISSUE TITLE
邮件无法正常发送

### ISSUE THREAD

**Issue by STARTOKEN-LAB** [v2board/v2board#390]
前端显示发送成功，但是一直收不到，一直排查。

数据库报错 

Connection could not be established with host smtpdm-ap-southeast-1.aliyun.com :failed loading cafile stream: `/etc/pki/tls/certs/ca-bundle.crt'

**Comment by STARTOKEN-LAB** [comment]
替换gmail发送邮件 数据库报错

Connection could not be established with host smtp.gmail.com :stream_socket_client(): unable to connect to tsl://smtp.gmail.com:587 (Unable to find the socket transport "tsl" - did you forget to enable it when you configured PHP?)

**Comment by STARTOKEN-LAB** [comment]
failed loading cafile stream: `/etc/pki/tls/certs/ca-bundle.crt'

更换google发信之后 数据库报错这个

**Comment by betaxab** [comment]
你的 linux 环境有问题，建议更换纯净 debian/ubuntu 系统，然后重新配置 v2board。

**Comment by STARTOKEN-LAB** [comment]
> 你的 linux 环境有问题，建议更换纯净 debian/ubuntu 系统，然后重新配置 v2board。

OK 我重新更换系统测试一下

**Comment by STARTOKEN-LAB** [comment]
已解决
