### ISSUE TITLE
Oh NO, 大哥，License 里不是我，麻烦别写我。

### ISSUE THREAD

**Issue by ssrpanel** [v2board/v2board#4]
https://github.com/v2board/v2board/commit/d9dcddd5366800800493ac2fba9461ce658de30c#diff-9879d6db96fd29134fc802214163b95a

**Comment by ssrpanel** [comment]
风萧萧兮易水寒，胖虎一去兮不复还

**Comment by vft9nesd** [comment]
233333333

**Comment by deepbwork** [comment]
這真的是很蠢了
