### ISSUE TITLE
用户界面》我的订阅节点在线状态和本地是否能出墙有关系吗？

### ISSUE THREAD

**Issue by cdnf** [v2board/v2board#403]
有个奇怪的现象，同一个账号同一个wifi网络环境下：

1. macOS上浏览器打开用户后台，节点状态全是红色离线，此时clashx测试延时也全是失败的，不能出墙
2. iOS上浏览器打开用后后台，节点状态蓝色正常，小火箭也正常连接，能出墙

不是刷新的问题，想不到为什么会是这个现象，屌大的来说说怎么回事？

**Comment by STARTOKEN-LAB** [comment]
重启v2board面板

**Comment by 828767** [comment]
> 有个奇怪的现象，同一个账号同一个wifi网络环境下：
> 
> 1. macOS上浏览器打开用户后台，节点状态全是红色离线，此时clashx测试延时也全是失败的，不能出墙
> 2. iOS上浏览器打开用后后台，节点状态蓝色正常，小火箭也正常连接，能出墙
> 
> 不是刷新的问题，想不到为什么会是这个现象，屌大的来说说怎么回事？

重启面板？你说的是面板服务器吧？貌似和你 #391 不太一样

**Comment by raychien326** [comment]
> 有个奇怪的现象，同一个账号同一个wifi网络环境下：
> 
> 1. macOS上浏览器打开用户后台，节点状态全是红色离线，此时clashx测试延时也全是失败的，不能出墙
> 2. iOS上浏览器打开用后后台，节点状态蓝色正常，小火箭也正常连接，能出墙
> 
> 不是刷新的问题，想不到为什么会是这个现象，屌大的来说说怎么回事？

检查你的传输协议，不谢。

**Comment by 828767** [comment]
> 检查你的传输协议，不谢。

好奇是什么协议，http和https都不会影响节点状态吧

**Comment by louisyoung** [comment]
> 有个奇怪的现象，同一个账号同一个wifi网络环境下：
> 
> 1. macOS上浏览器打开用户后台，节点状态全是红色离线，此时clashx测试延时也全是失败的，不能出墙
> 2. iOS上浏览器打开用后后台，节点状态蓝色正常，小火箭也正常连接，能出墙
> 
> 不是刷新的问题，想不到为什么会是这个现象，屌大的来说说怎么回事？

我是同一个订阅mac上可以用，win 安卓却用不了

**Comment by cdnf** [comment]
也不知道什么问题，传输协议搞不懂，个别人出现，服务器上啥也没异常，还是关了吧
