### ISSUE TITLE
大问题 优惠券可以反复套娃 卡出超低价格

### ISSUE THREAD

**Issue by zdrtyujm** [v2board/v2board#408]
大问题 优惠券可以反复套娃 卡出超低价格
叠加使用优惠券可以卡出难以想象的超低价格
希望官方修复

**Comment by coder-bts** [comment]
复现步骤？

**Comment by zdrtyujm** [comment]
开启折抵的情况下，可以同时使用两张不通的优惠券

**Comment by cyril-cheng** [comment]
> 开启折抵的情况下，可以同时使用两张不同的优惠券

你自己设置的问题，优惠券都有指定套餐，你把两个优惠券都指定了同一个套餐，当然可以叠加了。

**Comment by cyril-cheng** [comment]
确实复现了，群里有人反应：
“刚注册 然后他第一单没支付（填了8折优惠券），第二单付了（填了8折优惠券），38.88只付了27.99。”
