### ISSUE TITLE
【功能建议】Stripe 可新增CNY结算以减少设置步骤

### ISSUE THREAD

**Issue by Fierce-Cat** [v2board/v2board#420]
来源：https://stripe.com/docs/payments/alipay

Stripe现已支持使用CNY作为缺省结算货币来结算，系统会自动将CNY订单转换为默认银行账户货币。这可以减少在 /admin#/config/payment 设置Stripe时出错的几率，并简化货币转换流程。希望添加此项功能。

**Comment by hietsusama** [comment]
微信支付不支持CNY 也就说CNY结算只能使用Alipay 货币是可以修改的 仔细看docs文档就能找到
另外需要可以找我买日本的Stripe 信誉度高 可开WX ZFP JCB @chain_a
