### ISSUE TITLE
pm2队列启动时指定文件不存在

### ISSUE THREAD

**Issue by realfull** [v2board/v2board#423]
新版本的pm2管理器
也无法退回到老版本
![IMG_20210425_121059.png](https://user-images.githubusercontent.com/58330328/115980494-c22d0900-a5bf-11eb-9cc5-b3b2a2c30985.png)

![IMG_20210425_121020.png](https://user-images.githubusercontent.com/58330328/115980482-a9bcee80-a5bf-11eb-8147-febaa5a683f4.png)

也尝试使用supervisor
![IMG_20210425_121039.png](https://user-images.githubusercontent.com/58330328/115980515-ed175d00-a5bf-11eb-821a-903d574d338c.png)
启动失败

**Comment by realfull** [comment]
已解决，![IMG_20210425_180917.png](https://user-images.githubusercontent.com/58330328/115989558-9460b800-a5f1-11eb-8df6-177f934f9663.png)
应该这样子写

**Comment by FunAomi** [comment]
> 已解决，![IMG_20210425_180917.png](https://user-images.githubusercontent.com/58330328/115989558-9460b800-a5f1-11eb-8df6-177f934f9663.png)
> 应该这样子写

 你的pm2重启会报错嘛？
