### ISSUE TITLE
重启PM2 Manager报错

### ISSUE THREAD

**Issue by AuroraFrowned** [v2board/v2board#425]
Sorry, something went wrong：
Traceback (most recent call last):
File "class/flask_sockets.py", line 30, in __call__
handler, values = adapter.match()
File "/www/server/panel/pyenv/lib/python3.7/site-packages/werkzeug/routing.py", line 1945, in match
raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "class/panelPlugin.py", line 1981, in a
return eval(execStr)
File "", line 1, in
File "plugin/pm2/pm2_main.py", line 524, in Restart
if result.find('✓') != -1: return public.returnMsg(True, 'Project [' + get.pname + '] has been restarted!')
AttributeError: 'tuple' object has no attribute 'find'

**Comment by FunAomi** [comment]
> Sorry, something went wrong：
> Traceback (most recent call last):
> File "class/flask_sockets.py", line 30, in **call**
> handler, values = adapter.match()
> File "/www/server/panel/pyenv/lib/python3.7/site-packages/werkzeug/routing.py", line 1945, in match
> raise NotFound()
> werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "class/panelPlugin.py", line 1981, in a
> return eval(execStr)
> File "", line 1, in
> File "plugin/pm2/pm2_main.py", line 524, in Restart
> if result.find('✓') != -1: return public.returnMsg(True, 'Project [' + get.pname + '] has been restarted!')
> AttributeError: 'tuple' object has no attribute 'find'

这个问题， 你解决了吗？
