### ISSUE TITLE
使用支付宝当面付 扫码支付后回调失败

### ISSUE THREAD

**Issue by jinwyp** [v2board/v2board#433]
使用支付宝当面付  扫码支付后 回调失败
支付宝文档更新了， 可能是 https://github.com/lokielse/omnipay-alipay 库的问题

https://opendocs.alipay.com/open/194/103296

**Comment by Return-s** [comment]
同样问题解决了吗？

**Comment by Return-s** [comment]
支付完无反应

**Comment by pudding1111** [comment]
虽然不知道原因，我替换掉R3的证书，更换ssl证书后。当面付回调正常了。

**Comment by cyril-cheng** [comment]
我1.5可以正常使用，更新到最新版以后回调不了，用支付宝助手调试发现回调报错http500。

**Comment by dand0285** [comment]
1.5.2同样问题

**Comment by cyril-cheng** [comment]
我终于知道新版当面付不能回调的真正原因了，你们都说错了：
对接的时候需要填2个证书密钥：
支付宝公钥：这里填的是(接口加签之后的支付宝公钥)，问题就在这里，如果填的是证书工具直接生成的app公钥，就会造成能支付，不能回调的问题；
支付宝私钥：这里填的是app私钥，就是用证书工具直接生成的app私钥。

**Comment by the-25th-Nova** [comment]
> 我终于知道新版当面付不能回调的真正原因了，你们都说错了：
> 对接的时候需要填2个证书密钥：
> 支付宝公钥：这里填的是(接口加签之后的支付宝公钥)，问题就在这里，如果填的是证书工具直接生成的app公钥，就会造成能支付，不能回调的问题；
> 支付宝私钥：这里填的是app私钥，就是用证书工具直接生成的app私钥。

在尝试之后还是不行，仍然不能回调

**Comment by the-25th-Nova** [comment]
> 我终于知道新版当面付不能回调的真正原因了，你们都说错了：
> 对接的时候需要填2个证书密钥：
> 支付宝公钥：这里填的是(接口加签之后的支付宝公钥)，问题就在这里，如果填的是证书工具直接生成的app公钥，就会造成能支付，不能回调的问题；
> 支付宝私钥：这里填的是app私钥，就是用证书工具直接生成的app私钥。

尝试之后确实是R3证书的问题，已经解决了。大概是之前填写的也是接口加签之后的支付宝公钥，感谢测试。
