### ISSUE TITLE
更新日本语言翻译问题

### ISSUE THREAD

**Issue by zhuixing05** [v2board/v2board#447]
我已经上传翻译好的日文翻译文本，请采纳！

**Comment by cyril-cheng** [comment]
日本语翻译就是日本人做的，咋可能会有严重错误？

**Comment by zhuixing05** [comment]
![Snipaste_2021-05-29_14-27-45](https://user-images.githubusercontent.com/36839600/120060406-458fbd80-c08a-11eb-8f1f-c25cd70a453c.png)
我认识的这个日本人是干VPN服务的，他说不是干相干行业的人翻译出来确实这样然后他给我修改了。
这是他翻译的，请查阅：[https://github.com/v2board/v2board-user-i18n/pull/21](https://github.com/v2board/v2board-user-i18n/pull/21)

**Comment by sunsysjp** [comment]
zhuixing05さん、こんにちは！
翻訳担当のマナと申します。
誤字訂正ありがとうございます。
訂正頂いた方の本業がVPNであれば、今後そちらのスタイルに合わせます。
(人それぞれの習慣もありますので、どちらか一方に合わせた方が翻訳作業がスムーズに行えます)
ちなみに誤字以外はほぼ習慣の違いであり、重大な翻訳ミスはないと考えております。
また、「請求書一覧」ですが、こちらは当時、開発者様から請求書ではなくほかの言い方にしてほしいとの依頼がありました。
そのため、ファイナンスと翻訳させていただいております。
今後ともよろしくお願いいたします。

**Comment by zhuixing05** [comment]
谢谢您的回复，对于我的不礼貌表示歉意！我想问一下，我的日本朋友想把这套系统以日本语作为默认语言，请问怎么设置？

**Comment by zhuixing05** [comment]
> zhuixing05さん、こんにちは！
> 翻訳担当のマナと申します。
> 誤字訂正ありがとうございます。
> 訂正頂いた方の本業がVPNであれば、今後そちらのスタイルに合わせます。
> (人それぞれの習慣もありますので、どちらか一方に合わせた方が翻訳作業がスムーズに行えます)
> ちなみに誤字以外はほぼ習慣の違いであり、重大な翻訳ミスはないと考えております。
> また、「請求書一覧」ですが、こちらは当時、開発者様から請求書ではなくほかの言い方にしてほしいとの依頼がありました。
> そのため、ファイナンスと翻訳させていただいております。
> 今後ともよろしくお願いいたします。

谢谢您的回复，对于我的不礼貌表示歉意！我想问一下，我的日本朋友想把这套系统以日本语作为默认语言，请问怎么设置？

**Comment by cyril-cheng** [comment]
浏览器默认语言改为日本语即可

**Comment by sunsysjp** [comment]
返信ありがとうございます。
お使いのブラウザの言語をもとに自動的に選択するような仕組みになってます。
お友達が日本語のブラウザをお使いであれば、ウェブのロード完了後にページが日本語表示になります。
ブラウザの言語関わらず、強制的に日本語表示をデフォルトにしたい場合はご自身にて再度コンパイルする必要があります
