### ISSUE TITLE
国际化不够友好，形同虚设！！！

### ISSUE THREAD

**Issue by Teeis** [v2board/v2board#448]
国际化为什么只改变一些菜单的名称，我的网站名字，套餐详情名字难道不应该改变吗？

**Comment by Teeis** [comment]
自定义的文字应该可以自己选择国际化，虽然这样有点麻烦，但是显示效果会好很多。一个网站搞得两种语言不是很方便，并不是所有的翻译chrome都能搞定的，特别是网站名称。小建议，不喜勿嘲。

**Comment by tokumeikoi** [comment]
如果你需要一个非常完善一步到位并且如你愿的面板，建议自己写

**Comment by Teeis** [comment]
> 如果你需要一个非常完善一步到位并且如你愿的面板，建议自己写

大佬说的是！是我吹毛求疵了，还让大佬亲自回复，我关闭问题就是了，今后不再提issue，希望V2board越来越好！

**Comment by phlinhng** [comment]
套餐詳情可以按 html 標籤自定義多語言。
