### ISSUE TITLE
[CSS] 管理页面展示收入信息字体过细

### ISSUE THREAD

**Issue by phlinhng** [v2board/v2board#452]
在管理页面的 UI 中，展示今日收入用的字重是 `.font-w300`，明显过细，建议改为 `.font-w500`

**Comment by betaxab** [comment]
太粗了反而影响美感。

**Comment by phlinhng** [comment]
哈哈哈 其实看久了也就习惯了
Inter 的字重才是正确的
因为以前调用的别的字体没有展示正确的字重
才会感觉使用 Inter 后字体变细
