### ISSUE TITLE
要开源就彻底开源呗

### ISSUE THREAD

**Issue by himanhimao** [v2board/v2board#454]
前端代码藏藏捏捏 小里小气

**Comment by himanhimao** [comment]
看见了 再别的项目里 感谢

**Comment by himanhimao** [comment]
别的项目里也是压缩的  作者你是想干嘛 ·

**Comment by phlinhng** [comment]
前端开源让人抄了拿去卖钱么？接口都开源成这样了，想要什么前端自己写。

**Comment by himanhimao** [comment]
> 前端开源让人抄了拿去卖钱么？接口都开源成这样了，想要什么前端自己写。

重写就重写 我不但要重写你的客户端 服务端我也要重写了 乱七八糟的

**Comment by maker2002** [comment]
> > 前端开源让人抄了拿去卖钱么？接口都开源成这样了，想要什么前端自己写。
> 
> 重写就重写 我不但要重写你的客户端 服务端我也要重写了 乱七八糟的

写好了记得开源啊...
现在最麻烦的问题还是修改个文字都不行。
