### ISSUE TITLE
作者提些问题, 会陆续更新

### ISSUE THREAD

**Issue by himanhimao** [v2board/v2board#456]
因为前端代码不开源，导致我想重写前端，后端，发现如下问题，暂时在此备注把

**Comment by himanhimao** [comment]
1. 作者把表设计的对象关系不清晰， 典型例子就是server_group , 本来是server对象的集合， 结果硬生生的把user对象关系扯了进来。页面也没有相关功能。User表的group_id关系是没有作用的
2. Plan更新后会重置用户流量，这不是给用户送钱么

**Comment by himanhimao** [comment]
3.  同样PLAN表里放个GROUP_ID干什么， 那是服务器组的集合，不是PLAN对象的属性。

**Comment by himanhimao** [comment]
4.订单逻辑的处理代码 逻辑有问题，写的过于复杂，有些字段模糊不清，甚至没有意义

**Comment by himanhimao** [comment]
5.代码没有OOP思想。services好几个类没有实际意义。可以移植到MODEL类直接解决

**Comment by tokumeikoi** [comment]
> 1. 作者把表设计的对象关系不清晰， 典型例子就是server_group , 本来是server对象的集合， 结果硬生生的把user对象关系扯了进来。页面也没有相关功能。User表的group_id关系是没有作用的
> 2. Plan更新后会重置用户流量，这不是给用户送钱么

看到这两个问题我就能明白你应该是一个连面板都没有用过的人，应该不适合提出问题。

**Comment by tokumeikoi** [comment]
虽然觉得提issue的用户听没有礼貌的，但是还是礼貌性做答一下。
