### ISSUE TITLE
[功能需求]增加设备限制和限速设置

### ISSUE THREAD

**Issue by NGKSSR** [v2board/v2board#47]
因为v2board我是最近再用虽然这个程序诞生时间不久需要继续打磨,但是作为一个用户我想说是真的好用,只是功能目前比较少.之前一直在用sspanel但是.希望v2board在后期也会增加独立主页index 最希望后期会加上 增加设备限制和限速设置这样子主要功能已经齐全了

**Comment by tokumeikoi** [comment]
1.v2board不是sspanel
2.v2board的功能就是非常的少，功能多的可以使用vnetpanel或者sspanel
3.你要是了解v2board它本身就是没有主页的，你可以自己做
4.开源程序不是你想，就要加的

**Comment by ssrpanel** [comment]
@tokumeikoi 请原谅我发出野猪般的笑声
