### ISSUE TITLE
审计清空后v2ray进程起不来

### ISSUE THREAD

**Issue by az2554** [v2board/v2board#49]
配置ws+tls+nginx
后端v2ray-poseidon
v2board版本1.1.2

在网页添加了审计然后再删除后，v2ray进程起不来

root@ubuntu001:~# service v2ray status
● v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Tue 2020-02-18 23:01:14 CST; 35s ago
  Process: 2654 ExecStart=/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json (code=exited, status=254)
 Main PID: 2654 (code=exited, status=254)

Feb 18 23:01:14 ubuntu001 systemd[1]: v2ray.service: Main process exited, code=exited, status=254/n/a
Feb 18 23:01:14 ubuntu001 systemd[1]: v2ray.service: Unit entered failed state.
Feb 18 23:01:14 ubuntu001 systemd[1]: v2ray.service: Failed with result 'exit-code'.
Feb 18 23:01:14 ubuntu001 systemd[1]: v2ray.service: Service hold-off time over, scheduling restart.
Feb 18 23:01:14 ubuntu001 systemd[1]: Stopped V2Ray Service.
Feb 18 23:01:14 ubuntu001 systemd[1]: v2ray.service: Start request repeated too quickly.
Feb 18 23:01:14 ubuntu001 systemd[1]: Failed to start V2Ray Service.

发现是数据库里节点的rules项有残留需要手动清除

>  {"domain":[]}

```UPDATE `v2_server` SET `rules` = NULL WHERE `v2_server`.`id` = 1;```

清空后v2ray进程就可以起来了

**Comment by ColetteContreras** [comment]
下个版本就会修复了

**Comment by jinastaka** [comment]
我也是这个问题，怎么进去编辑？

**Comment by jinastaka** [comment]
版主在么

**Comment by az2554** [comment]
> 我也是这个问题，怎么进去编辑？

更新v2board或者在数据库执行（1.1.X版本）：
```UPDATE `v2_server` SET `rules` = NULL WHERE `v2_server`.`id` >= 1;```

1.2.x版本可能会出现点击编辑审计后页面全白或者无法添加过滤器的情况，还是rules的问题：
```UPDATE `v2_server` SET `rules` = '{\"domain\":[],\"protocol\":[]}' WHERE `v2_server`.`id` >= 1;```

**Comment by jinastaka** [comment]
你qq多少




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"tanka"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月9日(星期一) 晚上9:40
收件人:&nbsp;"v2board/v2board"<v2board@noreply.github.com&gt;;
抄送:&nbsp;"鹰"<1842962557@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [v2board/v2board] 审计清空后v2ray进程起不来 (#49)



 
我也是这个问题，怎么进去编辑？
  
更新v2board或者在数据库执行（1.1.X版本）：
 UPDATE `v2_server` SET `rules` = NULL WHERE `v2_server`.`id` &gt;= 1;
 
1.2.x版本可能会出现点击编辑审计后页面全白或者无法添加过滤器的情况，还是rules的问题：
 UPDATE `v2_server` SET `rules` = '{\"domain\":[],\"protocol\":[]}' WHERE `v2_server`.`id` &gt;= 1;

**Comment by jinastaka** [comment]
qq多少




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"tanka"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月9日(星期一) 晚上9:40
收件人:&nbsp;"v2board/v2board"<v2board@noreply.github.com&gt;;
抄送:&nbsp;"鹰"<1842962557@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [v2board/v2board] 审计清空后v2ray进程起不来 (#49)



 
我也是这个问题，怎么进去编辑？
  
更新v2board或者在数据库执行（1.1.X版本）：
 UPDATE `v2_server` SET `rules` = NULL WHERE `v2_server`.`id` &gt;= 1;
 
1.2.x版本可能会出现点击编辑审计后页面全白或者无法添加过滤器的情况，还是rules的问题：
 UPDATE `v2_server` SET `rules` = '{\"domain\":[],\"protocol\":[]}' WHERE `v2_server`.`id` &gt;= 1;

**Comment by jinastaka** [comment]
版主能不能加下qq
