### ISSUE TITLE
怎么对接v2ray后端

### ISSUE THREAD

**Issue by Andyanna** [v2board/v2board#5]
怎么对接v2ray后端

**Comment by chen-ran** [comment]
目前可用的后端只有[@deepwork](https://t.me/deepbwork)的，我最近正在写一个新的后端。

**Comment by Andyanna** [comment]
你好，可以分享一下deepwork的项目地址吗？实在是搜索不到

**Comment by chen-ran** [comment]
> 你好，可以分享一下deepwork的项目地址吗？实在是搜索不到

不开源，联系他进行购买。

**Comment by Andyanna** [comment]
会有免费后端不？

**Comment by cyril-cheng** [comment]
https://github.com/deepbwork/v2board-server

**Comment by cyril-cheng** [comment]
> 目前可用的后端只有[@deepbwork](https://t.me/deepbwork)的，我最近正在写一个新的后端。

期待大佬的新作

**Comment by Pinkpiglet** [comment]
面板已经搭建好，期待大佬出v2ray。

**Comment by chen-ran** [comment]
@cyril-cheng @Pinkpiglet 快期末考试了，写了一半，先咕咕咕，过年前应该可以搞出来。

**Comment by kongkong1988** [comment]
@chen-ran 大佬，是个女子？大佬的后端支持ws+tls吗？最好搭配一键脚本，最好占用最少都资源，还得兼顾稳定都性能，最好售价再便宜些。

**Comment by Pinkpiglet** [comment]
@kongkong1988 当然是个可爱的男孩子啦

**Comment by kongkong1988** [comment]
@chen-ran 支付宝当面付授权回调地址应该填啥呢？我用当面付总是显示系统有点儿忙，过会儿再试试。

**Comment by cyril-cheng** [comment]
> @chen-ran 支付宝当面付授权回调地址应该填啥呢？我用当面付总是显示系统有点儿忙，过会儿再试试。

你有后端？？？

**Comment by thank243** [comment]
> @chen-ran 支付宝当面付授权回调地址应该填啥呢？我用当面付总是显示系统有点儿忙，过会儿再试试。

我也是。请教下你解决了吗？
