### ISSUE TITLE
能新增'码支付'这个支付方式吗

### ISSUE THREAD

**Issue by Program2Dog** [v2board/v2board#50]
https://codepay.fateqq.com/home.htm
这是码支付的官网如果能够支持它的话就太感谢了

**Comment by soryer** [comment]
add 一个支付页面的UI调整建议：“订单详情”下方空白过大，会遮挡“支付方式” ；
add 一个优惠券的使用问题：生成优惠券后用户没有找到在哪里使用- - 另外申请自定义优惠券字符功能；

**Comment by huojiankang** [comment]
https://codepay.fateqq.com/home.htm
这是码支付的官网如果能够支持它的话就van分感谢了

**Comment by mxhi** [comment]
希望能加入第三方收人民币的平台

**Comment by lynnhou** [comment]
> https://codepay.fateqq.com/home.htm
> 这是码支付的官网如果能够支持它的话就太感谢了

希望能上马！

**Comment by 1165262240** [comment]
+10086
