### ISSUE TITLE
关于邀请链接和其他一些小问题

### ISSUE THREAD

**Issue by wttfs** [v2board/v2board#51]
我使用前面板分离的方式部署的面板，由于我加入了主页所以，将前面板的文件放置于/user里，因为支付完成后跳转回主页的原因我将系统配置的站点URL填写为 mydomain.com/user ，但是在在邀请链接中的链接开头为 mydomain.com/#/ ，而不是我填写的站点URL mydomain.com/user/#/  ，导致跳转不正常。
还有1.1.2版本有用户反应称偶尔登录的时候会自动跳转出去，无法登录，邮件白名单有bug，还希望能将验证码的有效时间设置长一点，1分钟的验证码经常失效。
最后感谢大佬的贡献

**Comment by wttfs** [comment]
另外希望能开发用户分组的功能，订阅能设置限制用户组购买。

**Comment by tokumeikoi** [comment]
部署这个方式有很多，你可以单独捡个站点部署主页，完全没必要建个目录

**Comment by wttfs** [comment]
> 部署这个方式有很多，你可以单独捡个站点部署主页，完全没必要建个目录

明白，谢谢
