### ISSUE TITLE
订单管理定时任务无效， 订单一直显示开通中

### ISSUE THREAD

**Issue by amfiyong** [v2board/v2board#53]
/www/server/cron/0d09f73a1277c2f54927013f5714fd7e: line 4: Script: command not found
----------------------------------------------------------------------------
★[2020-02-22 21:02:01] Successful
----------------------------------------------------------------------------
/www/server/cron/0d09f73a1277c2f54927013f5714fd7e: line 4: Script: command not found
----------------------------------------------------------------------------
★[2020-02-22 21:03:01] Successful
----------------------------------------------------------------------------
/www/server/cron/0d09f73a1277c2f54927013f5714fd7e: line 4: Script: command not found
----------------------------------------------------------------------------
★[2020-02-22 21:04:01] Successful
----------------------------------------------------------------------------
/www/server/cron/0d09f73a1277c2f54927013f5714fd7e: line 4: Script: command not found
----------------------------------------------------------------------------
★[2020-02-22 21:05:01] Successful
----------------------------------------------------------------------------
/www/server/cron/0d09f73a1277c2f54927013f5714fd7e: line 4: Script: command not found
----------------------------------------------------------------------------
★[2020-02-22 21:06:01] Successful
----------------------------------------------------------------------------
/www/server/cron/0d09f73a1277c2f54927013f5714fd7e: line 4: Script: command not found
----------------------------------------------------------------------------
★[2020-02-22 21:07:01] Successful
----------------------------------------------------------------------------
/www/server/cron/0d09f73a1277c2f54927013f5714fd7e: line 4: Script: command not found
----------------------------------------------------------------------------
★[2020-02-22 21:08:01] Successful
----------------------------------------------------------------------------
/www/server/cron/0d09f73a1277c2f54927013f5714fd7e: line 4: Script: command not found
----------------------------------------------------------------------------
★[2020-02-22 21:09:01] Successful
----------------------------------------------------------------------------
/www/server/cron/0d09f73a1277c2f54927013f5714fd7e: line 4: Script: command not found
----------------------------------------------------------------------------
★[2020-02-22 21:10:01] Successful
----------------------------------------------------------------------------
/www/server/cron/0d09f73a1277c2f54927013f5714fd7e: line 4: Script: command not found
----------------------------------------------------------------------------
★[2020-02-22 21:11:01] Successful
----------------------------------------------------------------------------
/www/server/cron/0d09f73a1277c2f54927013f5714fd7e: line 4: Script: command not found
----------------------------------------------------------------------------
★[2020-02-22 21:28:02] Successful
----------------------------------------------------------------------------
/www/server/cron/0d09f73a1277c2f54927013f5714fd7e: line 4: Script: command not found
----------------------------------------------------------------------------
★[2020-02-22 21:29:01] Successful
----------------------------------------------------------------------------
/www/server/cron/0d09f73a1277c2f54927013f5714fd7e: line 4: Script: command not found
----------------------------------------------------------------------------
★[2020-02-22 21:30:01] Successful
----------------------------------------------------------------------------
/www/server/cron/0d09f73a1277c2f54927013f5714fd7e: line 4: Script: command not found
----------------------------------------------------------------------------
★[2020-02-22 21:31:01] Successful
----------------------------------------------------------------------------
/www/server/cron/0d09f73a1277c2f54927013f5714fd7e: line 4: Script: command not found
----------------------------------------------------------------------------
★[2020-02-22 21:32:01] Successful
----------------------------------------------------------------------------
/www/server/cron/0d09f73a1277c2f54927013f5714fd7e: line 4: Script: command not found
----------------------------------------------------------------------------
★[2020-02-22 21:33:01] Successful
----------------------------------------------------------------------------
/www/server/cron/0d09f73a1277c2f54927013f5714fd7e: line 4: Script: command not found
----------------------------------------------------------------------------
★[2020-02-22 21:34:01] Successful
----------------------------------------------------------------------------
/www/server/cron/0d09f73a1277c2f54927013f5714fd7e: line 4: Script: command not found
----------------------------------------------------------------------------
★[2020-02-22 21:35:01] Successful
----------------------------------------------------------------------------
/www/server/cron/0d09f73a1277c2f54927013f5714fd7e: line 4: Script: command not found
----------------------------------------------------------------------------
★[2020-02-22 21:36:01] Successful
----------------------------------------------------------------------------
/www/server/cron/0d09f73a1277c2f54927013f5714fd7e: line 4: Script: command not found
----------------------------------------------------------------------------
★[2020-02-22 21:37:01] Successful
----------------------------------------------------------------------------
/www/server/cron/0d09f73a1277c2f54927013f5714fd7e: line 4: Script: command not found
----------------------------------------------------------------------------
★[2020-02-22 21:38:01] Successful
----------------------------------------------------------------------------
/www/server/cron/0d09f73a1277c2f54927013f5714fd7e: line 4: Script: command not found
----------------------------------------------------------------------------
★[2020-02-22 21:39:01] Successful
----------------------------------------------------------------------------
/www/server/cron/0d09f73a1277c2f54927013f5714fd7e: line 4: Script: command not found
----------------------------------------------------------------------------
★[2020-02-22 21:40:01] Successful
----------------------------------------------------------------------------
/www/server/cron/0d09f73a1277c2f54927013f5714fd7e: line 4: Script: command not found
----------------------------------------------------------------------------
★[2020-02-22 21:41:01] Successful
----------------------------------------------------------------------------
/www/server/cron/0d09f73a1277c2f54927013f5714fd7e: line 4: Script: command not found
----------------------------------------------------------------------------
★[2020-02-22 21:42:01] Successful
----------------------------------------------------------------------------
/www/server/cron/0d09f73a1277c2f54927013f5714fd7e: line 4: Script: command not found
----------------------------------------------------------------------------
★[2020-02-22 21:43:01] Successful
----------------------------------------------------------------------------
/www/server/cron/0d09f73a1277c2f54927013f5714fd7e: line 4: Script: command not found
----------------------------------------------------------------------------
★[2020-02-22 21:44:01] Successful
----------------------------------------------------------------------------
/www/server/cron/0d09f73a1277c2f54927013f5714fd7e: line 4: Script: command not found
----------------------------------------------------------------------------
★[2020-02-22 21:45:01] Successful
----------------------------------------------------------------------------
/www/server/cron/0d09f73a1277c2f54927013f5714fd7e: line 4: Script: command not found
----------------------------------------------------------------------------
★[2020-02-22 21:46:01] Successful
----------------------------------------------------------------------------
/www/server/cron/0d09f73a1277c2f54927013f5714fd7e: line 4: Script: command not found
----------------------------------------------------------------------------
★[2020-02-22 21:47:02] Successful
----------------------------------------------------------------------------
/www/server/cron/0d09f73a1277c2f54927013f5714fd7e: line 4: Script: command not found
----------------------------------------------------------------------------
★[2020-02-22 21:48:01] Successful
----------------------------------------------------------------------------
/www/server/cron/0d09f73a1277c2f54927013f5714fd7e: line 4: Script: command not found
----------------------------------------------------------------------------
★[2020-02-22 21:49:01] Successful
----------------------------------------------------------------------------
/www/server/cron/0d09f73a1277c2f54927013f5714fd7e: line 4: Script: command not found
----------------------------------------------------------------------------
★[2020-02-22 21:50:01] Successful
----------------------------------------------------------------------------
/www/server/cron/0d09f73a1277c2f54927013f5714fd7e: line 4: Script: command not found
----------------------------------------------------------------------------
★[2020-02-22 21:51:01] Successful
----------------------------------------------------------------------------
这是脚本运行日志

**Comment by Cahost** [comment]
Cron估计设置错误，请把domain.com 请更改为自己的站点域名且路径必须存在。
