### ISSUE TITLE
[BUG] 限速设置无效

### ISSUE THREAD

**Issue by alterquit** [v2board/v2board#552]
The V2Board version number you are using
当前使用的V2Board版本号
--------
1.7.1 正式版

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
使用官方后端，在设置限速并更新至所有用户后，限速功能不生效。
已尝试重启后端等操作，限速依然不起作用。

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
N/A 无报错

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
N/A 无报错

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------
N/A 无日志提供

**Comment by tokumeikoi** [comment]
限速取决于节点服务端，1.7.1版本正常下发
