### ISSUE TITLE
[BUG] 更新1.7.1节点状态全红

### ISSUE THREAD

**Issue by HKTKCLoud** [v2board/v2board#556]
The V2Board version number you are using
当前使用的V2Board版本号
1.7.1
--------

Briefly describe the problem you are experiencing
简单描述你遇到的问题
从1.6.1更新1.7.1节点状态全红，后台是在线状态
--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
![image](https://user-images.githubusercontent.com/120702631/208027103-019dd7f3-4084-45ea-8c5e-5816c1342ec4.png)
![image](https://user-images.githubusercontent.com/120702631/208027179-c92961be-5431-4135-9266-91fe088baf23.png)

--------

**Comment by tokumeikoi** [comment]
#553
