### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by uby777881** [v2board/v2board#557]
我用的是V1.7.1.我已经更改了计划中的限速并向用户申请了强制更新.当我检查节点速度时。它没有改变。我可以知道需要多长时间才能生效。

**Comment by lmyuii** [comment]
其实做为官方日志已经写的非常清楚了，不得不说你们这些人是真的瞎。
![image](https://user-images.githubusercontent.com/99195444/208064069-71d150d9-fe61-469c-8e4e-72344d08c8ad.png)

**Comment by uby777881** [comment]
如果需要后端支持。那么这个速度限制在 V2board 中有什么用.V2board这个新的限速功能到底有什么用哈哈

**Comment by lmyuii** [comment]
这是api下发参数给后端，属于用户级别限速，而你的后端属于所有用户统一限速最大值，面板下发可以DIY，请搞明白逻辑关系

**Comment by uby777881** [comment]
因此，如果我在后端 (Xrayr) 中将节点速度限制设置为 200Mbps. 同一个节点可以对其他用户做不同的限速吗？

例如
名为 HK-1 的节点,我在后端 (xrayr) 将节点速度限制设置为 200Mbps.
我的网站上有 2 个用户。用户 A 我给了 200Mbps 节点。 UserB 我想给他 50Mbps 速度
所以，如果我创建一个新的订阅管理并将速度限制为 50Mbps。是否真的将UserB中同一节点的速度从200Mbps限制到50Mbps？

**Comment by lmyuii** [comment]
如果你的后端支持新的api特性，那么按照开发的正常逻辑，如果后端存在限速以及面板下发了限速，理应取最小值。其次如果是一个正常的环境， 面板支持下了限速下发特性，后端且可读，那么久不会存在后端的配置的限速行为，而是api下发限速

**Comment by uby777881** [comment]
好的。谢谢你的回答。
