### ISSUE TITLE
Admin page not found

### ISSUE THREAD

**Issue by Raminkash** [v2board/v2board#558]
Hello i have updated my v2board to newest released version

After that i cant reach admin page 
Http://domain/admin occured not found

What can i do

**Comment by tokumeikoi** [comment]
Did you set the backend path in the old panel?

**Comment by Raminkash** [comment]
I think no but I dont remember where can I found it

**Comment by tokumeikoi** [comment]
in config/v2board.php set secure_path, clear config cache command: php artisan config:cache
