### ISSUE TITLE
[BUG]从1.6.1更新到1.7.1节点指示灯出现问题

### ISSUE THREAD

**Issue by xcxcadc** [v2board/v2board#559]
The V2Board version number you are using
当前使用的V2Board版本号
--------
1.7.1

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
今天从1.6.1更新到1.7.1后。后台节点指示灯正常，前台用户页面节点指示灯全部变红，我重装都没有用

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

[
![image](https://user-images.githubusercontent.com/113344244/208086448-4d09c1bb-f673-4cc5-a69d-938516bbb639.png)
](url)

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by tokumeikoi** [comment]
#553

**Comment by xcxcadc** [comment]
清除了后我也重启了队列....

**Comment by tokumeikoi** [comment]
清空浏览器或者尝试更换浏览器看看吧。

**Comment by xcxcadc** [comment]
> 清空浏览器或尝试更换浏览器看吧。

.......还有什么办法吗.....就前台节点指示灯不亮和节点统计异常，其他都正常......

**Comment by tokumeikoi** [comment]
后台的指示灯和前台是一致的
