### ISSUE TITLE
企鹅邮箱发件问题

### ISSUE THREAD

**Issue by hanjianlin** [v2board/v2board#56]
本人用的是企鹅 企业 邮箱 绑定自己的域名 之前发信正常 后面应域名到期 跟换了域名 就无法发信
日志文件
-------------------------------------------
[2020-02-24 02:47:53][pAZ2WFAkwG40CHtB9B23prgtIYbHFETQ] Processing: App\Jobs\SendEmail
[2020-02-24 02:47:55][pAZ2WFAkwG40CHtB9B23prgtIYbHFETQ] Failed:     App\Jobs\SendEmail 
---------------------------------------------
邮箱配置
-------------------------------------------
MAIL_DRIVER=smtp
MAIL_HOST=smtp.exmail.qq.com
MAIL_PORT=465
MAIL_USERNAME=m**k@m***r.pw
MAIL_PASSWORD=*********
MAIL_ENCRYPTION=ssl
MAIL_FROM_ADDRESS=m**k@m***r.pw
MAIL_FROM_NAME=C******
MAILGUN_DOMAIN=
MAILGUN_SECRET=
--------------------------------------------
可以确认的是 发信 账户密码是正确的

**Comment by thank243** [comment]
你怎么不考虑下是不是qq自己做的限制呢?qq邮箱后台日志看看。

**Comment by hanjianlin** [comment]
已经解决了 清空下 缓存 就可以了  新配置 上 一定要先清缓存
