### ISSUE TITLE
Can Use V2BOARD with nginx for reverse proxy to cdn?[Feature request]

### ISSUE THREAD

**Issue by alirezashahrokhi** [v2board/v2board#562]
Please describe in detail the problems or needs you have encountered.
请详细描述你遇到的问题或需求。

hello all
i need hide XrayR node behind Cloudflare and tunnel to XrayR with Server a

v2board can support this config ?
i do reverse proxy with TLS in Both Server But i get WebSocket error 

thanks

**Comment by tokumeikoi** [comment]
Xrayr问题请询问xrayr项目方
