### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jacka1a** [v2board/v2board#563]
The V2Board version number you are using
当前使用的V2Board版本号
--------
1.7.1

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------

版本1.6.0前端节点突然全部掉线，查了后端日志报错如下。
Dec 16 19:50:05 ip-172-31-33-108 au[61886]: time="2022-12-16T19:50:05+08:00" level=warning msg="NodeID: 45 IDIndex 0 - Failed to obtain users info - context deadline exceeded (Client.Timeout or context cancellation while reading body)"
然后我又重新对接依旧是这个报错。
升级1.7.1还是这样。
随后我重启前端服务器恢复了，过了一会儿又变成这样了。

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by Amone0012** [comment]
我也这个问题，对接有问题，后端重启会失败
