### ISSUE TITLE
1.71版本通过执行 php artisan v2board:install  得到的admin入口无效

### ISSUE THREAD

**Issue by Amone0012** [v2board/v2board#564]
The V2Board version number you are using
当前使用的V2Board版本号
--------
1.71

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
由1.61升级至1.71后，https//xxxx.xx/admin被自动替换，执行 php artisan v2board:install 命令后获取的入口打开提示404

或者重置admin入口并找到/编辑设置文件获得可用的安全入口

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
![image](https://user-images.githubusercontent.com/96175998/208092775-2203fc18-2694-49bd-bfa1-fb0053067efa.png)

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
![image](https://user-images.githubusercontent.com/96175998/208093099-9c1842e1-4ef4-493a-b464-48ada0c54022.png)

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by tokumeikoi** [comment]
之前有设置过管理路径还是使用旧的路径

**Comment by Amone0012** [comment]
> 没有设置过路径，请问在哪个文件里设置路径呢

**Comment by tokumeikoi** [comment]
在 config/v2board.php 文件中查找 secure_path 参数，如果是空的，修改它，保存后执行 php artisan config:cache
