### ISSUE TITLE
支付回调接口出现错误

### ISSUE THREAD

**Issue by jinwyp** [v2board/v2board#566]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
1.7.1

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
从1.6 升级到1.7.1 后 

支付宝当面付回调接口出错 返回结果 如下

接口URL /api/v1/guest/payment/notify/AlipayF2F/xxxxxxxxxxxxxf99cb69eb32f58f54b9984ca8d99a&xxxx

返回结果如下

{
    "message": "\u9047\u5230\u4e86\u4e9b\u95ee\u9898\uff0c\u6211\u4eec\u6b63\u5728\u8fdb\u884c\u5904\u7406"
}

通过工具 经过unicode 转义后显示  “遇到了些问题，我们正在进行处理”

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by tokumeikoi** [comment]
请提供脱敏后的日志

**Comment by jinwyp** [comment]
> 请提供脱敏后的日志


[2022-12-16 23:59:55] local.ERROR: Call to a member function toArray() on null {"exception":"[object] (Error(code: 0): Call to a member function toArray() on null at /www/wwwroot/v2board/app/Services/PaymentService.php:21)
[stacktrace]
#0 /www/wwwroot/v2board/app/Http/Controllers/Guest/PaymentController.php(17): App\\Services\\PaymentService->__construct()
#1 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Guest\\PaymentController->notify()
#2 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#3 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#4 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#5 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Route->run()
#6 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#7 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#8 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#9 /www/wwwroot/v2board/app/Http/Middleware/Language.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#10 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\Language->handle()
#11 /www/wwwroot/v2board/app/Http/Middleware/ForceJson.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\ForceJson->handle()
#13 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\\Pipeline\\Pipeline->then()
#15 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack()
#16 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRoute()
#17 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute()
#18 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#19 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#20 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#22 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#23 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#25 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#26 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#28 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#30 /www/wwwroot/v2board/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#32 /www/wwwroot/v2board/app/Http/Middleware/CORS.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\CORS->handle()
#34 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#36 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#37 /www/wwwroot/v2board/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle()
#38 {main}
"}

**Comment by tokumeikoi** [comment]
回调数据由支付宝发送，你必须往接口发送正确的数据才能够回调，否则均会报错

**Comment by jinwyp** [comment]
> 回调数据由支付宝发送，你必须往接口发送正确的数据才能够回调，否则均会报错

现在的问题是 

/app/Http/Controllers/Guest/PaymentController.php

到21这行代码toArray();就报错了， 根本没往下走到 验证到支付宝参数的问题
if ($uuid) $payment = Payment::where('uuid', $uuid)->first()->toArray();

uuid 参数是有的，升级到1.7.1后就报错了

**Comment by tokumeikoi** [comment]
因为你的密钥信息验证支付宝传回的信息不正确，这个接口是标准接口，有问题反馈的会比较多，你这边应该多检查一下是否是账户密钥的问题。

**Comment by jinwyp** [comment]
/app/Http/Controllers/Guest/PaymentController.php

$verify = $paymentService->notify($request->input());

debug log

[2022-12-17 02:25:32] local.DEBUG: array (
  'verify' => false,
)  



/app/Services/PaymentService.php

public function notify($params)
{
if (!$this->config['enable']) abort(500, 'gate is not enable');
return $this->payment->notify($params);
}

这个 return $this->payment->notify($params);  的$this->payment->notify 这个notify 方法是在哪实现的？ 怎么最后返回的 $verify是个false呢？

**Comment by tokumeikoi** [comment]
这个问题不是面板导致的问题，请不用再次开启
