### ISSUE TITLE
[BUG]后台执行 bash update.sh之后 后台页面没有变化（版本还是161）

### ISSUE THREAD

**Issue by LingYunNetWork** [v2board/v2board#567]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
1.6.1

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
我执行了bash update.sh 但是回到后台查看 版本号什么的都没有变 已清除浏览器缓存未使用CDN 队列服务在执行脚本之前就停掉了

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by tokumeikoi** [comment]
浏览器缓存及cdn缓存，是否升级成功请以config/app.php最下方的版本号为准
