### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by qujinyu** [v2board/v2board#570]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------1.6.0

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------无法升级

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
![image](https://user-images.githubusercontent.com/120799911/208248519-1e1aaa87-0262-4241-8105-cd28012a361d.png)

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by qujinyu** [comment]
准确的说应该是更新后没有变化，更新浏览器缓存或者重新打开浏览器，都显示并没有升级成功

**Comment by tokumeikoi** [comment]
是否成功升级请以config/app.php底部的版本号为准

**Comment by qujinyu** [comment]
![image](https://user-images.githubusercontent.com/120799911/208249578-a88053e3-e238-4f7c-8668-2b9392777e5f.png)

**Comment by qujinyu** [comment]
> 是否成功升级请以config/app.php底部的版本号为准

![image](https://user-images.githubusercontent.com/120799911/208249610-0c2edd90-2274-41f6-8991-53c3c60a8c0c.png)
确实是没有升级成功

**Comment by imrelax** [comment]
git config --global --add safe.directory  /www/wwwroot/网站目录   然后再升级

小问题  用这个方法可以解决。我升级的时候也遇到过了。

**Comment by qujinyu** [comment]
> git config --global --add safe.directory /www/wwwroot/网站目录
> 
> 按照你图片上的测试域名的 地址的话 命令就是
> 
> git config --global --add safe.directory /www/wwwroot/best.nicename.club
> 
> 直接执行，然后再到v2board的目录运行 sh update.sh 进行升级即可
> 
> 小问题 用这个方法可以解决。我升级的时候也遇到过了。就是给git 配置下。增加了一个目录

感谢，按照大佬的方法操作已经成功升级了。谢谢大佬

**Comment by qujinyu** [comment]
> git config --global --add safe.directory /www/wwwroot/网站目录
> 
> 点击你图片上的测试域名称的地址的话命令就是
> 
> git config --global --add safe.directory /www/wwwroot/best.nicename.club
> 
> 直接执行，然后再到v2board的目录运行 sh update.sh 进入升级即可
> 
> 小问题用这个方法可以解决。我升级的时候也遇到过。就是给git配置下。增加了一个目录

大佬，更新成功了，然后404了，这怎么处理呀。

**Comment by imrelax** [comment]
赋权的问题。 重新为 v2board 所在的整个目录重新赋权

**Comment by qujinyu** [comment]
> 可能赋权的问题。 重新为 v2board 所在的整个目录重新赋权 https://docs.v2board.com/deploy/aapanel.html
> 
> Q：500错误 A：检查站点根目录权限，递归755，保证目录有可写文件的权限，也有可能是Redis扩展没有安装或者Redis没有按照造成的。你可以通过查看storage/logs下的日志来排查错误或者开启debug模式、站点设置中关闭防跨站。
> 
> 404 和500的错误问题很容易 混淆。
> 
> 可以尝试重启下 nginx 和supervisor

找到原因了，因为随机分配了管理员登录后缀，原来的后缀进不去管理员界面了。
