### ISSUE TITLE
[BUG]谷歌分析还在

### ISSUE THREAD

**Issue by uoox** [v2board/v2board#574]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
dev 分支

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
commit 99311e12a5a64c5bafb880076bfe2b93e6a71855 没有删干净GA
https://github.com/v2board/v2board/blob/dev/public/theme/v2board/dashboard.blade.php
https://github.com/v2board/v2board/blob/dev/resources/views/admin.blade.php

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by tokumeikoi** [comment]
[ed2a3b0](https://github.com/v2board/v2board/commit/ed2a3b034e431d2f39ff188f292861319c8d2b1a) 已移除
