### ISSUE TITLE
[BUG]修改站点名称,但发出去的邮件的发送者名称还用的旧的

### ISSUE THREAD

**Issue by gbcbooks** [v2board/v2board#576]
The V2Board version number you are using
当前使用的V2Board版本号
--------
Version 1.7.1

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
注册新用户时,用户邮件收到的邮件显示的发送者是旧站点名称

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
![image](https://user-images.githubusercontent.com/5257893/208280819-0465e194-43d0-4b20-9029-c384b3a32db7.png)

**Comment by tokumeikoi** [comment]
队列需要重启
