### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ryan999ye** [v2board/v2board#579]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------v1.71

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------请教如何在知识库上生成用户的一键订阅地址

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by ryan999ye** [comment]
小白求助, 请教如何在知识库上生成用户的一键订阅地址! 谢谢!

**Comment by cyril-cheng** [comment]
https://docs.v2board.com/use/knowledge.html

**Comment by ryan999ye** [comment]
@cyril-cheng 我在这里看里没看太明白 可以帮我打出来吗,大佬
