### ISSUE TITLE
[BUG]💡套餐过期7天以上的用户将会被清空套餐及权限组信息 -- 没生效

### ISSUE THREAD

**Issue by cdnf** [v2board/v2board#580]
当前使用的V2Board版本号
--------
1.7.1-dev

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
> 💡套餐过期7天以上的用户将会被清空套餐及权限组信息

看1.6.1更新日志里有这玩意儿，可用户管理列表里过期超7天的没有清理掉套餐和权限，你们正常清理不？
![image](https://user-images.githubusercontent.com/66202093/208295043-c12405ff-4561-438e-84a1-e82813ae8e3c.png)

涉及到定时任务的项都没啥问题：
1. 每日统计图表正常
2. 订单、工单自动关闭功能正常
3. 佣金发放功能正常
4. 队列监控里看各项任务正常运行

运行哪个命令可以看清理功能是否正常？

**Comment by cdnf** [comment]
+-----------------------------------------------------------+-------------+-------------+----------------------------+
| Command                                                   | Interval    | Description | Next Due                   |
+-----------------------------------------------------------+-------------+-------------+----------------------------+
| '/www/server/php/74/bin/php' 'artisan' v2board:statistics | 10 0 * * *  |             | 2022-12-19 00:10:00 +08:00 |
| '/www/server/php/74/bin/php' 'artisan' check:order        | * * * * *   |             | 2022-12-18 19:18:00 +08:00 |
| '/www/server/php/74/bin/php' 'artisan' check:commission   | * * * * *   |             | 2022-12-18 19:18:00 +08:00 |
| '/www/server/php/74/bin/php' 'artisan' check:ticket       | * * * * *   |             | 2022-12-18 19:18:00 +08:00 |
| '/www/server/php/74/bin/php' 'artisan' reset:traffic      | 0 0 * * *   |             | 2022-12-19 00:00:00 +08:00 |
| '/www/server/php/74/bin/php' 'artisan' reset:log          | 0 0 * * *   |             | 2022-12-19 00:00:00 +08:00 |
| '/www/server/php/74/bin/php' 'artisan' send:remindMail    | 30 11 * * * |             | 2022-12-19 11:30:00 +08:00 |
| '/www/server/php/74/bin/php' 'artisan' horizon:snapshot   | */5 * * * * |             | 2022-12-18 19:20:00 +08:00 |
+-----------------------------------------------------------+-------------+-------------+----------------------------+
各项 schedule 也没啥问题

**Comment by tokumeikoi** [comment]
这个特性是已被取消
