### ISSUE TITLE
[BUG]1.6更新到1.7.1出现请求失败错误

### ISSUE THREAD

**Issue by mayostkuzeueg** [v2board/v2board#583]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
版本1.7.1

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
今天从1.6.1更新到1.7.1的时更新失败，导致更新不完全！在更新已经不能更新，后，重装vps，装官网全新的1.71，然后导入我之前数据库，登陆后台是，右上角弹出，请求失败，我们正在处理这样的字样，每次登陆后台都会出现，后，新增落地机vps，在用xrayr对接v2borad面板时，始终对接不上，报错为：
XrayR.service: Scheduled restart job, restart counter is at 54.
Dec 18 22:40:24 us systemd[1]: Stopped XrayR Service.
Dec 18 22:40:24 us systemd[1]: Started XrayR Service.
Dec 18 22:40:24 us XrayR[579276]: XrayR 0.8.8 (A Xray backend that supports many panels)
Dec 18 22:40:24 us XrayR[579276]: 2022/12/18 22:40:24 Start the panel..
Dec 18 22:40:24 us XrayR[579276]: 2022/12/18 22:40:24 Xray Core Version: 1.6.6
Dec 18 22:40:24 us XrayR[579276]: 2022/12/18 22:40:24 [Warning] core: Xray 1.6.6 started
Dec 18 22:40:25 us XrayR[579276]: 2022/12/18 22:40:25 Panel Start fialed: request https://站点.com/api/v1/server/ShadowsocksTidalab/user failed: {
Dec 18 22:40:25 us XrayR[579276]:     "message": "\u9047\u5230\u4e86\u4e9b\u95ee\u9898\uff0c\u6211\u4eec\u6b63\u5728\u8fdb\u884c\u5904\u7406"
Dec 18 22:40:25 us XrayR[579276]: }, %!s(<nil>)
Dec 18 22:40:25 us XrayR[579276]: panic: Panel Start fialed: request https://站点.com/api/v1/server/ShadowsocksTidalab/user failed: {
Dec 18 22:40:25 us XrayR[579276]:     "message": "\u9047\u5230\u4e86\u4e9b\u95ee\u9898\uff0c\u6211\u4eec\u6b63\u5728\u8fdb\u884c\u5904\u7406"
Dec 18 22:40:25 us XrayR[579276]: }, %!s(<nil>)
Dec 18 22:40:25 us XrayR[579276]: goroutine 1 [running]:
Dec 18 22:40:25 us XrayR[579276]: log.Panicf({0x31829b3?, 0x0?}, {0xc000971e80?, 0xc00027c600?, 0xc0004c5b90?})
Dec 18 22:40:25 us XrayR[579276]:         log/log.go:395 +0x67
Dec 18 22:40:25 us XrayR[579276]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc000942540)
Dec 18 22:40:25 us XrayR[579276]:         github.com/XrayR-project/XrayR/panel/panel.go:204 +0x5bc
Dec 18 22:40:25 us XrayR[579276]: main.main()
Dec 18 22:40:25 us XrayR[579276]:         github.com/XrayR-project/XrayR/main/main.go:97 +0x250
Dec 18 22:40:25 us systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 18 22:40:25 us systemd[1]: XrayR.service: Failed with result 'exit-code'.

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
![photo_2022-12-19_05-51-31](https://user-images.githubusercontent.com/118878111/208323615-69650d9e-a99d-4e68-a569-1316d6a75d56.jpg)

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------
[log.txt](https://github.com/v2board/v2board/files/10254831/log.txt)

**Comment by jelly0925** [comment]
遇到和作者一样的问题，只有管理员后台登录才会报这个错误，应该是加载不出来昨日节点流量排行的原因，希望可以修复一下，谢谢

**Comment by tokumeikoi** [comment]
清空 stat_server 表

**Comment by mayostkuzeueg** [comment]
现在新问题！老用户续费，订阅无效

**Comment by mayostkuzeueg** [comment]
> 清空 stat_server 表

是数据库里的这个表清空不会有问题吧？现在新问题！老用户继续付费，订阅无效
