### ISSUE TITLE
支付宝当面付怎么自定义订单名？

### ISSUE THREAD

**Issue by zhoushao2018** [v2board/v2board#585]
支付宝当面付订单名字 跟v2b网站名绑定了
想自定义订单名。。。不想跟网站名绑定，这个咋搞?

![image](https://user-images.githubusercontent.com/63604074/208390285-97a5b3e4-8591-4c24-877e-ce39af303fa4.png)

**Comment by cyril-cheng** [comment]
app/Http/Controllers/User/OrderController.php:         

   'subject' => '办公用品',

**Comment by zhoushao2018** [comment]
> 

大佬能说详细点嘛，里面都是英文，没中文啊

**Comment by cyril-cheng** [comment]
subject后面的字段改成办公用品，你订单支付的名字就会变成：办公用品！
