### ISSUE TITLE
[BUG] 每日收入图表不生成

### ISSUE THREAD

**Issue by marvinli001** [v2board/v2board#586]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
v2board从1.6.1更新1.7.1首页下方每日收入图标没有每日生成了，定时任务无报错正常

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by cyril-cheng** [comment]
更新重启队列以后，第二天才会显示统计信息

**Comment by cyril-cheng** [comment]
更新重启队列以后，第二天才会显示统计信息

**Comment by cyril-cheng** [comment]
看看PM2队列是否在运行？更新版本以后会要求重启队列，重启土狗第二天才会显示统计信息。

**Comment by marvinli001** [comment]
emm，我前天更新的，覆盖更新然后重启了队列，昨晚没有看到图表，使用的是supervisor，队列日志全部正常，然后最后一次生成时间是16号

**Comment by marvinli001** [comment]
![IMG_20221219_175617](https://user-images.githubusercontent.com/44795725/208398594-cdec2023-dc5d-4e00-b032-c6c20aba4704.jpg)

**Comment by marvinli001** [comment]
![image](https://user-images.githubusercontent.com/44795725/208433068-3d407758-674d-4c6d-8d60-73f13d527345.png)

**Comment by marvinli001** [comment]
知道是什么问题了，啊哈哈哈，计划任务没有运行了

**Comment by marvinli001** [comment]
观察了一下依然没有生成，尝试重新安装了v2board1.7.1，定时任务和计划任务全部正常无报错，但是首页的图表依然不生成
