### ISSUE TITLE
automatic update , how to update?[Feature request]

### ISSUE THREAD

**Issue by alirezashahrokhi** [v2board/v2board#587]
Please describe in detail the problems or needs you have encountered.
请详细描述你遇到的问题或需求。

hi to all freinds
i need update my v2board
how i can update safety 1.6.1 to latest version?

**Comment by cyril-cheng** [comment]
1、sh update_dev.sh
2、Upgrade your server nodes for v2board

**Comment by alirezashahrokhi** [comment]
> 1、sh update_dev.sh 2、Upgrade your server nodes for v2board

thanks brother 
Thanks for the reply
Can you tell me exactly where to run this file?
This is the first time I want to immortalize this version and I am completely confused

**Comment by alirezashahrokhi** [comment]
i run update sh in website directory
not any thing changed 
whats wrong ?

**Comment by cyril-cheng** [comment]
i run update sh in website directory
no problem
website directory is authorized to www 755

**Comment by cyril-cheng** [comment]
![image](https://user-images.githubusercontent.com/49748357/208436005-3dc75519-17fa-4b10-805b-fe4b69d3015e.png)

**Comment by alirezashahrokhi** [comment]
thanks dear freind 
i do it and set 755 
but noting changed from 1.6.1 to 1.7.x

**Comment by alirezashahrokhi** [comment]
i do update.sh
![Untitled](https://user-images.githubusercontent.com/39673639/208443672-b581941f-e628-4569-ab2c-270dec25c708.png)
but again i see 1.6.1
![2](https://user-images.githubusercontent.com/39673639/208443754-b484fb51-79de-408a-a359-9aa9956600e3.png)

**Comment by cyril-cheng** [comment]
pm2 queue restart?

**Comment by alirezashahrokhi** [comment]
i delete cdn cache and browser 

how i can restart pm2 queue?

**Comment by nrsxs** [comment]
这里是反馈BUG！

**Comment by alirezashahrokhi** [comment]
i do anything and cant update
i think this is a bug

**Comment by alirezashahrokhi** [comment]
my problem not solved please dont close 
when my problem solve a will close this topic

i install 1.6.1 version with this help : https://v2board.com/deploy/aapanel.html
 now i see security problem in this version and need force major update but when use sh update.sh and change permissiion to 755 not changed any thing in my panel 
config/app.php show me 1.6.1 version
