### ISSUE TITLE
[BUG]更新到1.7.1后，用户续订，所有节点无效（就是不能通网）老用户没事

### ISSUE THREAD

**Issue by mayostkuzeueg** [v2board/v2board#588]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
V2Board版本号1.7.1

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
今天从1.6.1更新到1.7.1的时更新失败，导致更新不完全！在更新已经不能更新，后，重装vps，装官网全新的1.71，然后导入我之前数据库，我后台给某个用户加时间，然后从后台把订阅地址更新使用，所有节点都无法使用，全部报错“基础连接已关闭，发送时发生错误”  已经存在后台的老用户未到期的老用户不受影响，但是老用户速度非常非常慢

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

![QQ截图20221219181808](https://user-images.githubusercontent.com/118878111/208403194-f77d4454-f5c4-4d1e-a246-bffd2279f459.png)

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------
[log.txt](https://github.com/v2board/v2board/files/10258386/log.txt)

**Comment by cyril-cheng** [comment]
更新服务端，1.7.0以后必须更新服务端才能使用
