### ISSUE TITLE
[BUG] Changing the fa-IR.json file

### ISSUE THREAD

**Issue by matador7495** [v2board/v2board#589]
The V2Board version number you are using
1.7.1
--------

Briefly describe the problem you are experiencing
file fa-IR.json
--------

Unfortunately, the translated file was done by Google Translate and the correct words were not used.
I replaced the words with the correct meaning.
Please confirm the pull request.

**Comment by tokumeikoi** [comment]
We will provide full support in multiple languages in the future

**Comment by matador7495** [comment]
Thank you, but why did you close my pull request? I sent it to correct the wrong translations in the fa-IR.json file.

Unfortunately, the person who did the translation in Persian did not use the right words. That's why I sent you the correct file.
