### ISSUE TITLE
Flow Traffic isn't working(Fixed)

### ISSUE THREAD

**Issue by infinitaa** [v2board/v2board#593]
I'm afraid, after the update to the latest version, the flow control isn't working or at lease it doesn't show the real used traffic. It remains 0.
Thanks

**Comment by infinitaa** [comment]
I forgot about the Cron, Thanks

**Comment by miadabdi** [comment]
![image](https://user-images.githubusercontent.com/50056491/213303054-4c6f26f4-ba83-4250-9a60-a81e88c87ffb.png)
![image](https://user-images.githubusercontent.com/50056491/213303099-9a74aeeb-ac56-4730-9f3a-c1205d4bb112.png)
I have set up the cron, but I still have this problem, what can be done?

**Comment by infinitaa** [comment]
Make sure XrayR is connected to the V2board and check the log by option#8 and wait for node connection log. Make sure the Cron and Supervisor are configured with proper V2board folder. And at the end check htop process of the V2board server and check artisan processes that currently are running.

**Comment by miadabdi** [comment]
@infinitaa 
Well, the problem was that I did not specify https in ApiHost of ApiConfig. So changed it to https and it works perfectly.
thanks
