### ISSUE TITLE
Prevent registration of strange users

### ISSUE THREAD

**Issue by alirezashahrokhi** [v2board/v2board#594]
hi to all

How can I keep my panel private and prevent other strangers from registering?
Every time I open the panel, people are re-registered and I don't like it

![Untitled](https://user-images.githubusercontent.com/39673639/208697308-7d8a7e46-177f-4253-8616-a51e9559f511.png)

**Comment by nrsxs** [comment]
开启邮箱验证

**Comment by thank243** [comment]
Open stop register

**Comment by alirezashahrokhi** [comment]
> Open stop register
i try and now i have this bug
https://github.com/v2board/v2board/issues/595
