### ISSUE TITLE
[BUG]Fatal error: Uncaught RuntimeException: A facade root has not been set.

### ISSUE THREAD

**Issue by alirezashahrokhi** [v2board/v2board#595]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
1.6.1 (can't update) because update.sh not working (https://github.com/v2board/v2board/issues/587)

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
i try too Prevent registration of strange users buy close signup in v2board settings but i now get this error

Warning: is_dir(): open_basedir restriction in effect. File(/sys) is not within the allowed path(s): (/www/wwwroot/panel.shiraz.homes/:/tmp/:/proc/:/www/php_session/panel.shiraz.homes/) in /www/wwwroot/panel.shiraz.homes/vendor/linfo/linfo/src/Linfo/OS/Linux.php on line 65

Fatal error: Uncaught RuntimeException: A facade root has not been set. in /www/wwwroot/panel.shiraz.homes/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:258 Stack trace: #0 /www/wwwroot/panel.shiraz.homes/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/RegisterErrorViewPaths.php(18): Illuminate\Support\Facades\Facade::__callStatic() #1 /www/wwwroot/panel.shiraz.homes/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(598): Illuminate\Foundation\Exceptions\RegisterErrorViewPaths->__invoke() #2 /www/wwwroot/panel.shiraz.homes/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(579): Illuminate\Foundation\Exceptions\Handler->registerErrorViewPaths() #3 /www/wwwroot/panel.shiraz.homes/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(490): Illuminate\Foundation\Exceptions\Handler->renderHttpException() #4 /www/wwwroot/panel.shiraz.homes/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(356): Illumina in /www/wwwroot/panel.shiraz.homes/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 258

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by tokumeikoi** [comment]
The version can be checked at the bottom of config/app.php
