### ISSUE TITLE
[BUG]支付宝当面付 扫码支付后回调失败

### ISSUE THREAD

**Issue by zhoushao2018** [v2board/v2board#596]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

大佬咋回事啊？上一个问题还没解决，怎么关了，给个回复呀
![9DBB76BE0A98F5E2922EE3C04EC64156](https://user-images.githubusercontent.com/63604074/208835731-b308a2e4-0558-4b09-b828-a9b828a819f2.png)

![image](https://user-images.githubusercontent.com/63604074/208835692-8fe81bd0-362f-4871-b26d-2b244d5a30e7.png)

**Comment by tokumeikoi** [comment]
这个不是v2board的问题，请自行debug

**Comment by zhoushao2018** [comment]
> 

好的好的，有个回复就明白了，不回复还真不懂，网上搜索了好像是cf的问题，
