### ISSUE TITLE
[BUG]1.7.1限速功能

### ISSUE THREAD

**Issue by MARCCY** [v2board/v2board#599]
订阅设置限速，该订阅下的用户并没起到限速作用
但是单独设置用户的限速数值可以正常起作用

服务端: xrayr

**Comment by MARCCY** [comment]
这边发现订阅设置后 用户正常购买订阅后  账户信息会多一个跟随订阅的限速值。

但是注册赠送订阅，即使设置了限速，新用户注册后账户也不会有限速值。

**Comment by tokumeikoi** [comment]
已解决
