### ISSUE TITLE
关于推广数始终为1与邀请链接问题

### ISSUE THREAD

**Issue by soryer** [v2board/v2board#60]
开展了小范围的测试，放出邀请码一枚；但是邀请人在后台只能看到**一位**被邀请者，事实上已有**10名以上**被邀请且成功注册人员；
另外K大，套餐下单后结算时，减免金额的来源可否显示出来让用户知道自己享受了什么优惠。
谢谢

**Comment by tokumeikoi** [comment]
邀请并注册成功 !== 邀请并付费成功
