### ISSUE TITLE
[BUG] SMTP邮件发送失败

### ISSUE THREAD

**Issue by Weixiang** [v2board/v2board#600]
The V2Board version number you are using
当前使用的V2Board版本号
--------
v1.7.1

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
从v1.6.1更新版本后，邮件测试界面可以正常发送邮件，但在实际场景中，如用户注册、流量通知等均发送失败。
邮件使用Outlook SMTP发送。
配置如下
```
smtp.office365.com
587
tls
```

已尝试过重启队列、清除缓存、校准主机时间，均无效。

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------
mail log 如下

```
stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
```

**Comment by tokumeikoi** [comment]
https://www.deepl.com/zh/translator
