### ISSUE TITLE
请问怎么限制用户的使用设备数量？

### ISSUE THREAD

**Issue by qujinyu** [v2board/v2board#601]
大神们，机场怎么设置用户能同时在线几台设备使用啊？

**Comment by Footergame** [comment]
Xrayr配置文件里面，有个devicelimit参数设置下即可

**Comment by tokumeikoi** [comment]
无法限制设备，通过ip限制设备不精准且没有意义，开源协议均没有告知用户设备唯一ID，所以无法进行限制
