### ISSUE TITLE
[BUG]支付接口 WechatPayNative 无法使用

### ISSUE THREAD

**Issue by xb0or** [v2board/v2board#602]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
v1.7.1 

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
支付接口 WechatPayNative 无法使用 报错：Class 'Omnipay\Omnipay' not found

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
![_20225924095938.png](https://s2.loli.net/2022/12/24/kVwDyRTQIxiLjEJ.png)

**Comment by tokumeikoi** [comment]
微信支付sdk目前暂时不会更新
