### ISSUE TITLE
[BUG] 更新1.7.1之后修改后台设置报错 无法打开网站

### ISSUE THREAD

**Issue by jacksunhack** [v2board/v2board#603]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
V1.7.1

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
在我更新到1.7.1之后不管是动什么设置总是报错

`Warning: is_dir(): open_basedir restriction in effect. File(/sys) is not within the allowed path(s): (/www/wwwroot/mywebsite.com/:/tmp/) in /www/wwwroot/mywebsite.com/vendor/linfo/linfo/src/Linfo/OS/Linux.php on line 65

Fatal error: Uncaught RuntimeException: A facade root has not been set. in /www/wwwroot/mywebsite.com/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:258 Stack trace: #0 /www/wwwroot/mywebsite.com/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/RegisterErrorViewPaths.php(18): Illuminate\Support\Facades\Facade::__callStatic()
/www/wwwroot/mywebsite.com/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(598): Illuminate\Foundation\Exceptions\RegisterErrorViewPaths->__invoke()
/www/wwwroot/mywebsite.com/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(579): Illuminate\Foundation\Exceptions\Handler->registerErrorViewPaths() /www/wwwroot/mywebsite.com/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(490): Illuminate\Foundation\Exceptions\Handler->renderHttpException() /www/wwwroot/mywebsite.com/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(356): Illuminate\Foundation\Exceptions in /www/wwwroot/mywebsite.com/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 258`

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
![image](https://user-images.githubusercontent.com/47632644/209420542-2e4c3481-79e2-4f5c-b4d9-2aea5c9b9b79.png)

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by tokumeikoi** [comment]
1.使用aapanel关闭防跨站
