### ISSUE TITLE
节点状态页面停两分钟-五分钟亮红灯，也就是所有节点都掉线状态！[BUG]

### ISSUE THREAD

**Issue by wangchanggui** [v2board/v2board#605]
当前使用的V2Board版本号
--------1.7.0以上

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------节点状态页面停两分钟-五分钟亮红灯，也就是所有节点都掉线状态！

--------

**Comment by lmyuii** [comment]
是有这么回事，之前倒是没留意，不知道在1.7之前的版本有没有，我印象中1.62也存在这个问题
