### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by dashti75mo** [v2board/v2board#611]
Please describe in detail the problems or needs you have encountered.
请详细描述你遇到的问题或需求。
Hi thanks you for youre amazing tool
I want to tunnel Server1>Server2 then>attach to v2board
can you add any feature or guide me to do this?
Server1(Foreign)>>tunnel>>Server2(In country)>>>Client can acess through in country ip
i know how to tunnel servers
but dont know how to give access them to v2board

**Comment by matador7495** [comment]
In version 1.7.2, parent and child functionality does not work.
Just like any other node in xrayR, create a node and connect it to your ws server in the panel.
