### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by uby777881** [v2board/v2board#612]
The V2Board version V1.7.2
--------

![33](https://user-images.githubusercontent.com/100527761/209794986-9f154ec1-5849-47a7-bd89-07ba65c9e1da.png)
Why am getting this error?

**Comment by nrsxs** [comment]
别动不动就bug！

**Comment by uby777881** [comment]
![photo_2022-12-30_11-10-25](https://user-images.githubusercontent.com/100527761/210038387-123bf94f-168a-480a-99fa-a197f6dd7833.jpg)

升级到 1.7.2 后，总是报这个错
还有“昨日节点流量排行”是空的

**Comment by cyril-cheng** [comment]
贴日志，你发这些有啥用？
