### ISSUE TITLE
[BUG]1.6.1 - 1.7.2 管理页面提示请求失败问题处理过程

### ISSUE THREAD

**Issue by Excalibur-osu** [v2board/v2board#613]
没有二级地址分隔符导致, 如果修改过后台路径并且路径地址类似111/222可以复现
临时处理:
编辑文件 config/v2board.php 修改"frontend_admin_path"值 使用一级地址即可 例如1111
php artisan config:cache 刷新缓存后使用新地址登录后台

**Comment by tokumeikoi** [comment]
按照描述你只需要填写字符串，你非要这么填写有什么办法呢
