### ISSUE TITLE
请问大佬如何添加一键订阅客户端，想自定义修改并添加Choc

### ISSUE THREAD

**Issue by lsy821113773** [v2board/v2board#618]
因为Choc是基于clash原版写的，想删除ios portal中的surge并添加choc，找到了/app/Http/Controllers/Client/Protocols，但是不知道前端中在哪里修改，而且各个OS下的客户端显示又如何修改呢

**Comment by tokumeikoi** [comment]
choc好像停止维护了吧

**Comment by lsy821113773** [comment]
> 

Choc现在testflight里面还在更新

**Comment by tokumeikoi** [comment]
参考其他订阅文件写一个
