### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by Knowledge17** [v2board/v2board#620]
1.如何从机器上卸载V2board？
1. How to uninstall V2board from the machine?

2.许多客户很难找到订阅网址, 您有恢复旧订阅模式的计划吗？下面的截图
2.It's hard for many customers to find the subscription URL. Do you have any plans to bring back the old subscription model? screenshot below.

![photo_2023-01-01_21-00-25](https://user-images.githubusercontent.com/121760084/210176232-bb8224a4-c27d-4070-b60a-dd2c92669da9.jpg)

**Comment by shayanpal** [comment]
Which version is this screenshot for?

**Comment by Knowledge17** [comment]
阅读以上问题
