### ISSUE TITLE
[BUG] 似乎app/Http/Controllers/User/ServerController.php第30行有些问题

### ISSUE THREAD

**Issue by Yuzuki616** [v2board/v2board#621]
https://github.com/v2board/v2board/blob/6b235e592d57ecc25d5a97070da34fc395387bda/app/Http/Controllers/User/ServerController.php#L30
看上去etag是对updated_at做sha运算，也就是说数据库变动之后etag才会变动。但是last_check_at是存进redis里的，所以当last_check_at变动的时候etag不会变动，然后在etag不变动的情况下会发送304。这样会导致last_check_at变动之后浏览器仍然去读取缓存，从而导致节点状态变红而清除缓存后恢复正常的情况。

**Comment by Samiifarhang** [comment]
Hello and thanks
Unfortunately, in the new version, the Persian language has been removed from the knowledge base and documents , and it is not possible to create content in Persian, please help.

**Comment by tokumeikoi** [comment]
已复现

**Comment by tokumeikoi** [comment]
我们又尝试了一下，实际上请求的时候没有携带If-None-Match不会导致缓存。并不会发送304

**Comment by sanfansen** [comment]
我也是升级到了最新版

用户帐号刚登录，节点状态都是绿灯
过几分钟，都变红了

退出重新登录或者清除缓存，就是绿灯。过几分钟全部变红。

在电脑版 chrome，Edge 上都是如此

**Comment by tokumeikoi** [comment]
已在1.7.3中修复
