### ISSUE TITLE
订单一直处于开通中， cron 没有问题，想了解是否有其他原因导致？

### ISSUE THREAD

**Issue by ningtt** [v2board/v2board#622]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
1.7.2

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
你好， 订单状态一直处于“开通中”，尝试查看cron <--- php /www/wwwroot/www.address.com/artisan schedule:run ---> 并无问题。
后台队列监控中可以查看到报错
![image](https://user-images.githubusercontent.com/61641974/210255548-683b8f4d-f24d-4a9c-b90e-7f86930414a8.png)
我想知道 这个报错信息 如何查看？
希望大佬指点

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------
#0 /www/wwwroot/website.address.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(368): PDO->prepare()
#1 /www/wwwroot/website.address.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(705): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#2 /www/wwwroot/website.address.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(672): Illuminate\\Database\\Connection->runQueryCallback()
#3 /www/wwwroot/website.address.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(376): Illuminate\\Database\\Connection->run()
#4 /www/wwwroot/website.address.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2414): Illuminate\\Database\\Connection->select()
#5 /www/wwwroot/website.address.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2402): Illuminate\\Database\\Query\\Builder->runSelect()
#6 /www/wwwroot/website.address.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2936): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#7 /www/wwwroot/website.address.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2403): Illuminate\\Database\\Query\\Builder->onceWithColumns()
#8 /www/wwwroot/website.address.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(625): Illuminate\\Database\\Query\\Builder->get()
#9 /www/wwwroot/website.address.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(609): Illuminate\\Database\\Eloquent\\Builder->getModels()
#10 /www/wwwroot/website.address.com/app/Console/Commands/CheckTicket.php(45): Illuminate\\Database\\Eloquent\\Builder->get()
#11 /www/wwwroot/website.address.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\CheckTicket->handle()
#12 /www/wwwroot/website.address.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#13 /www/wwwroot/website.address.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#14 /www/wwwroot/website.address.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#15 /www/wwwroot/website.address.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#16 /www/wwwroot/website.address.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#17 /www/wwwroot/website.address.com/vendor/symfony/console/Command/Command.php(298): Illuminate\\Console\\Command->execute()
#18 /www/wwwroot/website.address.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#19 /www/wwwroot/website.address.com/vendor/symfony/console/Application.php(1040): Illuminate\\Console\\Command->run()
#20 /www/wwwroot/website.address.com/vendor/symfony/console/Application.php(301): Symfony\\Component\\Console\\Application->doRunCommand()
#21 /www/wwwroot/website.address.com/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#22 /www/wwwroot/website.address.com/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\\Component\\Console\\Application->run()
#23 /www/wwwroot/website.address.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#24 /www/wwwroot/website.address.com/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#25 {main}

**Comment by Samiifarhang** [comment]
Hello and thanks
Unfortunately, in the new version, the Persian language has been removed from the knowledge base and  documents , and it is not possible to create content in Persian, please help.

**Comment by ningtt** [comment]
已经解决问题

**Comment by yiwe888** [comment]
请问你是证明解决的呢
