### ISSUE TITLE
[BUG]Inactivity of Farsi language in the knowledge base section to enter content in the admin panel

### ISSUE THREAD

**Issue by Samiifarhang** [v2board/v2board#624]
![Untitled picture](https://user-images.githubusercontent.com/120055398/210375383-325b0f89-4bbe-4003-bf94-20b875706ca2.png)

Hi my friends
Thanks for your kind support
Unfortunately, in the knowledge section, the possibility of using Persian language to enter content is disabled. And for this reason, panel users who use Persian language do not have access to the content in the knowledge base section.
This problem did not exist in the previous version. And it happened after the update.
please guide me

**Comment by tokumeikoi** [comment]
We are planning to make the English version of the support administration panel available in 2.0.

**Comment by Samiifarhang** [comment]
> We are planning to make the English version of the support administration panel available in 2.0.

The problem is not the English language in the management panel.
While the Persian language is active in the user side panel, the system administrator must also publish educational materials in the knowledge base section.
Currently, Persian language is not available to publish the content in the knowledge base section
Please note: This possibility was previously active in version 1.7 for Persian language
And now, after the update in version 1.7.2, it is disabled and Persian language is not available in the management section of the knowledge base. And as a result, users do not have access to any of the contents of the knowledge base.

**Comment by Samiifarhang** [comment]
> We are planning to make the English version of the support administration panel available in 2.0.
![Untitled picture](https://user-images.githubusercontent.com/120055398/210678656-26651ed6-ed47-4289-be51-0cf696044aaa.png)

Thanks again for your follow up
In the attached image, which is a screenshot of the panel, I marked it with a mark.
  Let me explain more
Farsi language is active without any problem in the user side panel. But the problem is when using the management section of the knowledge base, and the system administrator does not have the option of selecting Persian language to send new content
