### ISSUE TITLE
[Feature request]订阅URL和 主站域名不一致要怎么操作

### ISSUE THREAD

**Issue by zhoushao2018** [v2board/v2board#626]
Please describe in detail the problems or needs you have encountered.
请详细描述你遇到的问题或需求。
订阅URL和 主站域名不一致要怎么操作？，订阅URL可以和主站域名URL跟域不一样吗？
官方文档啥也没说，网上也没有搜索到，所以就来这里问问大佬

**Comment by tokumeikoi** [comment]
没有理解您的问题
