### ISSUE TITLE
Fatal error: require(): Failed opening required '/home/v2board-1.7.2/vendor/autoload.php' (include_path='.:/www/server/php/73/lib/php') in /home/v2board-1.7.2/artisan on line 18

### ISSUE THREAD

**Issue by jldhrj** [v2board/v2board#627]
Warning: require(/home/v2board-1.7.2/vendor/autoload.php): failed to open stream: No such file or directory in /home/v2board-1.7.2/artisan on line 18
PHP Fatal error:  require(): Failed opening required '/home/v2board-1.7.2/vendor/autoload.php' (include_path='.:/www/server/php/73/lib/php') in /home/v2board-1.7.2/artisan on line 18

Fatal error: require(): Failed opening required '/home/v2board-1.7.2/vendor/autoload.php' (include_path='.:/www/server/php/73/lib/php') in /home/v2board-1.7.2/artisan on line 18

**Comment by ohmyskyhigh** [comment]
how did you solve it?

**Comment by jldhrj** [comment]
> how did you solve it?

Don't remember~
