### ISSUE TITLE
[BUG]当重置包价格为0时 用户面板显示错误

### ISSUE THREAD

**Issue by lotusproxy** [v2board/v2board#628]
The V2Board version number you are using
当前使用的V2Board版本号
--------
1.7.2 master

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
当将套餐的流量重置包价格设定为0时
在用户面板当使用流量超过85%时不会显示流量重置按钮
而是一个0（纯文本）
当将价格调至0以上时 按钮出现

**Comment by PAKingdom** [comment]
+1

**Comment by tokumeikoi** [comment]
有没有可能是留空而不是写0

**Comment by now163** [comment]
留空也不行，应该是个bug。不能设置为免费重置流量。
我这里也同样情况。

**Comment by tokumeikoi** [comment]
> 留空也不行，应该是个bug。不能设置为免费重置流量。 我这里也同样情况。

留空为不进行重置流量包的销售，本身就没有免费重置的功能

**Comment by lotusproxy** [comment]
在之前的版本中 将价格定为0依然可以进行重置
但是1.7.2中直接显示0而不是按钮
所以我认为这个应该算是bug

**Comment by now163** [comment]
同意，之前版本是可以设置0的。而且逻辑上也应该允许0元重置。
