### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Roadsidetop** [v2board/v2board#632]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
1.7.2

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
机器人绑定后发消息不回

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

![photo_2023-01-10_20-33-26](https://user-images.githubusercontent.com/104197818/211552803-6305d2f9-7c8e-4746-b76f-c90584fb5d18.jpg)

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
![捕获](https://user-images.githubusercontent.com/104197818/211552567-2aae4524-5b29-4116-bd7c-ace4e1a5e9eb.PNG)

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------
#0 /www/wwwroot/.../vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(153): Redis->connect()
#1 /www/wwwroot/.../vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(84): Illuminate\\Redis\\Connectors\\PhpRedisConnector->establishConnection()
#2 /www/wwwroot/.../vendor/laravel/framework/src/Illuminate/Support/helpers.php(263): Illuminate\\Redis\\Connectors\\PhpRedisConnector->Illuminate\\Redis\\Connectors\\{closure}()
#3 /www/wwwroot/.../vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(121): tap()
#4 /www/wwwroot/.../vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(28): Illuminate\\Redis\\Connectors\\PhpRedisConnector->createClient()
#5 [internal function]: Illuminate\\Redis\\Connectors\\PhpRedisConnector->Illuminate\\Redis\\Connectors\\{closure}()
#6 /www/wwwroot/.../vendor/laravel/framework/src/Illuminate/Redis/Connections/PhpRedisConnection.php(536): call_user_func()
#7 /www/wwwroot/.../vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(220): Illuminate\\Redis\\Connections\\PhpRedisConnection->command()
#8 /www/wwwroot/.../vendor/laravel/framework/src/Illuminate/Redis/Connections/PhpRedisConnection.php(575): Illuminate\\Redis\\Connections\\Connection->__call()
#9 /www/wwwroot/.../vendor/laravel/horizon/src/Repositories/RedisSupervisorRepository.php(152): Illuminate\\Redis\\Connections\\PhpRedisConnection->__call()
#10 /www/wwwroot/.../vendor/laravel/horizon/src/Supervisor.php(216): Laravel\\Horizon\\Repositories\\RedisSupervisorRepository->forget()
#11 /www/wwwroot/.../vendor/laravel/horizon/src/Supervisor.php(320): Laravel\\Horizon\\Supervisor->terminate()
#12 /www/wwwroot/.../vendor/laravel/horizon/src/Supervisor.php(286): Laravel\\Horizon\\Supervisor->ensureParentIsRunning()
#13 /www/wwwroot/.../vendor/laravel/horizon/src/Supervisor.php(260): Laravel\\Horizon\\Supervisor->loop()
#14 /www/wwwroot/.../vendor/laravel/horizon/src/Console/SupervisorCommand.php(100): Laravel\\Horizon\\Supervisor->monitor()
#15 /www/wwwroot/.../vendor/laravel/horizon/src/Console/SupervisorCommand.php(75): Laravel\\Horizon\\Console\\SupervisorCommand->start()
#16 /www/wwwroot/.../vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Horizon\\Console\\SupervisorCommand->handle()
#17 /www/wwwroot/.../vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#18 /www/wwwroot/.../vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#19 /www/wwwroot/.../vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#20 /www/wwwroot/.../vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#21 /www/wwwroot/.../vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#22 /www/wwwroot/.../vendor/symfony/console/Command/Command.php(298): Illuminate\\Console\\Command->execute()
#23 /www/wwwroot/.../vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#24 /www/wwwroot/.../vendor/symfony/console/Application.php(1040): Illuminate\\Console\\Command->run()
#25 /www/wwwroot/.../vendor/symfony/console/Application.php(301): Symfony\\Component\\Console\\Application->doRunCommand()
#26 /www/wwwroot/.../vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#27 /www/wwwroot/.../vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\\Component\\Console\\Application->run()
#28 /www/wwwroot/.../vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#29 /www/wwwroot/.../artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#30 {main}
"}

**Comment by thank243** [comment]
use `/bind` also no respones?
