### ISSUE TITLE
[BUG]1.7.2路由规则超过1000条添加报请求失败未指定动作

### ISSUE THREAD

**Issue by jelly0925** [v2board/v2board#635]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------

1.7.2
Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
路由规则超过1000条添加报请求失败未指定动作，删除2条以后保存就正常了。

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

![路由规则01](https://user-images.githubusercontent.com/3022023/212008971-6bd882b7-4933-40d3-87de-09e961ab6e73.png)

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by tokumeikoi** [comment]
没有复现
