### ISSUE TITLE
[Feature request] “一键导入”增加选项

### ISSUE THREAD

**Issue by idanran** [v2board/v2board#639]
请求增加“导入到 [Clash Verge](https://github.com/zzzgydi/clash-verge)”。

**Comment by tokumeikoi** [comment]
这个不兼容clash:// ？直接用导入到clash就可以了不是吗

**Comment by cyril-cheng** [comment]
> 这个不兼容clash:// ？直接用导入到clash就可以了不是吗

windows页面只有导入到clash for windows的选项
![image](https://user-images.githubusercontent.com/49748357/213384882-9853a4ab-4418-4f53-8a78-d7bf4e47c439.png)

**Comment by idanran** [comment]
> 这个不兼容clash:// ？直接用导入到clash就可以了不是吗

会启动CFW

**Comment by six6pear** [comment]
为啥要加一个一样内核的魔改客户端呢？这个口子一开难道各种client都要加进来吗？

**Comment by idanran** [comment]
> 为啥要加一个一样内核的魔改客户端呢？这个口子一开难道各种client都要加进来吗？本来这玩意的用户量就不多。机场的小白用户们更不可能去选这种东西。

1.很好奇你知道什么是魔改吗…
2.这个软件有3.2k的star

**Comment by tokumeikoi** [comment]
导入到Clash For Windows 会修改成导入到Clash
