### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by alijoon3376** [v2board/v2board#641]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
1.7.2

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
My server was shut down for a short time and after it was turned on, despite the connection of users, all users are displayed offline in the v2board panel, please help

**Comment by tokumeikoi** [comment]
update to dev version
