### ISSUE TITLE
XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT

### ISSUE THREAD

**Issue by uby777881** [v2board/v2board#645]
你好, 我有两台机器。一个用于网站，另一个用于节点.

我的 V2board 版本 1.7.2

我在使用 "PanelType: "NewV2board" 时遇到错误

错误日志如下

当我使用 "PanelType: "V2board"它工作正常。

我该如何解决？

Jan 18 00:20:18 vm505238 XrayR[3792]: XrayR 0.8.8 (A Xray backend that supports many panels)
Jan 18 00:20:18 vm505238 XrayR[3792]: 2023/01/18 00:20:18 Start the panel..
Jan 18 00:20:18 vm505238 XrayR[3792]: 2023/01/18 00:20:18 Xray Core Version: 1.6.6
Jan 18 00:20:18 vm505238 XrayR[3792]: 2023/01/18 00:20:18 [Warning] core: Xray 1.6.6 started
Jan 18 00:20:19 vm505238 XrayR[3792]: 2023/01/18 00:20:19 Panel Start fialed: request https://test.mydomain.com/api/v1/server/UniProxy/config failed: {
Jan 18 00:20:19 vm505238 XrayR[3792]: "message": "\u9047\u5230\u4e86\u4e9b\u95ee\u9898\uff0c\u6211\u4eec\u6b63\u5728\u8fdb\u884c\u5904\u7406"
Jan 18 00:20:19 vm505238 XrayR[3792]: }, %!s()
Jan 18 00:20:19 vm505238 XrayR[3792]: panic: Panel Start fialed: request https://test.mydomain.com/api/v1/server/UniProxy/config failed: {
Jan 18 00:20:19 vm505238 XrayR[3792]: "message": "\u9047\u5230\u4e86\u4e9b\u95ee\u9898\uff0c\u6211\u4eec\u6b63\u5728\u8fdb\u884c\u5904\u7406"
Jan 18 00:20:19 vm505238 XrayR[3792]: }, %!s()
Jan 18 00:20:19 vm505238 XrayR[3792]: goroutine 1 [running]:
Jan 18 00:20:19 vm505238 XrayR[3792]: log.Panicf({0x31829b3?, 0x0?}, {0xc000937e80?, 0xc00027c600?, 0xc0004c5bb0?})
Jan 18 00:20:19 vm505238 XrayR[3792]: log/log.go:395 +0x67
Jan 18 00:20:19 vm505238 XrayR[3792]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc000968100)
Jan 18 00:20:19 vm505238 XrayR[3792]: github.com/XrayR-project/XrayR/panel/panel.go:204 +0x5bc
Jan 18 00:20:19 vm505238 XrayR[3792]: main.main()
Jan 18 00:20:19 vm505238 XrayR[3792]: github.com/XrayR-project/XrayR/main/main.go:97 +0x250
Jan 18 00:20:19 vm505238 systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 18 00:20:19 vm505238 systemd[1]: XrayR.service: Failed with result 'exit-code'.

**Comment by infinitaa** [comment]
Fix the config.yaml of XrayR and make sure XrayR is updated to the latest version. I assume it's 0.8.8

**Comment by uby777881** [comment]
> Fix the config.yaml of XrayR and make sure XrayR is updated to the latest version. I assume it's 0.8.8

Thank you for your reply.
I guess i'm using the latest version 0.8.8 https://github.com/XrayR-project/XrayR/releases

But, When i choose panel type V2board, Xrayr is working and nodes are online. The problem happen when i choose Panel type as NewV2board.

I wonder if i need to do any other setup. As i told before my website and nodes are in different VPS and Different domain. I separated them using redis.

**Comment by uby777881** [comment]
![1](https://user-images.githubusercontent.com/100527761/213909184-8f5e498c-d9f8-40aa-8940-a97cf2f9ff39.png)
![2](https://user-images.githubusercontent.com/100527761/213909185-c5a3d6b7-4e64-48fe-9c50-8fb1aebecc91.png)

**Comment by infinitaa** [comment]
Make sure you can ping API host via your XrayR server and also make sure your V2Board server is responding correctly to your requests.In some cases V2board server cannot process all the requests and CPU goes overloaded.

**Comment by uby777881** [comment]
![2](https://user-images.githubusercontent.com/100527761/213913382-af37dc0d-63e3-4fe8-a7e1-3407dfeaf7ad.png)
![1](https://user-images.githubusercontent.com/100527761/213913383-c4392add-63e9-4013-ae96-1d673973eb4c.png)

I can ping the API host and the V2board server is running normally. Because all the nodes load goes to the slave vps.

Still i don't understand why Xrayr can't read my API host

**Comment by uby777881** [comment]
Any Help

**Comment by uby777881** [comment]
WTH You guys don’t even know what the issue is? Then keep the old API. Why are you planning to remove API if you don’t know how to fix the issue 👎👎
