### ISSUE TITLE
[BUG] 托管配置文件格式不正确: yaml: unmarshal errors: line 17: cannot unmarshal !!map into []map[string]interface {}

### ISSUE THREAD

**Issue by jackom** [v2board/v2board#648]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
1.7.2.1671471846226

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
在Mac电脑的ClashX客户端上更新订阅失败，检查了空格、换行等没问题，我直接用default.clash.yaml文件也是一样的报错问题。

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
<img width="258" alt="image" src="https://user-images.githubusercontent.com/5052960/214061370-5af52cbf-3527-43c8-a102-91964a934228.png">

<img width="604" alt="image" src="https://user-images.githubusercontent.com/5052960/214061657-66964dbc-a07b-448d-b0b6-1be9263de1eb.png">

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------
<img width="1469" alt="image" src="https://user-images.githubusercontent.com/5052960/214062830-73a80aa2-77ea-4fc2-9bd0-289ab5a61852.png">

**Comment by lmyuii** [comment]
你自己的问题，你没有节点你没看见吗

**Comment by jackom** [comment]
> 你自己的问题，你没有节点你没看见吗

我是在proxy-groups里面配置的，之前安装的旧版同样的配置没问题的，新版本有问题。。
