### ISSUE TITLE
[BUG]用户注册时输入空格也可注册成功

### ISSUE THREAD

**Issue by imKinod** [v2board/v2board#650]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
1.7.2

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
用户注册时输入空格也可注册成功，但下次重新登录时不输入空格将无法登录。

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
![image](https://user-images.githubusercontent.com/117040965/214871330-95687f1e-c94c-4a0c-9eee-9b8eb58d8856.png)

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by tokumeikoi** [comment]
1.7.3已修复
