### ISSUE TITLE
V2board Device Limit on Plan

### ISSUE THREAD

**Issue by Github-Aiko** [v2board/v2board#652]
How to use the device limit function in V2board? does it require anything i seem to have a limit set but it doesn't work ( i'm using v2board v1.7.2 and xrayR backend )  and how it works , hope my question will be answered .

**Comment by doandat943** [comment]
the core problem is in xrayr not v2board

**Comment by Github-Aiko** [comment]
> the core problem is in xrayr not v2board

What is its operation?

**Comment by doandat943** [comment]
> 

xrayr not have any function like "device limit", v2board is just panel to control xrayr, etc.. works

**Comment by doandat943** [comment]
maybe soga have that func

**Comment by Github-Aiko** [comment]
I do not like to use soda because it is quite inconvenient in some places. I just want to know how this function is limited to each node or is it limited to all packages .

**Comment by shayanpal** [comment]
what do U mean to restrict online ips
and how its done?

**Comment by Rezamrdd** [comment]
so is there anyother xrays like x-ui to use to device limit?

**Comment by doandat943** [comment]
> so is there anyother xrays like x-ui to use to device limit?

x-ui just panel to control "x-ray" like v2board and it doesn't have device limit function

**Comment by Rezamrdd** [comment]
> > so is there anyother xrays like x-ui to use to device limit?
> 
> x-ui just panel to control "x-ray" like v2board and it doesn't have device limit function

most of the x-ui panels has such things for use limitation
