### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by rlibaba** [v2board/v2board#653]
您好，就是用户购买了一个月付套餐，我v2b后台是设置为“按月重置流量”。但是我发现无论这些用户有没有进行续费，到了订阅到期的当天，流量都会被重置，导致那些未续费的用户在套餐过期当天还可以大量滥用流量

我有想过将套餐单独设置为“不重置流量”，但如果这样的话，那些订阅了季付的也不会自动重置流量了。

如果修改“重置流量”仅对“季付”以上的套餐生效会不会更加合理呢。

**Comment by qwinwin** [comment]
简单粗暴一点的话 按月重置延迟一天就可以 目前0点重置确实不合理
如 2023/02/03 19:00到期的话  02/04再重置流量

**Comment by tokumeikoi** [comment]
你可以创建多个套餐，分别设置季付，月付，这不冲突

**Comment by qwinwin** [comment]
> 你可以创建多个套餐，分别设置季付，月付，这不冲突

大佬 “按月重置流量”情况下，季付的最后一天也会重置流量导致最后一天可以滥用把
