### ISSUE TITLE
[BUG] trojan ipv6 訂閱格式錯誤

### ISSUE THREAD

**Issue by lotusproxy** [v2board/v2board#654]
The V2Board version number you are using
当前使用的V2Board版本号
--------
1.7.2 master

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
raw格式的訂閱信息中，trojan ipv6格式使用不標準，如若遇到ipv6應該是如下格式
```
[::]:11451

現在的情況是
:::11451

缺少了對於ip的括號
```

**Comment by tokumeikoi** [comment]
host信息取决于你在创建节点是填写的

**Comment by lotusproxy** [comment]
是的，發現應該手工將ipv6地址括起來
在vmess因為vmess訂閱是json的格式所以不影響，但是trojan必須要用[xxxx]:4643這樣

所以直接在節點-連接地址手動將其用[]括起來就可以了
