### ISSUE TITLE
[BUG]前台节点指示灯出现异常，求帮助

### ISSUE THREAD

**Issue by xcxcadc** [v2board/v2board#655]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
1.7.2

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
我从1.7.1更新到1.7.2后，后台节点指示灯正常，但是前台节点指示灯全部是红，我也使用了清除缓存的操作：php artisan config:cache
但是还是没反应.....请问还有什么办法吗...还是说我做错什么了，目前就只有前台节点指示灯出现错误，其他功能一切正常，谢谢！

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
前台错误图](https://s2.loli.net/2023/01/29/zTaxKylu6vkwOCX.png)

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
[后台显示正常图](https://s2.loli.net/2023/01/29/8pt4f6nV1Bdv5zC.png)

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by WPF0414** [comment]
遇到同样的问题，请问你解决了吗？
