### ISSUE TITLE
admin page 404 error but client page is ok ?

### ISSUE THREAD

**Issue by sarahtuska** [v2board/v2board#656]
i installed v2board on aapanel .after install . the client address is ok  but with the link during install it gave me , it doesn't open and i have 404 error . that mean my address maybe is wrong . how can i find my admin panel address . is there any way to find it . thx

**Comment by sarahtuska** [comment]
i find it with this php /www/wwwroot/mysite/artisan v2board:install
problem is the secure address is giving me still dosnt work and get 404 page . whats the problem. is it because of nginx.
hpw can i fix it

**Comment by shnaram** [comment]
I have the same problem
