### ISSUE TITLE
[BUG] Clash 自定义配置文件 节点正则匹配 若遇到空会返回一个对象而不是空数组

### ISSUE THREAD

**Issue by taurusxin** [v2board/v2board#658]
The V2Board version number you are using
当前使用的V2Board版本号
--------
1.7.2

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
如标题所示，使用正则匹配节点，如果没有匹配到，则会将 proxies 置为一个对象而不是空数组，导致 Clash 配置文件发生错误

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
![Snipaste_2023-01-31_11-51-09.png](https://s2.loli.net/2023/01/31/zq3QeyEYBTV6SKM.png)

**Comment by tokumeikoi** [comment]
1.7.3已修复

**Comment by tokumeikoi** [comment]
即便是数组也没办法订阅，这个只能尽量保证proxies不能为空数组，我们也不好移除你的proxy-group
