### ISSUE TITLE
[Feature request] 多域名支付后,自动返回系统设置的主站点网址。

### ISSUE THREAD

**Issue by heaid** [v2board/v2board#659]
Please describe in detail the problems or needs you have encountered.
请详细描述你遇到的问题或需求。

例如：多个域名情况下 a.1.com     b.2.com   c.3.com   系统设置的主站地址为a.1.com

- 目前的情况是：

系统设置站点域名为a.1.com后，
用户如果打开的是 b.2.com 或者c.3.com  成功付款后，会自动跳转回 a.1.com ，需要重新再登录。

- 需求：

是否可以在用户访问 b.2.com 或者c.3.com  并成功付款后，返回到当前用户访问的域名b.2.com   或者c.3.com   。

不知道我描述的您是否明白了。

**Comment by lmyuii** [comment]
自己改两处代码就好了

**Comment by tokumeikoi** [comment]
站点地址的目的就是为了让用户永远都能知道网站的最新地址
