### ISSUE TITLE
[BUG] Shadowsocks win客户端订阅获取不到节点

### ISSUE THREAD

**Issue by qwinwin** [v2board/v2board#663]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
1.7.2

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
Shadowsocks win客户端订阅获取不到节点
cipher: chacha20-ietf-poly1305

注释掉 app/Http/Controllers/Client/Protocols/Shadowsocks.php 33行：
`&& in_array($item['cipher'], ['aes-128-gcm', 'aes-256-gcm', 'aes-192-gcm'])`
则可正常获取到节点

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
api返回：
![image.png](https://pic7.58cdn.com.cn/nowater/webim/big/n_v243f2b4450191407593799982ee7416ea.png)

**Comment by tokumeikoi** [comment]
1.7.3修复
