### ISSUE TITLE
Cant Access to admin panel [BUG]

### ISSUE THREAD

**Issue by Bardiafa** [v2board/v2board#669]
Hi i just installed it using aaPanel & i even can login to the account i wrote in cli, but i cant access admin .
I saw some guys changed the url to DomainName.xxx/admin 
but when i do that it saied 404-NotFound
I even checked my sql & my account is_admin == 1.

Please HELP!

**Comment by tokumeikoi** [comment]
In wwwroot path run command: php artisan v2board:install
