### ISSUE TITLE
[Feature request]能否增加邮箱注册符号限制

### ISSUE THREAD

**Issue by despacito008** [v2board/v2board#672]
Please describe in detail the problems or needs you have encountered.
请详细描述你遇到的问题或需求。
网站一直遭受注册侵扰，使用的是一次性邮箱获取订阅
类似如下的邮箱
sunt.ingyun23@gmail.com
parentspinckneyx.qnf658.0@gmail.com
b.harath.k.a.lladi.3.8@gmail.com
ceoyuiop+w@gmail.com
a.the.narev.ingt.o.n@gmail.com

需求
能否增加邮箱注册符号限制

**Comment by betaxab** [comment]
这个功能是有的。你把 "禁止使用Gmail多别名" 功能打开就行了。

**Comment by despacito008** [comment]
> 这个功能是有的。你把 "禁止使用Gmail多别名" 功能打开就行了。

好的 谢谢
