### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by V2link-org** [v2board/v2board#673]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
1.72

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
账户推广永久点了确认，系统一直显示发放中。已经发了一天了还在发放中

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

![image](https://user-images.githubusercontent.com/115438437/218365267-44627c67-258b-41ec-aae9-2037d396edd7.png)

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------
![image](https://user-images.githubusercontent.com/115438437/218366257-c20744f0-6520-4dd6-8c82-b4c1254b0c90.png)

**Comment by betaxab** [comment]
请检查自动任务。不是 v2board 问题。
