### ISSUE TITLE
[BUG]如何取消“强制域名地址直连”的clash规则下发

### ISSUE THREAD

**Issue by besnow** [v2board/v2board#685]
The V2Board version number you are using
当前使用的V2Board版本号
--------
1.7.2

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
想取消“强制域名地址直连”这条clash规则，但发现是程序下发时自动增加的一条规则

**Comment by lajichang0** [comment]
app/Http/Controllers/Client/Protocols/Clash.php
82-85行，注释掉
