### ISSUE TITLE
[BUG]  后台查看流量使用情况！

### ISSUE THREAD

**Issue by imrelax** [v2board/v2board#687]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
1.7.2

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
在后台查看流量使用情况 会员列表。然后流量使用情况排序。

我发现情况是。
统计的是计费周期内当前的已使用的流量总计。
但是。。但是。。 如果用户没有续费。 套餐已经结束了
统计流量数据就永远记录在 那个数值。 不清零？

这样就导致 我看流量使用情况排序的时候。 看到了一大堆 已经停用的账号居然还显示着。不方便筛选！

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by maajiko** [comment]
我也有此类问题,用户后台以及管理后台，无法查看流量使用情况，好像是中转后无法统计

**Comment by imrelax** [comment]
咱俩说 的不是同一个情况。
我说的是这样的 
![](https://user-images.githubusercontent.com/33931868/221335483-682d20f2-f7c3-4a65-a1ec-c58bfdd4407e.jpg)

1、已经到期了。显示正常 这不要紧。
2、早就到期很久了。但是流量的使用情况一直是在最后的那个时间段。导致我排序 会看到类似这样的用户很多。 一大堆 已经到期NN久的会员 依然还在显示流量。虽然他实际可能根本没用！

**Comment by 1kst** [comment]
自己加个筛选不得了，这种需求没意义
