### ISSUE TITLE
[BUG] 设置SS 2022加密方式时，UDP不通

### ISSUE THREAD

**Issue by Rakau** [v2board/v2board#690]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
1.72

Briefly describe the problem you are experiencing
简单描述你遇到的问题
RT，希望增加SS 2022的UOT功能

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
RT

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
RT

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by lmyuii** [comment]
面板不负责客户端行为，不通你在这里反馈个啥
