### ISSUE TITLE
[BUG] 设置SS 2022加密方式时，Clash Meta订阅无法获取对应代理配置

### ISSUE THREAD

**Issue by Rakau** [v2board/v2board#691]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
1.72

Briefly describe the problem you are experiencing
简单描述你遇到的问题
获取订阅时，没有那一组SS 2022的代理配置，使用&flag=clashmeta也没有

**Comment by lmyuii** [comment]
calsh核心不支持

**Comment by cyril-cheng** [comment]
有没有一种可能，应该使用&flag=clash

**Comment by Rakau** [comment]
> 有没有一种可能，应该使用&flag=clash

clash原版不支持SS 2022，用了更加没用

**Comment by Rakau** [comment]
> Also It's
> 
> ```
> Helper::getShadowsocksServerKey
> ```
> 
> Instead of
> 
> ```
> Helper::getServerKey
> ```
> 
> At line 89 and 94 in app/Http/Controllers/Client/Protocols/ClashMeta.php
> 
> (If you're using master branch)

I'm now on 1.7.3 and the problem is still not fixed. I tried your method but when I get the subscription it prompts an error: "We've encountered some problems, please try later"

**Comment by Rakau** [comment]
> On my panel it works

Maybe I need to try again

**Comment by Rakau** [comment]
> On my panel it works

I used other methods and managed to get the subscription, but the normal Clash Core client gets it and reports an error. I then tested with the latest Alpha Core currently available and the l connection times out

**Comment by betaxab** [comment]
@Rakau @lotusproxy 加参数 `&flag=clashmeta` 强制指定使用 ClashMeta 配置，即可解决问题。

**Comment by Rakau** [comment]
> @Rakau @lotusproxy 加参数 `&flag=clashmeta` 强制指定使用 ClashMeta 配置，即可解决问题。

什么版本有效？在1.7.3下使用这个无法获取ss 2022的节点信息

**Comment by betaxab** [comment]
自 SS2022 配置添加之日起有效。请检查你的 ClashMeta.php 配置是否与最新 dev 一致。

**Comment by Rakau** [comment]
> 自 SS2022 配置添加之日起有效。master 与 dev 测试均无问题。请检查你的 ClashMeta.php 配置是否与最新 dev 一致。

已经更新到Dev，问题解决
