### ISSUE TITLE
[BUG]调用微信支付时api返回500

### ISSUE THREAD

**Issue by 3199361233** [v2board/v2board#692]
The V2Board version number you are using
当前使用的V2Board版本号
v1.7.2
--------

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
调用微信支付时api返回500
POST https://xxxxx.com/api/v1/user/order/checkout 500   umi.js?v=1.7.2.1671471846226:1

--------

**Comment by 3199361233** [comment]
已经测试架设过v1.5.5版本，微信支付是正常的，在v1.7.0以上的版本，微信支付都会返回500错误

**Comment by yiwe888** [comment]
我也是微信是错误的。还有我想请问你1.55，的数据库你恢复到1.72上不会报错吗？

**Comment by 3199361233** [comment]
> 我也是微信是错误的。还有我想问你1.55，你恢复到1.72上不会报错吗？

我是重新搭建了一个1.5.5版本的测试面板，然后在测试面板里接入微信支付测试的，是正常的，新版本不行

**Comment by yiwe888** [comment]
对的，目前我也是只能在1.55上使用。还有一个问题，我尝试在新版本上用EPAY是可以用的。但是我在1.72甚至1.60以上的版本上导入1.55的数据库发现登录后台会报错。你这边在新版能用1.55的数据库资料还原吗

**Comment by 3199361233** [comment]
> 对的，目前我也是只能在1.55上使用。还有一个问题，我尝试在新版本上用EPAY是可以用的。但是我在1.72甚至1.60以上的版本上导入1.55的数据库发现登录后台会报错。你这边在新版能用1.55的数据库资料还原吗

1.5.5的数据库结构跟新版的数据库结构不一致，我目前的解决办法是全部用易支付，易支付再接入微信官方

**Comment by yiwe888** [comment]
> > 对的，目前我也是只能在1.55上使用。还有一个问题，我尝试在新版本上用EPAY是可以用的。但是我在1.72甚至1.60以上的版本上导入1.55的数据库发现登录后台会报错。你这边在新版能用1.55的数据库资料还原吗
> 
> 1.5.5的数据库结构跟新版的数据库结构不一致，我目前的解决办法是全部用易支付，易支付再接入微信官方

明白，但是你这样新版本不能导入数据的话就是没有了所有注册用户的信息啊？有没有办法能够到处用户的信息到1.72版本上呢

**Comment by 3199361233** [comment]
> > > 对的，目前我也是只能在1.55上使用。还有一个问题，我尝试在新版本上用EPAY是可以用的。但是我在1.72甚至1.60以上的版本上导入1.55的数据库发现登录后台会报错。你这边在新版能用1.55的数据库资料还原吗
> > 
> > 
> > 1.5.5的数据库结构跟新版的数据库结构不一致，我目前的解决办法是全部用易支付，易支付再接入微信官方
> 
> 明白，但是你这样新版本不能导入数据的话就是没有了所有注册用户的信息啊？有没有办法能够到处用户的信息到1.72版本上呢

先从1.5.5版本升级到最新版呀，升级的时候会把数据库结构调整到适应最新版的，就是你直接把面板升级就行了。然后自己搭建一个易支付接入微信官方的支付，然后新版v2b再接入易支付

**Comment by yiwe888** [comment]
我目前的1.55版本也是新装的，不是通过git部署的。我用网站上的方法：备份数据库及 config/v2board.php 文件后全新安装v2board恢复文件即可完成重装。。弄好之后都是错误不能启动的。你新装好的1.55还原好数据库后，你是通过什么方法升级到1.72不报错的呢？

**Comment by yiwe888** [comment]
> > > > 对的，目前我也是只能在1.55上使用。还有一个问题，我尝试在新版本上用EPAY是可以用的。但是我在1.72甚至1.60以上的版本上导入1.55的数据库发现登录后台会报错。你这边在新版能用1.55的数据库资料还原吗
> > > 
> > > 
> > > 1.5.5的数据库结构跟新版的数据库结构不一致，我目前的解决办法是全部用易支付，易支付再接入微信官方
> > 
> > 
> > 明白，但是你这样新版本不能导入数据的话就是没有了所有注册用户的信息啊？有没有办法能够到处用户的信息到1.72版本上呢
> 
> 先从1.5.5版本升级到最新版呀，升级的时候会把数据库结构调整到适应最新版的，就是你直接把面板升级就行了。然后自己搭建一个易支付接入微信官方的支付，然后新版v2b再接入易支付

还有你说的把数据库结构调整？具体如何调整？

**Comment by 3199361233** [comment]
> 我目前的1.55版本也是新装的，不是通过git部署的。我用网站上的方法：备份数据库及 config/v2board.php 文件后全新安装v2board恢复文件即可完成重装。。弄好之后都是错误不能启动的。你新装好的1.55还原好数据库后，你是通过什么方法升级到1.72不报错的呢？

1.在你现在的1.5.5版本的面板机器上，直接把1.7.2的文件下载下来覆盖到1.5.5版本的文件
2.然后使用官方教程里的非git部署更新 "php artisan v2board:update" 命令来更新面板
3.更新完之后的新版本就是1.7.2了

**Comment by yiwe888** [comment]
好的，我试下。感谢

苏孜 ***@***.***> 于 2023年2月28日周二 下午10:55写道：

**Comment by yiwe888** [comment]
> > 我目前的1.55版本也是新装的，不是通过git部署的。我用网站上的方法：备份数据库及 config/v2board.php 文件后全新安装v2board恢复文件即可完成重装。。弄好之后都是错误不能启动的。你新装好的1.55还原好数据库后，你是通过什么方法升级到1.72不报错的呢？
> 
> 1.在你现在的1.5.5版本的面板机器上，直接把1.7.2的文件下载下来覆盖到1.5.5版本的文件 2.然后使用官方教程里的非git部署更新 "php artisan v2board:update" 命令来更新面板 3.更新完之后的新版本就是1.7.2了

![image](https://user-images.githubusercontent.com/89459511/221929503-76d58677-7f91-415f-966e-2afb4f7472f9.png)
![image](https://user-images.githubusercontent.com/89459511/221929600-188f68cc-c056-49b1-8239-ccbf3bbcf8dd.png)
我也是装好的1.55，然后再github下载1.72然后再aapanel上解压复制所有文件覆盖，运行上面命令，但是还是错误。

**Comment by yiwe888** [comment]
> > 我目前的1.55版本也是新装的，不是通过git部署的。我用网站上的方法：备份数据库及 config/v2board.php 文件后全新安装v2board恢复文件即可完成重装。。弄好之后都是错误不能启动的。你新装好的1.55还原好数据库后，你是通过什么方法升级到1.72不报错的呢？
> 
> 1.在你现在的1.5.5版本的面板机器上，直接把1.7.2的文件下载下来覆盖到1.5.5版本的文件 2.然后使用官方教程里的非git部署更新 "php artisan v2board:update" 命令来更新面板 3.更新完之后的新版本就是1.7.2了

我新装好的1.55测试可以正常，在没有恢复数据库的情况下然后直接用下载的1.72解压覆盖，然后"php artisan v2board:update" ，依旧出错，报错500.请问你是怎么从1.55升级到1.72的呢？如果在我的VPS上直接新装1.72是可以正常的

**Comment by tokumeikoi** [comment]
微信支付在最新的版本中目前是无法使用的，暂时没有人提供新的sdk

**Comment by sTon081** [comment]
> > > > 对的，目前我也是只能在1.55上使用。还有一个问题，我尝试在新版本上用EPAY是可以用的。但是我在1.72甚至1.60以上的版本上导入1.55的数据库发现登录后台会报错。你这边在新版能用1.55的数据库资料还原吗
> > > 
> > > 
> > > 1.5.5的数据库结构跟新版的数据库结构不一致，我目前的解决办法是全部用易支付，易支付再接入微信官方
> > 
> > 
> > 明白，但是你这样新版本不能导入数据的话就是没有了所有注册用户的信息啊？有没有办法能够到处用户的信息到1.72版本上呢
> 
> 先从1.5.5版本升级到最新版呀，升级的时候会把数据库结构调整到适应最新版的，就是你直接把面板升级就行了。然后自己搭建一个易支付接入微信官方的支付，然后新版v2b再接入易支付

你好，我想请问一下，我对接易支付的时候出错：提示说在站点配置里配置站点，怎么解决呢。日志：payment/save 500

**Comment by purelolly** [comment]
> 微信支付在最新的版本中目前是无法使用的，暂时没有人提供新的sdk

用官方不就好了

**Comment by mm350** [comment]
你们都是用的V1版本吗？我怎么只能找到v2或V3的key
