### ISSUE TITLE
Panel counts just near 40% of the traffic used by users[BUG]

### ISSUE THREAD

**Issue by isaghm** [v2board/v2board#693]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
1.6.0

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
I have 60k active users, V2Board panel counts just near 40% of the traffic used by users. daily traffic ~23TB vs the actual usage of ~60TB from the network provider.

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
I don't know where is the error

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
I don't know where is the error

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------
I don't know which log i have to monitor!

**Comment by tokumeikoi** [comment]
Traffic data is reported by nodes, not panel issues
