### ISSUE TITLE
[Feature request] 如何配置双栈的机场及节点

### ISSUE THREAD

**Issue by test0103** [v2board/v2board#694]
为了提供更多的接入，想知道如何接入双栈(IPv4&IPv6)的流量节点，网上及官方文档都没讲这个。另外想知道如何通过docker在一台服务器上通过caddy来部署多个v2board来承载业务？

**Comment by Oldming1** [comment]
父子节点，设置多个入站就行，你本地后端不就是认得端口

**Comment by cyril-cheng** [comment]
你的中转机是双栈就行了
