### ISSUE TITLE
資料庫連線失敗

### ISSUE THREAD

**Issue by PoorerImmune** [v2board/v2board#70]
我用的是 Debian 10 系統。依照文檔的指導，在執行到 php artisan v2board:install 這一步時，我正確輸入了資料庫的位址、用戶名和密碼，但是在最新的版本（1.1.2）上會出現連線失敗的問題，也沒有錯誤細節提示，舊版本的則很順利。

**Comment by skywalk128** [comment]
您好，想请教一下数据库的地址一般是什么格式，我写localhost和ip都链接失败

**Comment by PoorerImmune** [comment]
> 您好，想请教一下数据库的地址一般是什么格式，我写localhost和ip都链接失败

如果 MySQL/MariaDB 資料庫在本機，「http://localhost」和「http://127.0.0.1」均可。二者的分別在於前者在 Linux 平台上是以 Unix Socket 的方式連線；後者則以 TCP/IP 來連線。你可以在「User」資料表中看到相關欄位。
