### ISSUE TITLE
[Feature request]  Request to add routing management whitelist function

### ISSUE THREAD

**Issue by lineelu** [v2board/v2board#700]
Good evening, V2Board staff, I am your paying user, because of the particularity of my business, I want to add the route whitelist function, the specific function is as follows: For example, add a whitelist domain name to route management: google.com, at this time only the google.com domain name You can pass through the proxy, other domain names will not be able to pass through the proxy, and you can only go through the local direct connection.

**Comment by lineelu** [comment]
Sincerely thank you V2Board team for allowing me to work full time.

**Comment by tokumeikoi** [comment]
Support depends on the node server backend program
