### ISSUE TITLE
[BUG]  订阅管理 一次性套餐，最大容纳用户量无法修改

### ISSUE THREAD

**Issue by Hiccup6** [v2board/v2board#702]
The V2Board version number you are using
当前使用的V2Board版本号
--------
1.7.2

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
订阅管理，最大容纳用户量。修改不生效。
修改完后重新编辑订阅，发现该项重新置空

**Comment by tokumeikoi** [comment]
无法复现
