### ISSUE TITLE
[BUG] 安卓clash profile does not contain proxies

### ISSUE THREAD

**Issue by jw-star** [v2board/v2board#704]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

1.73
--------

订阅不兼容 安卓clash  profile does not contain proxies or proxy-providers
--------

**Comment by tokumeikoi** [comment]
规则组不要存在空节点就不会有问题
