### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by yangliu123** [v2board/v2board#710]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
1.7.2

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
添加节点时，添加权限组出现错误

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
![图片](https://user-images.githubusercontent.com/10783503/223348024-24ce8a23-d166-4527-a176-f08c89dbc2e0.png)

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
![图片](https://user-images.githubusercontent.com/10783503/223347859-82221e41-96b5-4b91-a633-dc1cd005e2c6.png)

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by tokumeikoi** [comment]
无法复现
