### ISSUE TITLE
[BUG]1.7.3为什么无法下载呢

### ISSUE THREAD

**Issue by StarNGK** [v2board/v2board#716]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by keleyun** [comment]
![Q %RNUCNQV(1@84E9RI K B](https://user-images.githubusercontent.com/105415857/223712668-4eb459a8-523c-44e0-a537-ec63b0985565.png)

**Comment by keleyun** [comment]
同样遇到这个问题，版本号1.7.2，查看教程，就提示请求失败，之前不这样

**Comment by Pastechn** [comment]
提供一下log吧 要不然解决起来没有头绪

**Comment by StarNGK** [comment]
看到官方tg频道发布了 1.7.3更新信息 可是 打开下载地址404 是关闭了该版本的下载么
