### ISSUE TITLE
[BUG]1.7.2版本，无法打开教程内容。

### ISSUE THREAD

**Issue by keleyun** [v2board/v2board#717]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
1.7.2

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
打开使用文档，查阅教程，提示请求失败 遇到了些问题，我们正在进行处理

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

![Q %RNUCNQV(1@84E9RI K B](https://user-images.githubusercontent.com/105415857/223713168-d671e9c7-3abf-43fe-827b-3d0841842cd3.png)

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by tokumeikoi** [comment]
无法理解问题
