### ISSUE TITLE
v2board佣金确认后  怎么不自动发放

### ISSUE THREAD

**Issue by qiansui88** [v2board/v2board#725]
[v2board佣金确认后  怎么不自动发放，佣金3天确认已经开启了
![HJ_NL_T0LQRI)RQ2TUL8G)H](https://user-images.githubusercontent.com/127650574/224529446-97715243-d378-4271-b9e0-9a0f07f9ff84.png)
![D)DFTBKMEK7EH$O$(HBXB_X](https://user-images.githubusercontent.com/127650574/224529448-ba0ea1c4-3b72-436c-af5e-7409d3cee9f6.png)

**Comment by qiansui88** [comment]
1.72-1.73

**Comment by V2link-org** [comment]
去查看你的定时任务有没有在工作

**Comment by qiansui88** [comment]
![A54(~P5)TQA5E3MX_B3Y~P](https://user-images.githubusercontent.com/127650574/224640620-142b2e94-36c4-464f-b617-cd97d9db1bc5.png)

**Comment by qiansui88** [comment]
定时任务 一直没问题

**Comment by qiansui88** [comment]
![HLQZI 8J3D_AM XV5X` G)Q](https://user-images.githubusercontent.com/127650574/224640829-7c6d67d9-efde-434b-a05d-38273a2d500a.png)
这个报错 一直找不到原因

**Comment by qiansui88** [comment]
> 去查看你的定时任务有没有在工作

你看下是哪里有问题

**Comment by SnakeMa** [comment]
我的也是这个问题，手动确认后，一直是【发放中】这个状态，定时任务也没有报错。用的版本是1.7.2

**Comment by SnakeMa** [comment]
自行在宝塔的定时任务日志里发现，是运行了多个php版本导致的，我是7.4和8.2版本都在运行，网站是用的8.2，报错提示是识别用的7.4版本的php，卸载7.4版本就好了。
