### ISSUE TITLE
这是关于一键导入Loon订阅的URL Scheme以及流量信息接口的说明

### ISSUE THREAD

**Issue by ArriettyQAQ** [v2board/v2board#729]
希望可以增加对Loon的支持，这是Loon的商店地址 https://apps.apple.com/app/loon/id1373567447

**关于一键导入订阅**
一键导入Loon订阅的URL Scheme
https://www.nsloon.com/openloon/import?nodelist=encode(url)

例如这样的可以被一键导入订阅：
https://www.nsloon.com/openloon/import?nodelist=https://www.xxx.com/api/v1/client/subscribe?token=adfc2fb7bgd312654613204daef6780c

**关于流量**
Loon会读取订阅响应header中的Subscription-Userinfo信息，其中上行流量、下行流量、总用量、到期时间的输出格式如下：

Subscription-Userinfo:upload=1111;download=111;total=123456;expire=1614527045

参考文档 https://loon0x00.github.io/LoonManual/#/cn/node

更多URL Scheme可以在这里找到：配置 - 右上角更多 - URL Scheme & 统一链接

**Comment by betaxab** [comment]
已添加支持。

**Comment by MoeCinnamo** [comment]
> 已添加支持。

Vmess加密方式好像不對，最好是auto或者chacha20以減少不必要的識別
