### ISSUE TITLE
[BUG]邮件连接stmp服务器超时，无法发送邮件

### ISSUE THREAD

**Issue by sttr5509** [v2board/v2board#733]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
1.7 3

Briefly describe the problem you are experiencing
简单描述你遇到的问题
无法发送邮件！总是提示连接超时！php函数已解禁，对列也是启动的。
Connection could not be established with host smtp.office365.com :stream_socket_client(): Unable to connect to tcp://smtp.office365.com:587 (Connection timed out)

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
![mmexport1679155257393.png](https://user-images.githubusercontent.com/111668462/226117093-80aabc16-b520-4d30-ab1d-18f1e6db7f96.png)

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by betaxab** [comment]
服务器问题，和V2board无关。

**Comment by CN-Root** [comment]
你的服务器587端口没开，大部分厂商都是限制587端口的

**Comment by sttr5509** [comment]
> 你的服务器587端口没开，大部分厂商都是限制587端口的

打开了，还是无法连接

**Comment by sttr5509** [comment]
> 服务器问题，和V2board无关。

换了服务器确实解决了，感谢！
