### ISSUE TITLE
配置支付接口后，订阅下单后，一到支付那块，金额就变成0元了

### ISSUE THREAD

**Issue by imshunzi** [v2board/v2board#734]
配置支付接口后，订阅下单后，一到支付那块，金额就变成0元了，由于金额为0，付款后直接能用，请问下怎么设置。版本是最新的1.7.3版本

**Comment by betaxab** [comment]
你这是什么付款接口

**Comment by SsCat1069** [comment]
什么接口都没用，只要到付款那就变成0元了，购物车那还有金额，支付那就变成0了，什么接口都不没调用

**Comment by imshunzi** [comment]
> 你这是什么付款接口
什么付款接口都没设置，本来想用余额来付款，但是发现 ，订阅后下单那还有金额，下单后到付款那就变成0元了。

**Comment by CN-Root** [comment]
有余额的话默认是余额优先支付

**Comment by imshunzi** [comment]
问题是没有余额啊~
