### ISSUE TITLE
[BUG] Crisp.chat突然无法在ios系统上的任何浏览器使用，点击对话框会出现闪退现象！

### ISSUE THREAD

**Issue by Sucre888** [v2board/v2board#736]
1.7.2/ 1.7.3同样发现这个问题，iphone的所有浏览器都是这样，安卓和电脑就没有这个问题。

问了crisp的客服回答是这样的：As per checking, that is a z-index problem. To fix it, please see the doc here: https://docs.crisp.chat/guides/chatbox-sdks/web-sdk/dollar-crisp/#change-container-index   

但是不知道该如何操作，请大家指教一下。谢谢！

**Comment by Sucre888** [comment]
> 加上这句代码
> 
> $crisp.push(["config", "container:index", [1]]);

请教一下具体加在哪个位置呢

**Comment by yes567** [comment]
微软浏览器也是乱码
