### ISSUE TITLE
[BUG]路由管理添加之后使用无效

### ISSUE THREAD

**Issue by CN-Root** [v2board/v2board#753]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
2023/03/24
安装的最新版

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
在路由管理中屏蔽了
.po***b.com(这里就不透露这个域名了,应该能看懂吧)
并且已经在节点路由组中添加了，但是仍然能够访问这个网站

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
https://img.alicdn.com/imgextra/i3/2/O1CN01vQknXT1EA1bMQcier_!!2-rate.png

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
https://img.alicdn.com/imgextra/i3/2/O1CN01vQknXT1EA1bMQcier_!!2-rate.png

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by tokumeikoi** [comment]
注意：XrayR等非V2Board问题请前往项目方提问
