### ISSUE TITLE
您好，我使用宝塔面板安装，最后一步不知道怎么执行呀。

### ISSUE THREAD

**Issue by 997862** [v2board/v2board#755]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
在查看安装文档第8条的时候，在宝塔面板找了半天
“在 Run Dir 选择 站点目录 在 Start Command 填写 php artisan horizon 在 Processes 填写 1”
我也没找到Command命令行工具以及设置，但是我通过ssh执行了php artisan horizon，可以正常运行，但是结束远程连接，就会断掉。我使用”php artisan horizon &“来执行，持续一段时间会假死掉。
麻烦您了

还有，我想购买V2Ray服务端、Shadowsocks服务端、Windows客户端，不知道是不是有优惠呀，或者打包价格？
我TG：+18322096789，Q：997862麻烦您，我发过TG消息给您，并未得到回复。

**Comment by MoeCinnamo** [comment]
在宝塔面板软件商店处，安装宝塔进程管理器或者守护进程管理器，点击Setting，然后里面就可以设置
