### ISSUE TITLE
后端节点对接前端时报错，"message": "server is not exist"，请问问题出在了哪里呢，完整报错代码如下

### ISSUE THREAD

**Issue by junjiakeji** [v2board/v2board#759]
后端节点对接前端时报错
 panic: Panel Start fialed: request https://域名/api/v1/server/UniProxy/config failed: {
4月 02 07:56:21 vultr.guest XrayR[4680]: "message": "server is not exist"
换服务器重新弄了一次，突然就报这种错，重新搭建对接了几次，都是报这种错，请问问题出在了哪里呢？

**Comment by a0x5b22bbb** [comment]
node_id 跟 节点上的ID 没对上.

**Comment by a0x5b22bbb** [comment]
举个例子.  你在v2board上创建了节点  会自动生成node_id, 比如是4 . 
那你 XrayR 的配置里 也要把node_id改成4, 并且重启   docker-compose restart (在XrayR目录下)
然后你再看日志 他就正常.
我也出现这个问题是因为 我在v2board上增删了节点(做测试) 导致节点无法匹配. 
你看看是不是也是这个原因
