### ISSUE TITLE
[Feature request]向Shadowrocket下发Shadowsocks 2022 udp over tcp

### ISSUE THREAD

**Issue by uoox** [v2board/v2board#763]
Please describe in detail the problems or needs you have encountered.
请详细描述你遇到的问题或需求。

Shadowsocks 2022 已经支持uot，希望能够下发uot

**Comment by trueboost** [comment]
这个项目看起来是废了

**Comment by trueboost** [comment]
具体需要修改哪几个参数 有模板吗？

LotusProxy ***@***.***> 于2023年4月8日周六 20:57写道：
