### ISSUE TITLE
[BUG]系统中配置了Telegram Token，Webhook也设置成功，但机器人不回复消息。

### ISSUE THREAD

**Issue by anbzhuu** [v2board/v2board#765]
The V2Board version number you are using
当前使用的V2Board版本号
--------
v1.7.3

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
系统中配置了Telegram Token，Webhook也设置成功，但机器人不回复消息。

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
![111111](https://user-images.githubusercontent.com/102845354/230260455-d491685f-029a-45cb-a2a4-094063e1e38e.png)
![2222222](https://user-images.githubusercontent.com/102845354/230260490-d41db99e-bac8-47f2-91d6-64b63e3782e6.png)

**Comment by phpshark** [comment]
怎样检查防火墙是否拦截了telegram的通知？
