### ISSUE TITLE
[Feature request]希望能支持xray新的VLESS+vision+realty

### ISSUE THREAD

**Issue by okoklai** [v2board/v2board#768]
Please describe in detail the problems or needs you have encountered.
请详细描述你遇到的问题或需求。

目前后端xrayr已经完成适配了，请大佬同步更新前端面板让我们早日用上新协议。

现在VMESS/TR被封的情况非常普遍，除非上加密隧道，基本上已经无法正常使用了。

**Comment by ruoyuqing** [comment]
同意，现在几乎每天得换个端口。。。

**Comment by 903496130** [comment]
> VMESS

为什么VMESS会被封禁呀 VMESS不是已经加密了吗，应该是检测不到的吧，求教🙏

**Comment by okoklai** [comment]
> > VMESS
> 
> 为什么VMESS会被封禁呀 VMESS不是已经加密了吗，应该是检测不到的吧，求教🙏

1、无法解密不表示没有特征。
2、封禁的话只要特征符合即可，无需知道具体内容。
3、当然，如果可以解密的话，封杀会更精准，更高效。

**Comment by helloworld113** [comment]
please

**Comment by cyril-cheng** [comment]
WARNING

VLESS 已被弃用并且可能被移除。

请考虑使用 Trojan 作为替代品。
[https://www.v2fly.org/v5/config/proxy/vless.html](url)

**Comment by cyril-cheng** [comment]
> > > VMESS
> > 
> > 
> > 为什么VMESS会被封禁呀 VMESS不是已经加密了吗，应该是检测不到的吧，求教🙏
> 
> 1、无法解密不表示没有特征。 2、封禁的话只要特征符合即可，无需知道具体内容。 3、当然，如果可以解密的话，封杀会更精准，更高效。

用nginx加密下很难？

**Comment by okoklai** [comment]
> > > > VMESS
> > > 
> > > 
> > > 为什么VMESS会被封禁呀 VMESS不是已经加密了吗，应该是检测不到的吧，求教🙏
> > 
> > 
> > 1、无法解密不表示没有特征。 2、封禁的话只要特征符合即可，无需知道具体内容。 3、当然，如果可以解密的话，封杀会更精准，更高效。
> 
> 用nginx加密下很难？

GFW具体的原理我也不清楚。

但是从我个人的经历来看，VMESS+WS+NGINX(TLS),TROJAN+NGINX(TLS),VLESS+WS+NGINX(TLS)都有被封端口/IP的情况，在敏感时期更为严重。

当然，直接xrayr内置的WS（TCP）+TLS也是一样被封禁。

参考相关帖子“TLS IN TLS TUNNEL”的特征综合个人经历。个人感觉跟NGINX关系不大。
