### ISSUE TITLE
升级1.2后订阅无法修改，但可以添加

### ISSUE THREAD

**Issue by thank243** [v2board/v2board#77]
此为phpinfo信息
![phpinfo](https://user-images.githubusercontent.com/11692994/75959634-93565e00-5ef9-11ea-80d3-1a425db0d055.png)

此为chrome错误截图
![chrome](https://user-images.githubusercontent.com/11692994/75959772-d0baeb80-5ef9-11ea-9870-fa73ba2e20f0.png)

此为nginx access.log信息（直接返回500错误）
![error500](https://user-images.githubusercontent.com/11692994/75959805-e7f9d900-5ef9-11ea-974d-a9e86312ea4a.png)

查阅storage/logs/相关日志，并没有发现返回错误。
php也打开error_log等选项也没有发现相关错误。
前后端均为最新的1.2版本。并采用前后分离，api域名与网站域名不相同托管在oss上，均开启cf的cdn。
除了订阅不能修改外，其他功能皆正常。望指教，谢谢。

刚测试添加新的订阅成功，但是返回继续修改依然报错。

**Comment by thank243** [comment]
查阅代码，发现是
```
            if (!User::where('plan_id', $plan->id)
                ->update(['group_id' => $plan->group_id])
            ) {
                DB::rollBack();
                abort(500, '保存失败');
            }

```
直接返回500，难怪只有nginx有个500错误日志

**Comment by tokumeikoi** [comment]
1.2.1版本中已修复
