### ISSUE TITLE
which backend support hysteria ?[Feature request]

### ISSUE THREAD

**Issue by alirezashahrokhi** [v2board/v2board#770]
hi all dears
which backend support hysteria for version 1.7.4 v2board?

xrayr can not support this

**Comment by zowei2016** [comment]
me too

**Comment by sleeeeeeepa** [comment]
我也想知道

**Comment by Ahmad10611** [comment]
It's very funny. It's like having a car but no gas. Please explain how to build a hysteria node.

**Comment by Mjeir** [comment]
and me

**Comment by MrVb0** [comment]
This panel does not add Vision and Reality which is supported in XrayR and it works well!!! 
But he has added Hysteria which is not supported by any backend and blocked in many areas !  It's very strange...
We have requested many times to add vless, vision, reality, but it has not been paid attention to!! 
I am sorry ...
