### ISSUE TITLE
ERROR 1.2版本支付启用开关后报错

### ISSUE THREAD

**Issue by TerrorbladeART** [v2board/v2board#78]
后台- 支付配置 - 支付宝 - 启用  关闭再打开后报错。  且更改支付配置也报错
php7.3  master分支 1.2版本 
生产测试环境均报。
![9B4F16A9-B923-46CB-9ED6-EB987FEA2EAE](https://user-images.githubusercontent.com/59191279/75993063-e220e980-5f33-11ea-974d-55732328caa6.jpeg)

**Comment by tokumeikoi** [comment]
1.2.1版本中已经修复

**Comment by TerrorbladeART** [comment]
> 1.2.1版本中已经修复

ThankU
