### ISSUE TITLE
[BUG]1.7.3发现流量不重置

### ISSUE THREAD

**Issue by tszho-t** [v2board/v2board#780]
截图什么的就不需要提供了吧，反正就是无论我选择按月重置还是每月1日号重置，都是不重置的，因为是个人自用所以流量并不多，刚刚才发现，试过系统设置和单独的订阅设置都是如此，之前的版本好像没有这个问题，具体忘了，反正都是从1.7.0 1.7.1  ~~一直升级到目前1.7.3

**Comment by okoklai** [comment]
检查守护进程是否正常。

**Comment by tszho-t** [comment]
进程守护正常，我甚至重启过守护进程，整台服务器重启过，别的都正常，唯有流量不会重置

**Comment by mikemails** [comment]
我之前也有这个困扰，我不太懂，不过在搜索查看了有关问题的 issue 后，我在 宝塔 aaPanel Cron 里 add 了一个定时任务就好了。
![image](https://github.com/v2board/v2board/assets/71946909/a7fedd85-8504-409e-8059-ea530d33a2d0)
