### ISSUE TITLE
Set up webhooks - Request failed [Feature request]

### ISSUE THREAD

**Issue by MmdData** [v2board/v2board#781]
Hello, im getting this error when im trying to set up webhooks using [one-click settings] button:

> Request failed
> 
> Error from TG: Bad Request: bad webhook: An HTTPS URL must be provided for webhook
>
![webooks_error](https://user-images.githubusercontent.com/17106435/230933047-0765c2df-2842-46d2-b8f6-6fcbddfa84cb.png)

**Comment by cyril-cheng** [comment]
website use https

**Comment by MmdData** [comment]
> website must use https

website is using https and the certificate is valid.

**Comment by phpshark** [comment]
> > 网站必须使用https
> 
> 网站正在使用 https 且证书有效。
打开站点的“强制HTTPS”按钮
