### ISSUE TITLE
1.7.4PHP线程BUG

### ISSUE THREAD

**Issue by L763103999** [v2board/v2board#784]
Please describe in detail the problems or needs you have encountered.
请详细描述你遇到的问题或需求。
![image](https://user-images.githubusercontent.com/114154414/231449363-88095340-300b-4468-9e77-d9eba312b5c4.png)
更新 1.7.4开发版本后 出现 PHP线程爆炸  本服务器 4核 内存 24G

**Comment by L763103999** [comment]
![image](https://user-images.githubusercontent.com/114154414/231449902-67b60ab2-34e9-4b78-8fe3-673d2f8118c5.png)
这是图

**Comment by L763103999** [comment]
![image](https://user-images.githubusercontent.com/114154414/231450329-33eb469a-b188-46fa-83ed-2a28ac051282.png)

**Comment by cg3s** [comment]
![image](https://user-images.githubusercontent.com/28707826/231951468-e26d526b-27f4-40db-b615-e24c7fe15302.png)
同样遇到，更新到最新版后，就满负荷状态。

**Comment by Chnancheek** [comment]
我也出现了php线程爆炸
[](https://image.cheekd1s.us/file/1d8e6a982da32ff3181bd.png)

**Comment by Chnancheek** [comment]
[](https://image.cheekd1s.us/file/1d8e6a982da32ff3181bd.png)
