### ISSUE TITLE
请问啥时候支持vless+reality

### ISSUE THREAD

**Issue by AK47-Plusone** [v2board/v2board#796]
请问啥时候支持vless+reality。
真的是又稳又快

**Comment by phoenixx98** [comment]
**I am also waiting for it. Please add vless & reality protocol. Thanks to the developer..**

**Comment by Cp0204** [comment]
自己开分支吧，很多PR作者也不处理也不回复，这个源开得就很消极，没劲

**Comment by Cp0204** [comment]
https://github.com/v2board/v2board/pull/633

**Comment by lotusproxy** [comment]
> 请问啥时候支持vless+reality。
> 真的是又稳又快

No standard for reality share link for now, also it's in beta currently
