### ISSUE TITLE
Please Add vless & Reallity Protocol ......English lang..

### ISSUE THREAD

**Issue by phoenixx98** [v2board/v2board#797]
I am also waiting for it. Please add vless & reality protocol. Thanks to the developer..

**Comment by mmsh1370** [comment]
I am also waiting for it. Please add vless & reality protocol. Thanks to the developer..

**Comment by cyril-cheng** [comment]
![image](https://user-images.githubusercontent.com/49748357/236591249-eda62c03-57a2-4836-a991-66b212c6080e.png)
https://www.v2fly.org/v5/config/proxy/vless.html
