### ISSUE TITLE
Stripe WeChat Pay 支付後無法跳轉交易[BUG]

### ISSUE THREAD

**Issue by 109980549** [v2board/v2board#804]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
1.7.3

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
user用微信支付後無法跳轉，stripe詢問後回復：

That's because the source is not attached to any customer so we don;t know where to attach that source.
We need to create a customer first, you can do this through the dashboard, I'll give you the steps.
1. Navigate to the Customers page on your Dashboard
2. Click the “+ New” button and fill in all the relevant information about the customer
3. Click “Add customer” to save the customer’s details to your Stripe account
Next, charge the source via API. https://stripe.com/docs/sources/customers#single-use-sources

如果說可以在新版本中更新這個功能，那就太好了。

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by seal-net** [comment]
你好，我也出现这样的问题，请问你解决了吗？

**Comment by mm350** [comment]
请问APIkey v1在哪里找到，我只看到v2和v3
