### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by hake7987** [v2board/v2board#811]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
v1.7.3

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------

链接导出后报错：
Could not switch to this profile!
invalid dns enhanced-mode: redir-host

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------
[2023-05-06 14:13:05] local.ERROR: Connection refused {"exception":"[object] (RedisException(code: 0): Connection refused at /www/wwwroot/xxx.xxxx.com/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php:153)
[stacktrace]
#0 /www/wwwroot/xxx.xxxx.com/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(153): Redis->connect()
#1 /www/wwwroot/xxx.xxxx.com/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(84): Illuminate\\Redis\\Connectors\\PhpRedisConnector->establishConnection()
#2 /www/wwwroot/xxx.xxxx.com/vendor/laravel/framework/src/Illuminate/Support/helpers.php(263): Illuminate\\Redis\\Connectors\\PhpRedisConnector->Illuminate\\Redis\\Connectors\\{closure}()
#3 /www/wwwroot/xxx.xxxx.com/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(75): tap()
#4 /www/wwwroot/xxx.xxxx.com/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(27): Illuminate\\Redis\\Connectors\\PhpRedisConnector->createClient()
#5 [internal function]: Illuminate\\Redis\\Connectors\\PhpRedisConnector->Illuminate\\Redis\\Connectors\\{closure}()
#6 /www/wwwroot/xxx.xxxx.com/vendor/laravel/framework/src/Illuminate/Redis/Connections/PhpRedisConnection.php(536): call_user_func()
#7 /www/wwwroot/xxx.xxxx.com/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(220): Illuminate\\Redis\\Connections\\PhpRedisConnection->command()
#8 /www/wwwroot/xxx.xxxx.com/vendor/laravel/framework/src/Illuminate/Redis/Connections/PhpRedisConnection.php(575): Illuminate\\Redis\\Connections\\Connection->__call()
#9 /www/wwwroot/xxx.xxxx.com/vendor/laravel/horizon/src/Repositories/RedisSupervisorRepository.php(150): Illuminate\\Redis\\Connections\\PhpRedisConnection->__call()
#10 /www/wwwroot/xxx.xxxx.com/vendor/laravel/horizon/src/Supervisor.php(216): Laravel\\Horizon\\Repositories\\RedisSupervisorRepository->forget()
#11 /www/wwwroot/xxx.xxxx.com/vendor/laravel/horizon/src/Supervisor.php(320): Laravel\\Horizon\\Supervisor->terminate()
#12 /www/wwwroot/xxx.xxxx.com/vendor/laravel/horizon/src/Supervisor.php(286): Laravel\\Horizon\\Supervisor->ensureParentIsRunning()
#13 /www/wwwroot/xxx.xxxx.com/vendor/laravel/horizon/src/Supervisor.php(260): Laravel\\Horizon\\Supervisor->loop()
#14 /www/wwwroot/xxx.xxxx.com/vendor/laravel/horizon/src/Console/SupervisorCommand.php(101): Laravel\\Horizon\\Supervisor->monitor()
#15 /www/wwwroot/xxx.xxxx.com/vendor/laravel/horizon/src/Console/SupervisorCommand.php(76): Laravel\\Horizon\\Console\\SupervisorCommand->start()
#16 /www/wwwroot/xxx.xxxx.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Horizon\\Console\\SupervisorCommand->handle()
#17 /www/wwwroot/xxx.xxxx.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#18 /www/wwwroot/xxx.xxxx.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#19 /www/wwwroot/xxx.xxxx.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#20 /www/wwwroot/xxx.xxxx.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#21 /www/wwwroot/xxx.xxxx.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#22 /www/wwwroot/xxx.xxxx.com/vendor/symfony/console/Command/Command.php(298): Illuminate\\Console\\Command->execute()
#23 /www/wwwroot/xxx.xxxx.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(120): Symfony\\Component\\Console\\Command\\Command->run()
#24 /www/wwwroot/xxx.xxxx.com/vendor/symfony/console/Application.php(1040): Illuminate\\Console\\Command->run()
#25 /www/wwwroot/xxx.xxxx.com/vendor/symfony/console/Application.php(301): Symfony\\Component\\Console\\Application->doRunCommand()
#26 /www/wwwroot/xxx.xxxx.com/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#27 /www/wwwroot/xxx.xxxx.com/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\\Component\\Console\\Application->run()
#28 /www/wwwroot/xxx.xxxx.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#29 /www/wwwroot/xxx.xxxx.com/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#30 {main}
"} 
[2023-05-06 14:27:03] local.ERROR: Facade\Ignition\QueryRecorder\QueryRecorder::__construct(): Argument #2 ($reportBindings) must be of type bool, null given, called in /www/wwwroot/xxx.xxxx.com/vendor/facade/ignition/src/IgnitionServiceProvider.php on line 383 {"exception":"[object] (TypeError(code: 0): Facade\\Ignition\\QueryRecorder\\QueryRecorder::__construct(): Argument #2 ($reportBindings) must be of type bool, null given, called in /www/wwwroot/xxx.xxxx.com/vendor/facade/ignition/src/IgnitionServiceProvider.php on line 383 at /www/wwwroot/xxx.xxxx.com/vendor/facade/ignition/src/QueryRecorder/QueryRecorder.php:22)
[stacktrace]
#0 /www/wwwroot/xxx.xxxx.com/vendor/facade/ignition/src/IgnitionServiceProvider.php(383): Facade\\Ignition\\QueryRecorder\\QueryRecorder->__construct()
#1 /www/wwwroot/xxx.xxxx.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(873): Facade\\Ignition\\IgnitionServiceProvider->Facade\\Ignition\\{closure}()
#2 /www/wwwroot/xxx.xxxx.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(758): Illuminate\\Container\\Container->build()
#3 /www/wwwroot/xxx.xxxx.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): Illuminate\\Container\\Container->resolve()
#4 /www/wwwroot/xxx.xxxx.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(694): Illuminate\\Foundation\\Application->resolve()
#5 /www/wwwroot/xxx.xxxx.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(836): Illuminate\\Container\\Container->make()
#6 /www/wwwroot/xxx.xxxx.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(1027): Illuminate\\Foundation\\Application->make()
#7 /www/wwwroot/xxx.xxxx.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(947): Illuminate\\Container\\Container->resolveClass()
#8 /www/wwwroot/xxx.xxxx.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(908): Illuminate\\Container\\Container->resolveDependencies()
#9 /www/wwwroot/x x x/vendor/laravel/framework/src/Illuminate/Container/Container.php(758): Illuminate\\Container\\Container->build()
#10 /www/wwwroot/xxx.xxxx.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): Illuminate\\Container\\Container->resolve()
#11 /www/wwwroot/xxx.xxxx.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(694): Illuminate\\Foundation\\Application->resolve()
#12 /www/wwwroot/xxx.xxxx.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(836): Illuminate\\Container\\Container->make()
#13 /www/wwwroot/xxx.xxxx.com/vendor/facade/ignition/src/IgnitionServiceProvider.php(419): Illuminate\\Foundation\\Application->make()
#14 [internal function]: Facade\\Ignition\\IgnitionServiceProvider->Facade\\Ignition\\{closure}()
#15 /www/wwwroot/xxx.xxxx.com/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(695): array_map()
#16 /www/wwwroot/xxx.xxxx.com/vendor/facade/ignition/src/IgnitionServiceProvider.php(418): Illuminate\\Support\\Collection->map()
#17 /www/wwwroot/xxx.xxxx.com/vendor/facade/ignition/src/IgnitionServiceProvider.php(153): Facade\\Ignition\\IgnitionServiceProvider->registerBuiltInMiddleware()
#18 /www/wwwroot/xxx.xxxx.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(682): Facade\\Ignition\\IgnitionServiceProvider->register()
#19 /www/wwwroot/xxx.xxxx.com/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(75): Illuminate\\Foundation\\Application->register()
#20 /www/wwwroot/xxx.xxxx.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(659): Illuminate\\Foundation\\ProviderRepository->load()
#21 /www/wwwroot/xxx.xxxx.com/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#22 /www/wwwroot/xxx.xxxx.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap()
#23 /www/wwwroot/xxx.xxxx.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith()
#24 /www/wwwroot/xxx.xxxx.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#25 /www/wwwroot/xxx.xxxx.com/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#26 {main}
"}

**Comment by uby777881** [comment]
Clash for windows?
