### ISSUE TITLE
[BUG]无法登陆

### ISSUE THREAD

**Issue by v2support** [v2board/v2board#814]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号 1.7.3
--------

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
从1.5.5更新执行sh update.sh 面板还是显示1.5.5, 下载zip然后覆盖到网站目录,执行php artisan v2board:update, 现在登陆界面提示 " 请求失败
遇到了些问题，我们正在进行处理""

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
![图片](https://user-images.githubusercontent.com/132957347/236954774-594752a0-487a-420c-a701-9931b659903e.png)
![图片](https://user-images.githubusercontent.com/132957347/236954868-d4bfba76-9e5f-406b-9dc3-08d071a30996.png)

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

[2023-05-09 06:47:02] local.ERROR: Class 'Firebase\JWT\JWT' not found {"exception":"[object] (Error(code: 0): Class 'Firebase\\JWT\\JWT' not found at /www/wwwroot/.com/app/Services/AuthService.php:25)
[stacktrace]
#0 /www/wwwroot/.com/app/Http/Controllers/Passport/AuthController.php(222): App\\Services\\AuthService->generateAuthData()
#1 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Passport\\AuthController->login()
#2 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#3 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#4 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\\Routing\\Route->runController()
#5 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Route->run()
#6 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#7 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#8 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#9 /www/wwwroot/.com/app/Http/Middleware/Language.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#10 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\Language->handle()
#11 /www/wwwroot/.com/app/Http/Middleware/ForceJson.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\ForceJson->handle()
#13 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then()
#15 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack()
#16 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute()
#17 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute()
#18 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch()
#19 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#20 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#22 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#24 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#26 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#28 /www/wwwroot/.com/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#30 /www/wwwroot/.com/app/Http/Middleware/CORS.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\CORS->handle()
#32 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then()
#34 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#35 /www/wwwroot/.com/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle()
#36 {main}
"}

**Comment by alirezashahrokhi** [comment]
same problem

**Comment by Gogoworks** [comment]
我也遇到同样的问题，是否有解决方案？

**Comment by k23223** [comment]
> 🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问 🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions
> 
> ## The V2Board version number you are using
> 当前使用的V2Board版本号 1.7.3
> ## Briefly describe the problem you are experiencing
> 简单描述你遇到的问题
> 从1.5.5更新执行sh update.sh 面板还是显示1.5.5, 下载zip然后覆盖到网站目录,执行php artisan v2board:update, 现在登陆界面提示 " 请求失败 遇到了些问题，我们正在进行处理""
> 
> ## Screenshot of the reported error(Please do desensitization)
> 报告错误的截图（请做脱敏处理）
> ![图片](https://user-images.githubusercontent.com/132957347/236954774-594752a0-487a-420c-a701-9931b659903e.png) ![图片](https://user-images.githubusercontent.com/132957347/236954868-d4bfba76-9e5f-406b-9dc3-08d071a30996.png)
> 
> ## The latest log files in the storage/logs directory report from #1 (Please do desensitization)
> storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
> [2023-05-09 06:47:02] local.ERROR: Class 'Firebase\JWT\JWT' not found {"exception":"[object] (Error(code: 0): Class 'Firebase\JWT\JWT' not found at /www/wwwroot/.com/app/Services/AuthService.php:25) [stacktrace] #0 /www/wwwroot/.com/app/Http/Controllers/Passport/AuthController.php(222): App\Services\AuthService->generateAuthData() #1 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\Passport\AuthController->login() #2 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction() #3 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\Routing\ControllerDispatcher->dispatch() #4 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\Routing\Route->runController() #5 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\Routing\Route->run() #6 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}() #7 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #8 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\SubstituteBindings->handle() #9 /www/wwwroot/.com/app/Http/Middleware/Language.php(15): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #10 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\Language->handle() #11 /www/wwwroot/.com/app/Http/Middleware/ForceJson.php(20): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #12 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\ForceJson->handle() #13 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #14 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\Pipeline\Pipeline->then() #15 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\Routing\Router->runRouteWithinStack() #16 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\Routing\Router->runRoute() #17 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\Routing\Router->dispatchToRoute() #18 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Routing\Router->dispatch() #19 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}() #20 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #21 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle() #22 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #23 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle() #24 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #25 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle() #26 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #27 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle() #28 /www/wwwroot/.com/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #29 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle() #30 /www/wwwroot/.com/app/Http/Middleware/CORS.php(18): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #31 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\CORS->handle() #32 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #33 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\Pipeline\Pipeline->then() #34 /www/wwwroot/.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter() #35 /www/wwwroot/.com/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle() #36 {main} "}

重新设置一下权限，递归设置
