### ISSUE TITLE
[BUG]知识库不支持波斯语，希望新增一下～

### ISSUE THREAD

**Issue by imKaricia** [v2board/v2board#815]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
1.7.3

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------

知识库不支持波斯语，希望新增一下～

**Comment by tokumeikoi** [comment]
后续会重做
