### ISSUE TITLE
客户面板-使用教程：点击后报错 Server Error。php7.3 master分支1.2.1版本

### ISSUE THREAD

**Issue by raychien326** [v2board/v2board#82]
![屏幕快照 2020-03-06 01 40 19](https://user-images.githubusercontent.com/56867373/76009360-0ee0fb00-5f4c-11ea-8d28-621b0ce5a85b.png)

**Comment by tokumeikoi** [comment]
重新执行拉去代码并更新即可

**Comment by raychien326** [comment]
thank u

tokumeikoi <notifications@github.com> 于2020年3月6日周五 上午11:50写道：
