### ISSUE TITLE
可以兼容下 x-ui面板吗

### ISSUE THREAD

**Issue by awdzs123** [v2board/v2board#820]
您好，由于x-ui面板有对用户ID进行验证，所以我苦于v2board上传节点的时候没有用户id的输入框，这往往导致v2ray更新订阅的时候，vmess和vless的节点的用户id是随机生成的，这往往使节点无法正常使用，希望可以兼容下。然后还有就是Trojans的密码验证，v2board上传节点的过程中也没有密码的输入框，希望可以兼容下

**Comment by bigsb-scw** [comment]
+1
