### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jerrytomdog** [v2board/v2board#826]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
1.7.3

Briefly describe the problem you are experiencing
简单描述你遇到的问题
中转节点，配置完成后，可以正常联网但是面板不显示在线情况，用户使用不消耗流量

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by betaxab** [comment]
子/父节点 逻辑请先搞清楚再来用。这个跟 V2board 无关。

你新增子节点，所有计费都是父节点来完成的，子节点只负责是否能在前端面板上显示，且子节点的服务器连接配置信息、倍率以及在线状态均继承自父节点。
子节点只是用来配置（中转）服务器域名/IP及端口，标签，节点名称的。

至于你对应（中转）服务器上所消耗的流量，这个没法来统计

对于子节点：
权限组控制用户能否前端看到这个子节点
对于父节点：
权限组控制用户能否连上这个节点

面板不正常显示在线状态：

请从子节点配置中正确选择父节点，不选择或者选择错误的父节点自然不正确显示在线状态
