### ISSUE TITLE
v2board api documents

### ISSUE THREAD

**Issue by RezaNazari051** [v2board/v2board#834]
Hello
I need the document panel
Is it possible to help me?

**Comment by Rezasharifi9** [comment]
> Hello I need the document panel Is it possible to help me?

No Help You , Sorry

**Comment by cyril-cheng** [comment]
https://github.com/cdnf/v2board-api-document

**Comment by Rezasharifi9** [comment]
Do you also have the api document on the admin panel side?

**Comment by RezaNazari051** [comment]
Do you have the admin panel documents?

**Comment by tobi1008** [comment]
Why do I go to the admin URL again 404
https://share.cleanshot.com/dz9RwCf0
