### ISSUE TITLE
[BUG]流量不重置

### ISSUE THREAD

**Issue by X-Firefly** [v2board/v2board#838]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------1.73

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------流量不重置

不管是选每月1号还是按月重置  流量都不会重置~！

**Comment by 794786374** [comment]
怎么看自己什么版本

**Comment by X-Firefly** [comment]
> 怎么看自己什么版本

左下角有版本号

**Comment by huangzaiguo** [comment]
也遇到同样的问题，同是1.7.3

**Comment by 794786374** [comment]
卸载PHP和那两个插件，重新安装可以解决

**Comment by X-Firefly** [comment]
> 卸载PHP和那两个插件，重新安装可以解决

两个是什么插件？

**Comment by 794786374** [comment]
redis和fileinfo
现在又遇到另外一个问题了，路由和限速不起作用

**Comment by X-Firefly** [comment]
> redis和fileinfo 现在又遇到另外一个问题了，路由和限速不起作用

问题多多啊？算了 还是不折腾了 手动重置一下好了。

**Comment by Pastechn** [comment]
流量重置是通过计划任务 `reset:traffic` 实现的 可以先检查一下计划任务有没有执行成功

**Comment by huangzaiguo** [comment]
宝塔里添加一个定时任务就可以了

php /网站目录/artisan reset:traffic

**Comment by X-Firefly** [comment]
> 宝塔里添加一个定时任务就可以了
> 
> php /网站目录/artisan reset:traffic

多谢指教！
