### ISSUE TITLE
[BUG]TG机器人无法收到消息！

### ISSUE THREAD

**Issue by phpshark** [v2board/v2board#840]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
 v1.7.3

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------

后台Token，以及Webhook一键设置都设置成功了，但是就是发送信息给机器人没有反应。
官方文档有写，防火墙拦截，但是vps的防火墙我是关闭状态的！

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

![4](https://github.com/v2board/v2board/assets/112195700/0ee9330f-7b7d-4a12-bde5-51ecf692858e)

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by mogan1999** [comment]
+1

**Comment by 794786374** [comment]
我的套餐使用的流量和节点使用人数都看不到欸，全是0

**Comment by devopssdoc** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
