### ISSUE TITLE
节点顺序无法重置（希望可以优化）

### ISSUE THREAD

**Issue by Aim233a** [v2board/v2board#843]
比如：
1 ss 节点 1
2 ss 节点 2

把 1 ss 节点 1 删除后在创建一个就成为了 3 ss 节点 1

能不能删除后把 2 ss节点 2 变成 1 然后再新建就是 2

有啥坏处也希望大家评论一下😜

**Comment by Genesis-Fire** [comment]
> 比如：
> 1 ss 节点 1
> 2 ss 节点 2
> 
> 把 1 ss 节点 1 删除后在创建一个就成为了 3 ss 节点 1
> 
> 能不能删除后把 2 ss节点 2 变成 1 然后再新建就是 2
> 
> 有啥坏处也希望大家评论一下😜

已存在的节点号不能变 变了不得改后端？应该说让新建的节点号取代刚删除的节点号
