### ISSUE TITLE
[Feature request]讨论：VLESS协议是否已经”过时“”弃用“的

### ISSUE THREAD

**Issue by okoklai** [v2board/v2board#847]
Please describe in detail the problems or needs you have encountered.
请详细描述你遇到的问题或需求。

事实上，基于TLS OVER TLS的VMESS/TROJAN协议目前在CN已经遭到了大范围的精确封锁。

这让v2board等面板名存实亡。因为大部份草根用户使用v2b管理直连节点，会遭到防火墙封禁端口/封禁IP等。

当然，对于有实力的商业商家不存在这个问题，他们可以通过自研加密协议打隧道的方式，或者申请IPLC/IEIP专线等方式来规避封锁。

这对众多拥有优质直连线路的人来说是个不幸的消息，因为诸多CN2GIA、9929、三网CMI等优质线路使用这个面板来管理会遭到封锁。

VMESS/VLESS过时与否：VLESS独立的原因起源于一次关于开源协议的争论。但是认为VLESS是一个遭到”弃用的“”过时协议“无疑是一个带有**偏见**的行为。

VLESS目前版本一直在更新。并且快速响应了这次防火墙大范围封锁，推出了基于XTLS改进的reality协议。在实测中，抗封锁能力是有目共睹的。这给我们带来了新的希望。

最后无论作者做出怎样的决定，我还是衷心的谢谢您的开源和无私奉献。

**Comment by tokumeikoi** [comment]
vless会被加入
