### ISSUE TITLE
[INFO]增加修改节点信息后进行提交时,会有几率报请求失败问题

### ISSUE THREAD

**Issue by TerrorbladeART** [v2board/v2board#85]
[INFO]
PHP7.3 
master分支1.2.1版本
增加修改节点信息后进行提交时,会有几率报请求失败. 且无法修改审计规则.
重新刷新页面后方能正常操作.

[](url)
<img width="675" alt="WechatIMG10" src="https://user-images.githubusercontent.com/59191279/76055589-0a99f980-5faf-11ea-9c6d-06958847f50e.png">
<img width="491" alt="WechatIMG9" src="https://user-images.githubusercontent.com/59191279/76055595-0e2d8080-5faf-11ea-8a27-6ce0dcfa8bc5.png">

**Comment by tokumeikoi** [comment]
没有复现，具体操作步骤有吗

**Comment by TerrorbladeART** [comment]
我再次遇到的时候我调试一下吧,到时候我再提交
