### ISSUE TITLE
[BUG]流量记录空，没有明细

### ISSUE THREAD

**Issue by binad2022** [v2board/v2board#853]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------1.74

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
无论用户前端还是后台流量记录都是空

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by mm350** [comment]
同样问题+1，期待解决

**Comment by kissimok** [comment]
流量统计,不会增加....

**Comment by kissimok** [comment]
仪表盘流量使用会正常增加,,后台也会正常增加..唯独就是用户登录以后在“流量明细”这个里面不会改变
