### ISSUE TITLE
[BUG]流量统计问题,

### ISSUE THREAD

**Issue by kissimok** [v2board/v2board#854]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
1.7.4

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
我是从1.7.3正常操作更新到1.7.4的......以下问题在1.7.3没升级之前都是正常的

后台,在用户管理界面,查看“已用”流量可以正常显示增加.......但是.....选择用户..查看“TA的流量记录”这个里面流量记录是不会有任何改变的.

前段,用户登录后..在仪表盘查看流量可以正常显示增加....但是...在“流量明细”里面.流量也无法增加...

过了凌晨12点后....后台的“昨日节点流量排行”也不会统计流量了

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by Memory-good** [comment]
我也是这个问题，怎么回退

**Comment by kissimok** [comment]
> 我也是这个问题，怎么回退

退回貌似要有之前文件备份和数据库备份......我有备份,但是目前我没有选择退回,,,如果你有上个版本备份,你直接重新安装,然后导入配置文件和数据库就好了.

**Comment by mm350** [comment]
我已降级。
备份：1，备份/config/v2board.php，2，备份数据库
降级：删除网站目录所有文件，下载1.7.1 https://github.com/v2board/v2board/archive/refs/tags/1.7.1.zip，放到网站目录解压，正常安装。
恢复v2board.php文件，恢复数据库，ssh到网站目录执行sh update.sh,搞定。(执行一次是恢复，再执行第二次又是升级)

**Comment by kissimok** [comment]
> 我已降级。
> 备份：1，备份/config/v2board.php，2，备份数据库
> 降级：删除网站目录所有文件，下载1.7.1 [https://github.com/v2board/v2board/archive/refs/tags/1.7.1.zip，放到网站目录解压，正常安装。](https://github.com/v2board/v2board/archive/refs/tags/1.7.1.zip%EF%BC%8C%E6%94%BE%E5%88%B0%E7%BD%91%E7%AB%99%E7%9B%AE%E5%BD%95%E8%A7%A3%E5%8E%8B%EF%BC%8C%E6%AD%A3%E5%B8%B8%E5%AE%89%E8%A3%85%E3%80%82)
> 恢复v2board.php文件，恢复数据库，ssh到网站目录执行sh update.sh,搞定。(执行一次是恢复，再执行第二次又是升级)

你这个步骤我用了会报错.....我的解决方法是..
1:删除数据库,删除目录下所有文件.....
2:创建数据库,账号密码一样的...
3:上传了1.7.3版本...正常全新方式安装一次..
4:导入数据库和v2board.php文件..
5:在网站目录执行一次sh update.sh
就这样就没有问题了

**Comment by tokumeikoi** [comment]
如果是6.4日更新的，数据需要在6.6日后才会正常开始统计，从174开始用户侧的流量数据也将是次日计入数据库，并非bug
