### ISSUE TITLE
[BUG] 统计队列被移除

### ISSUE THREAD

**Issue by HynoR** [v2board/v2board#857]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
1.74

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
1.73还存在，1.74没有统计这一栏。
翻[PR](https://github.com/v2board/v2board/pull/848/files#diff-8913740bc0fb3a35f809661f02cd84c56a0cf60a226e94256041607c092b76d2)发现直接移除了这个Job。 删除该文件的操作详见该[commit](https://github.com/v2board/v2board/commit/eee5152f5244e87ef359a53f9878be1d7eeaec67)
其他issue反馈1.74没有流量详单统计估计是这个原因。

更新和PR也没对移除的更改说明原因。这个地方需要跟进一下变动说明，并且如果真的需要移除这个Job，前端也需要同步把这一栏给删掉。

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
发生的文件更改
<img width="903" alt="image" src="https://github.com/v2board/v2board/assets/20227709/7f9db81d-3017-402b-b679-6710a83fa379">

1.73队列面板图
<img width="688" alt="image" src="https://github.com/v2board/v2board/assets/20227709/9ef927bd-8a5d-425d-90c4-97974087cd02">

1.74队列面板图
<img width="710" alt="image" src="https://github.com/v2board/v2board/assets/20227709/9d8a72b7-d4fb-4971-bef6-cd9b1def6c7f">

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by aldington-david** [comment]
为啥移除了
