### ISSUE TITLE
[BUG]hysteria节点开启在订阅中不显示

### ISSUE THREAD

**Issue by sleeeeeeepa** [v2board/v2board#858]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
1.7.4

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
创建hysteria节点并开启显示, 用户配置对应的权限/订阅信息，复制出的订阅链接打开为空
如果在这个权限内再加入一个vmess（一个hysteria节点一个vmess节点），则订阅链接中只有vmess
下图为仅配置hy节点 并开启

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
![image](https://github.com/v2board/v2board/assets/26105843/f2c88c03-1743-408d-bb58-67a18d2b3db5)

![image](https://github.com/v2board/v2board/assets/26105843/27d8f6ac-63b7-496a-b06d-a9a9ada45210)
![image](https://github.com/v2board/v2board/assets/26105843/692cd52e-6870-4e96-a761-30dedd367a0b)
![image](https://github.com/v2board/v2board/assets/26105843/77a22c88-72c1-48b3-9782-0d0b341a4651)

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------
无日志

**Comment by tokumeikoi** [comment]
客户端不支持

**Comment by Mjeir** [comment]
> 🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问 🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions
> 
> ## The V2Board version number you are using
> 当前使用的V2Board版本号
> 1.7.4
> 
> ## Briefly describe the problem you are experiencing
> 简单描述你遇到的问题
> 创建hysteria节点并开启显示, 用户配置对应的权限/订阅信息，复制出的订阅链接打开为空 如果在这个权限内再加入一个vmess（一个hysteria节点一个vmess节点），则订阅链接中只有vmess 下图为仅配置hy节点 并开启
> 
> ## Screenshot of the reported error(Please do desensitization)
> 报告错误的截图（请做脱敏处理）
> ![image](https://user-images.githubusercontent.com/26105843/243290602-f2c88c03-1743-408d-bb58-67a18d2b3db5.png)
> 
> ![image](https://user-images.githubusercontent.com/26105843/243290752-27d8f6ac-63b7-496a-b06d-a9a9ada45210.png) ![image](https://user-images.githubusercontent.com/26105843/243290893-692cd52e-6870-4e96-a761-30dedd367a0b.png) ![image](https://user-images.githubusercontent.com/26105843/243290992-77a22c88-72c1-48b3-9782-0d0b341a4651.png)
> 
> ## Screenshot of the reported error(Please do desensitization)
> 报告错误的截图（请做脱敏处理）
> ## The latest log files in the storage/logs directory report from #1 (Please do desensitization)
> storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
> 无日志

How did you use this protocol?

**Comment by sleeeeeeepa** [comment]
> 客户端不支持
是在浏览器直接访问订阅链接没有返回  还不到客户端

**Comment by sleeeeeeepa** [comment]
https://github.com/v2board/v2board/issues/858#issuecomment-1577186175
是在浏览器直接访问订阅链接没有返回 还不到客户端

**Comment by sleeeeeeepa** [comment]
> 客户端不支持



是在浏览器直接访问订阅链接没有返回 还不到客户端
