### ISSUE TITLE
[BUG]等了几天了，流量依旧没有记录信息，你们有么

### ISSUE THREAD

**Issue by luowei729** [v2board/v2board#860]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
1.7.4

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
依旧没有记录信息

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
![image](https://github.com/v2board/v2board/assets/10611605/ed532ffb-4206-454a-a567-caa59957e799)

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by haibinml** [comment]
我也一样

**Comment by X-Firefly** [comment]
我的连面板 昨日流量也没显示。。。

**Comment by mm350** [comment]
我的可以了。
4号升级的，5号凌晨没记录，降级到1.7.1 。
听说要等两天，又升级了，然后每天0：15分才显示前一天记录

**Comment by linglala** [comment]
一样的情况，都几天了

**Comment by lotusproxy** [comment]
> 一样的情况，都几天了

Please make sure you've restarted the panel

**Comment by linglala** [comment]
> > 同样的情况，都几天了
> 
> 请确保您已重新启动面板

服务器和宝塔面都重启过了.

**Comment by haibinml** [comment]
> > > 同样的情况，都几天了
> > 
> > 
> > 请确保您已重新启动面板
> 
> 服务器和宝塔面都重启过了.

我直接吧数据库清了就恢复了然后吧用户再倒回来
