### ISSUE TITLE
权限组不能正常删除&父子节点倍率

### ISSUE THREAD

**Issue by xb0or** [v2board/v2board#87]
1、权限租可以正常添加 但是不能正常删除
2、直连节点为父节点倍率为1x  中转节点为子节点倍率为2  使用中转节点倍率计算为父节点倍率 1X 希望可以子父节点单独计算倍率 
谢谢大佬

**Comment by tokumeikoi** [comment]
1.https://github.com/v2board/v2board/issues/86
2.没办法以子节点记录倍率
