### ISSUE TITLE
[INFO]工单栏点击提交人邮箱进入空白页面问题

### ISSUE THREAD

**Issue by TerrorbladeART** [v2board/v2board#89]
[INFO]
php 7.3
master分支1.2.1版本

点击提交工单用户的邮箱进入空白页面 空白URL格式如下:
https://www.XXX.XXX/#/user?email=1234567@123.com
      
正确url格式应该如:https://www.xxx.xxx/admin#/user?email=xxx@xxx.com
![image](https://user-images.githubusercontent.com/59191279/76073696-fcf76a80-5fd4-11ea-9c29-6d07068d5663.png)

**Comment by tokumeikoi** [comment]
1.2.2 fix
