### ISSUE TITLE
500 Server Error

### ISSUE THREAD

**Issue by Topcckin** [v2board/v2board#9]
您好，我3次尝试通过TG群教程搭建前端，前两次使用的教程里面的1.0.1版本，后面一次使用的1.0.2，打开域名都是500 Server Error错误，我使用的是BT面板，安装环境为PHP73，Nginx 1.17，MySQL 5.6，redis已经安装，除了BT面板，基本上就是按照教程走的，不知道哪里出问题了。

**Comment by tokumeikoi** [comment]
报错日志位于storage/logs目录下，如果没有日志请检查目录权限

**Comment by Topcckin** [comment]
[2020-01-06 06:21:36] local.ERROR: The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths. {"exception":"[object] (RuntimeException(code: 0): The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths. at /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:43)
[stacktrace]
#0 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(28): Illuminate\\Encryption\\Encrypter->__construct('\\fR\\xDD#B>\\x0FO\\x82\\xAD\\x03\\xD0\\xF7\\xE1]...', 'AES-256-CBC')
#1 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(799): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#2 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build(Object(Closure))
#3 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\\Container\\Container->resolve('encrypter', Array)
#4 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(769): Illuminate\\Container\\Container->make('encrypter', Array)
#5 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(945): Illuminate\\Foundation\\Application->make('encrypter')
#6 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(873): Illuminate\\Container\\Container->resolveClass(Object(ReflectionParameter))
#7 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(834): Illuminate\\Container\\Container->resolveDependencies(Array)
#8 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build('App\\\\Http\\\\Middle...')
#9 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\\Container\\Container->resolve('App\\\\Http\\\\Middle...', Array)
#10 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(769): Illuminate\\Container\\Container->make('App\\\\Http\\\\Middle...', Array)
#11 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(160): Illuminate\\Foundation\\Application->make('App\\\\Http\\\\Middle...')
#12 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#13 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#14 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#15 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#16 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#17 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#18 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#19 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /www/wwwroot/fly.o-hahaha.com/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#31 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#32 /www/wwwroot/fly.o-hahaha.com/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#33 {main}
"} 
[2020-01-06 06:21:36] local.ERROR: The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths. {"exception":"[object] (RuntimeException(code: 0): The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths. at /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:43)
[stacktrace]
#0 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(28): Illuminate\\Encryption\\Encrypter->__construct('\\fR\\xDD#B>\\x0FO\\x82\\xAD\\x03\\xD0\\xF7\\xE1]...', 'AES-256-CBC')
#1 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(799): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#2 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build(Object(Closure))
#3 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\\Container\\Container->resolve('encrypter', Array)
#4 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(769): Illuminate\\Container\\Container->make('encrypter', Array)
#5 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(945): Illuminate\\Foundation\\Application->make('encrypter')
#6 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(873): Illuminate\\Container\\Container->resolveClass(Object(ReflectionParameter))
#7 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(834): Illuminate\\Container\\Container->resolveDependencies(Array)
#8 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build('App\\\\Http\\\\Middle...')
#9 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\\Container\\Container->resolve('App\\\\Http\\\\Middle...', Array)
#10 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(769): Illuminate\\Container\\Container->make('App\\\\Http\\\\Middle...', Array)
#11 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(209): Illuminate\\Foundation\\Application->make('App\\\\Http\\\\Middle...')
#12 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(183): Illuminate\\Foundation\\Http\\Kernel->terminateMiddleware(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
#13 /www/wwwroot/fly.o-hahaha.com/public/index.php(60): Illuminate\\Foundation\\Http\\Kernel->terminate(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
#14 {main}
"} 
[2020-01-06 06:23:22] local.ERROR: The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths. {"exception":"[object] (RuntimeException(code: 0): The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths. at /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:43)
[stacktrace]
#0 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(28): Illuminate\\Encryption\\Encrypter->__construct('\\fR\\xDD#B>\\x0FO\\x82\\xAD\\x03\\xD0\\xF7\\xE1]...', 'AES-256-CBC')
#1 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(799): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#2 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build(Object(Closure))
#3 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\\Container\\Container->resolve('encrypter', Array)
#4 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(769): Illuminate\\Container\\Container->make('encrypter', Array)
#5 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(945): Illuminate\\Foundation\\Application->make('encrypter')
#6 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(873): Illuminate\\Container\\Container->resolveClass(Object(ReflectionParameter))
#7 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(834): Illuminate\\Container\\Container->resolveDependencies(Array)
#8 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build('App\\\\Http\\\\Middle...')
#9 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\\Container\\Container->resolve('App\\\\Http\\\\Middle...', Array)
#10 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(769): Illuminate\\Container\\Container->make('App\\\\Http\\\\Middle...', Array)
#11 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(160): Illuminate\\Foundation\\Application->make('App\\\\Http\\\\Middle...')
#12 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#13 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#14 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#15 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#16 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#17 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#18 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#19 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /www/wwwroot/fly.o-hahaha.com/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#31 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#32 /www/wwwroot/fly.o-hahaha.com/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#33 {main}
"} 
[2020-01-06 06:23:22] local.ERROR: The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths. {"exception":"[object] (RuntimeException(code: 0): The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths. at /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:43)
[stacktrace]
#0 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(28): Illuminate\\Encryption\\Encrypter->__construct('\\fR\\xDD#B>\\x0FO\\x82\\xAD\\x03\\xD0\\xF7\\xE1]...', 'AES-256-CBC')
#1 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(799): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#2 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build(Object(Closure))
#3 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\\Container\\Container->resolve('encrypter', Array)
#4 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(769): Illuminate\\Container\\Container->make('encrypter', Array)
#5 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(945): Illuminate\\Foundation\\Application->make('encrypter')
#6 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(873): Illuminate\\Container\\Container->resolveClass(Object(ReflectionParameter))
#7 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(834): Illuminate\\Container\\Container->resolveDependencies(Array)
#8 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build('App\\\\Http\\\\Middle...')
#9 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\\Container\\Container->resolve('App\\\\Http\\\\Middle...', Array)
#10 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(769): Illuminate\\Container\\Container->make('App\\\\Http\\\\Middle...', Array)
#11 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(209): Illuminate\\Foundation\\Application->make('App\\\\Http\\\\Middle...')
#12 /www/wwwroot/fly.o-hahaha.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(183): Illuminate\\Foundation\\Http\\Kernel->terminateMiddleware(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
#13 /www/wwwroot/fly.o-hahaha.com/public/index.php(60): Illuminate\\Foundation\\Http\\Kernel->terminate(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
#14 {main}
"}

**Comment by Topcckin** [comment]
> 报错日志位于存储/日志目录下，如果没有日志请检查目录权限

您好，我看日志好像是加密出问题了。

**Comment by tokumeikoi** [comment]
删掉目录下.lock文件，.env文件重新cp .env.example文件后重新insall

**Comment by Topcckin** [comment]
删除目录下的.lock文件，和.env文件，重新cp之后，编辑.env文件填写数据库，还是没改变，仍然是500错误

**Comment by tokumeikoi** [comment]
完整的跟随教程走一遍是没有问题的。

**Comment by cyril-cheng** [comment]
请将v2board总目录设置为www用户755权限

**Comment by Topcckin** [comment]
网站目录是755，777我也试过了，也不行，不知道是不是我机子的问题，教程是debian和aapanel，我是centos和宝塔。

cyril-cheng <notifications@github.com> 于 2020年1月6日周一 21:39写道：

**Comment by Pinkpiglet** [comment]
lock文件导致的，删除即可显示登陆页面，但是登陆一直转圈

**Comment by Pinkpiglet** [comment]
删除lock文件，删除数据库，重新执行php artisan v2board:install即可
![image](https://user-images.githubusercontent.com/38532706/72209181-a266f400-34e6-11ea-971e-296d420522d3.png)

**Comment by zhangxiangping5146** [comment]
检查redis 状态，重启 redis
