### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by xlingzzy** [v2board/v2board#902]
在节点管理创建了一个直连节点和一个中转节点，但是想隐藏直连节点显示中转节点，尝试改过他们的权限组(订阅分配使用权限组2的节点。直连权限组1，中转权限组2或直连权限组1，中转权限组1、2)中转节点不能正常使用 必须把直连放到权限组2时中转才可以正常使用，这该怎么办

**Comment by Ovo-Kitty** [comment]
把显隐关掉就好了啊
