### ISSUE TITLE
[INFO]账户余额计算佣金问题

### ISSUE THREAD

**Issue by TerrorbladeART** [v2board/v2board#91]
[INFO]
php7.3
master 分支1.2.1版本
实际佣金只有0.5 .
而账户余额却有1元的佣金
后台修改佣金状态为 [确认中], 用户账户余额中的推广邀请金依然未变动.

![image](https://user-images.githubusercontent.com/59191279/76074868-fc5fd380-5fd6-11ea-9587-2f4046263e8f.png)
![image](https://user-images.githubusercontent.com/59191279/76074928-13062a80-5fd7-11ea-849c-1be951053a3e.png)
![image](https://user-images.githubusercontent.com/59191279/76075323-c2db9800-5fd7-11ea-8c22-e2ef2cbf9da5.png)

**Comment by tokumeikoi** [comment]
能否查询数据库user表看下commission_balance是多少？

**Comment by TerrorbladeART** [comment]
好，我用电脑的时候我截图看下

**Comment by tokumeikoi** [comment]
有查看吗
