### ISSUE TITLE
[Vulnerable] possible data breach

### ISSUE THREAD

**Issue by lotusproxy** [v2board/v2board#911]
We observed a serious data leak, probably uploading PHP to Protocols/ through some vulnerability, then using client controller / subscription to enable it to create a Trojan horse

**Comment by betaxab** [comment]
detail please

**Comment by lotusproxy** [comment]
> detail please

Telegram @fuckxsus

**Comment by coldice8** [comment]
> We observed a serious data leak, probably uploading PHP to Protocols/ through some vulnerability, then using client controller / subscription to enable it to create a Trojan horse

The problem is uploading php files. How is it uploaded? Can it be uploaded to that directory, then can't it be executed directly?

**Comment by lotusproxy** [comment]
Idk, we don't have any details/samples about that

But the breaches are obvious

**Comment by RPRX** [comment]
~~好久没写 PHP 了~~，简单看了下 v2board 的后端代码，分析如下：
1. 关于是否 SQL 注入，**暂未发现直接拼 SQL**，底层 Laravel 都是 PDO 参数绑定，不过要注意版本，我搜到 Laravel 低版自带漏洞
2. 直接写文件的话，似乎只有 app/Console/Commands/V2boardInstall.php 有相关操作，**需要检查下危险函数前是否有逻辑漏洞**
3. **可能是 XSS 攻击**，攻击者把一些前端代码插到数据库，管理员加载时执行，一些前后端框架自带防御机制（前端代码我没看）
4. **CSRF 的可能性不大**，因为不是特别好使，要部署一个管理员会访问的网站（TG 发消息让他打开？），而且浏览器逐年加限制
5. 代码里有 curl 等，**需要熟悉代码的人看看有没有 SSRF 类漏洞**，参考 https://websec.readthedocs.io/zh/latest/vuln/ssrf.html ，这个链接内容挺全的，~~我也是才搜到，那就不用继续写了~~，**较大的可能还有其它软件有漏洞，或者配置不当导致比如目录访问**

此前我看到一个比较明显的问题是有些人用 X-UI 会通过 HTTP 进行配置（非 HTTPS），REALITY 不需要域名更是加剧了这个问题，这不就是裸送给中间人嘛，密码再设得和 SSH 一样连服务器都送出去了，**建议把 X-UI 外网访问关了，通过 SSH 端口转发进行配置**

同理，如果一时定位不到漏洞，**可以先把 v2board admin 端等能内网化的都内网化，尽量减少暴露，并严格最小化各个软件的权限**
