### ISSUE TITLE
请教：域名被盗导致v2board无法通过域名登陆之补救措施

### ISSUE THREAD

**Issue by alexallen1** [v2board/v2board#917]
不懂就问啊，之前v2board aapanel设置的是二级域名，登陆面板设置的网站域名\订阅地址也是那个。
然后那个域名掌控权不在我这了，ping那个域名变成Name or service not known

请问补救措施~万分感谢~

**Comment by Cp0204** [comment]
/config/v2board.php

**Comment by alexallen1** [comment]
通过问chatgpt 监视文件变化  inotifywait -r -m -e modify,create,delete,move --format "%w%f" /文件路径
找到是/bootstrap/cache/config.php。然后把站点网址清空掉，终于解决了……没chatgpt 还真不知道怎么死..
