### ISSUE TITLE
PHP兼容问题 我宝塔里有7.4和7.2版本的PHP，v2提示我说我的版本过低网站就打不开了！怎么关掉版本提示！

### ISSUE THREAD

**Issue by 794786374** [v2board/v2board#919]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
1.7.4
--------

Briefly describe the problem you are experiencing
简单描述你遇到的问题

怎么关掉PHP版本检测
--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.4.0". You are running 7.3.31. in /www/wwwroot/vendor/composer/platform_check.php on line 24
--------

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by lotusproxy** [comment]
Docker
