### ISSUE TITLE
修改邮件配置后快速生效的方法

### ISSUE THREAD

**Issue by thank243** [v2board/v2board#92]
今天想试试mailgun。结果改了邮箱后执行config:cache后半天不生效。后来重启服务器后意外生效了。
测试发现需要重启邮件队列，之后立刻生效。
邮件错误日志移步数据库maillog里面查看，正常应该返回null。

**Comment by yanlianglai** [comment]
今天遇到了同样的问题 ，我还多了一个叫什么数据太长无法写入数据库，查了下failed_jobs 发现是redis的问题，光重启队列是没有用的，redis ，php同样要重启一下，立马就好了
