### ISSUE TITLE
[INFO]关于订阅升降级退款计算逻辑问题

### ISSUE THREAD

**Issue by TerrorbladeART** [v2board/v2board#93]
场景： 
网站：A网站试用规则为，试用时间为1个月，试用流量为1G。
用户：B用户在网站注册并进入试用组，那么此时B用户有一个月的试用时间并且只有1G流量
复现：当B用户此时购买某一套餐时（实际复现时是用户使用了同价优惠价购买，支付宝未测试。），系统会依据时间进行退款。
![B613309F-E34F-49C0-82BB-C9E07E627C88](https://user-images.githubusercontent.com/59191279/76100427-963f7480-6007-11ea-8a58-67cb87dae8c7.jpeg)
![95E3A7AF-3479-49E4-BADE-7B3303F694BE](https://user-images.githubusercontent.com/59191279/76100440-99d2fb80-6007-11ea-843c-a4ce3a00c778.jpeg)

**Comment by tokumeikoi** [comment]
不给试用订阅分配价格就没有价值了，这种问题就不要发issue了
