### ISSUE TITLE
[BUG]后端已经接入v2，但是个别节点不计算流量，也不扣除流量，其他节点正常

### ISSUE THREAD

**Issue by zkx8525** [v2board/v2board#943]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
1.7.4

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
后端已经接入v2，但是个别节点不计算流量，也不扣除流量，其他节点正常
就算使用bug节点也不会显示有在线客户端，尝试pm和队列重启无效果

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
<img width="96" alt="image" src="https://github.com/v2board/v2board/assets/109951664/f9d66313-6705-4ba3-a2bd-78a507be6df9">

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by QianChenJun** [comment]
解决了么，我也遇到了同样的问题。

**Comment by zkx8525** [comment]
> 

一直没解决，根本不知道问题所在，很服

**Comment by QianChenJun** [comment]
我后来把我那个前端的域名，由http改成了https就好了😂 但是太容易封IP了 我就不弄了

**Comment by zkx8525** [comment]
> 我后来把我那个前端的域名，由http改成了https就好了😂 但是太容易封IP了 我就不弄了

都是接入的https，跟这个没关系
