### ISSUE TITLE
1.7.4 Telegram功能无法使用机器人webhook 设置成功但是回到Telegram机器人不显示指令[BUG]

### ISSUE THREAD

**Issue by 794786374** [v2board/v2board#946]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
-------- 1.7.4

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------机器人令牌保存了 webhook 设置成功也开启机器人通知了，但是回到电报设置的机器人没反应。

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
![image](https://github.com/v2board/v2board/assets/88839101/01636bda-8249-4840-b6e7-59f45d3dd779)
![image](https://github.com/v2board/v2board/assets/88839101/978c2d17-9302-4c59-b081-a7120bb328cd)

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------

**Comment by vstar37** [comment]
有解决方案了吗
