### ISSUE TITLE
TLS headers customization

### ISSUE THREAD

**Issue by jitdor** [v2board/v2board#99]
Certain V2Ray clients, such as Kitsunebi on both Android and iOS, allows customization of the V2Ray TLSObject, such as the "serverName" and "allowInsecure" properties, which are currently not supported in V2board.

I hope the ability to specify a TLS hostname can be added in future releases as it allows for more creative configuration use cases.

Thank you!

**Comment by tokumeikoi** [comment]
1.2.3 support

**Comment by zigma4000** [comment]
Does it support TLSObject customization? If yes, is there any documentation for that?
